#if !defined(AFX_VDBLOCK_H__FB61FBC2_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDBLOCK_H__FB61FBC2_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdPrimary;
class CvdXProperties;
class CvdFigure;
class CvdPolyline;
class CvdLine;
class CvdArc;
class CvdInsert;
class CvdText;
class CvdCircle;
class CvdAttrib;
class CvdEllipse;
class CvdRect;
class CvdImage;
class CvdDimension;
class CvdPoint;
class CvdLayers;
class Cvd3DFace;
class CvdPolyface;
class CvdPolyhatch;
class CvdViewport;

/////////////////////////////////////////////////////////////////////////////
// CvdBlock wrapper class

class dllExport CvdBlock : public COleDispatchDriver
{
public:
	CvdBlock() {}		// Calls COleDispatchDriver default constructor
	CvdBlock(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdBlock(const CvdBlock& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetLabel();
	void SetLabel(LPCTSTR lpszNewValue);
	CString GetType();
	long GetId();
	CString GetHandle();
	void Update();
	void Erase();
	CvdPrimary Copy();
	CvdXProperties GetXProperties();
	BOOL GetDeleted();
	void SetDeleted(BOOL bNewValue);
	CvdFigure GetStart();
	CvdFigure GetLast();
	CvdFigure GetNext();
	CvdFigure GetPrevious();
	BOOL SetPosition(LPDISPATCH entity);
	CvdFigure GetItem(long Index);
	VARIANT GetBoundingBox();
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	VARIANT GetOrigin();
	void SetOrigin(const VARIANT& newValue);
	long GetCount();
	CvdPolyline AddPolyLine(const VARIANT& VertexArray);
	CvdLine AddLine(const VARIANT& StartPoint, const VARIANT& EndPoint);
	CvdArc AddArc(const VARIANT& CenterPoint, double Radius, double StartAngle, double EndAngle);
	CvdInsert InsertBlock(const VARIANT& InsertionPoint, LPCTSTR Name, double Xscale, double Yscale, double Rotation);
	CvdText AddText(LPCTSTR TextString, const VARIANT& InsertionPoint, double Height);
	CvdCircle AddCircle(const VARIANT& CenterPoint, double Radius);
	CvdAttrib AddAttrib(BOOL InVisibleMode, LPCTSTR TagString, LPCTSTR PromptString, LPCTSTR ValueString, const VARIANT& InsPoint, double Height);
	BOOL AddItem(LPDISPATCH Object);
	BOOL RemoveItem(LPDISPATCH Object);
	CvdEllipse AddEllipse(const VARIANT& CenterPoint, double MajorLength, double MinorLength);
	CvdRect AddRect(const VARIANT& InsertionPoint, double Width, double Height);
	CvdImage AddImage(LPCTSTR FileName, const VARIANT& InsertionPoint, double Scale);
	CvdDimension AddDimAligned(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition);
	CvdDimension AddDimRotated(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition, double RotationAngle);
	void ChangeOrder(LPDISPATCH Object, short ToBack);
	CvdPoint AddPoint(const VARIANT& Point);
	CString GetXrefPath();
	void SetXrefPath(LPCTSTR lpszNewValue);
	short GetXrefFlag();
	void SetXrefFlag(short nNewValue);
	CvdLayers GetXrefLayers();
	void XrefLayerControl();
	void XrefReLoad();
	Cvd3DFace Add3DFace(const VARIANT& VertexList);
	CvdPolyface AddPolyFace(const VARIANT& VertexList, const VARIANT& FaceList);
	CvdDimension AddDimDiameter(const VARIANT& DefPoint1, const VARIANT& DefPoint2);
	CvdDimension AddDimRadial(const VARIANT& CenterPoint, const VARIANT& DefPoint2);
	CvdPolyhatch AddPolyHatch();
	CvdViewport AddViewPort(const VARIANT& CenterPoint, double Width, double Height);
	CvdDimension AddDimAngular(const VARIANT& AngleVertex, const VARIANT& FirstEndPoint, const VARIANT& SecondEndPoint, const VARIANT& LinePosition);
	LPDISPATCH RenderToBitmap(long ImageWidth, long ImageHeight);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDBLOCK_H__FB61FBC2_F825_11D7_B650_0003B3008E71__INCLUDED_)
