// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdblock.h"

// Dispatch interfaces referenced by this interface
#include "vdPrimary.h"
#include "vdxproperties.h"
#include "vdFigure.h"
#include "vdpolyline.h"
#include "vdline.h"
#include "vdarc.h"
#include "vdInsert.h"
#include "vdtext.h"
#include "vdcircle.h"
#include "vdattrib.h"
#include "vdellipse.h"
#include "vdrect.h"
#include "vdimage.h"
#include "vddimension.h"
#include "vdPoint.h"
#include "vdLayers.h"
#include "vd3DFace.h"
#include "vdpolyface.h"
#include "vdpolyhatch.h"
#include "vdviewport.h"


/////////////////////////////////////////////////////////////////////////////
// CvdBlock properties

/////////////////////////////////////////////////////////////////////////////
// CvdBlock operations

CString CvdBlock::GetLabel()
{
	CString result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdBlock::SetLabel(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CvdBlock::GetType()
{
	CString result;
	InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CvdBlock::GetId()
{
	long result;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString CvdBlock::GetHandle()
{
	CString result;
	InvokeHelper(0x36, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdBlock::Update()
{
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdBlock::Erase()
{
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CvdPrimary CvdBlock::Copy()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdPrimary(pDispatch);
}

CvdXProperties CvdBlock::GetXProperties()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x64, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdXProperties(pDispatch);
}

BOOL CvdBlock::GetDeleted()
{
	BOOL result;
	InvokeHelper(0x1000, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CvdBlock::SetDeleted(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CvdFigure CvdBlock::GetStart()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdBlock::GetLast()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdBlock::GetNext()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ed, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdBlock::GetPrevious()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ee, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

BOOL CvdBlock::SetPosition(LPDISPATCH entity)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3ef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity);
	return result;
}

CvdFigure CvdBlock::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdFigure(pDispatch);
}

VARIANT CvdBlock::GetBoundingBox()
{
	VARIANT result;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CString CvdBlock::GetName()
{
	CString result;
	InvokeHelper(0x10, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdBlock::SetName(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

VARIANT CvdBlock::GetOrigin()
{
	VARIANT result;
	InvokeHelper(0x11, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CvdBlock::SetOrigin(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x11, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

long CvdBlock::GetCount()
{
	long result;
	InvokeHelper(0x12, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CvdPolyline CvdBlock::AddPolyLine(const VARIANT& VertexArray)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&VertexArray);
	return CvdPolyline(pDispatch);
}

CvdLine CvdBlock::AddLine(const VARIANT& StartPoint, const VARIANT& EndPoint)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&StartPoint, &EndPoint);
	return CvdLine(pDispatch);
}

CvdArc CvdBlock::AddArc(const VARIANT& CenterPoint, double Radius, double StartAngle, double EndAngle)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, Radius, StartAngle, EndAngle);
	return CvdArc(pDispatch);
}

CvdInsert CvdBlock::InsertBlock(const VARIANT& InsertionPoint, LPCTSTR Name, double Xscale, double Yscale, double Rotation)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_BSTR VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&InsertionPoint, Name, Xscale, Yscale, Rotation);
	return CvdInsert(pDispatch);
}

CvdText CvdBlock::AddText(LPCTSTR TextString, const VARIANT& InsertionPoint, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_R8;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		TextString, &InsertionPoint, Height);
	return CvdText(pDispatch);
}

CvdCircle CvdBlock::AddCircle(const VARIANT& CenterPoint, double Radius)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, Radius);
	return CvdCircle(pDispatch);
}

CvdAttrib CvdBlock::AddAttrib(BOOL InVisibleMode, LPCTSTR TagString, LPCTSTR PromptString, LPCTSTR ValueString, const VARIANT& InsPoint, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BOOL VTS_BSTR VTS_BSTR VTS_BSTR VTS_VARIANT VTS_R8;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		InVisibleMode, TagString, PromptString, ValueString, &InsPoint, Height);
	return CvdAttrib(pDispatch);
}

BOOL CvdBlock::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdBlock::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

CvdEllipse CvdBlock::AddEllipse(const VARIANT& CenterPoint, double MajorLength, double MinorLength)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, MajorLength, MinorLength);
	return CvdEllipse(pDispatch);
}

CvdRect CvdBlock::AddRect(const VARIANT& InsertionPoint, double Width, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&InsertionPoint, Width, Height);
	return CvdRect(pDispatch);
}

CvdImage CvdBlock::AddImage(LPCTSTR FileName, const VARIANT& InsertionPoint, double Scale)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_R8;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		FileName, &InsertionPoint, Scale);
	return CvdImage(pDispatch);
}

CvdDimension CvdBlock::AddDimAligned(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&ExtLine1Point, &ExtLine2Point, &LinePosition);
	return CvdDimension(pDispatch);
}

CvdDimension CvdBlock::AddDimRotated(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition, double RotationAngle)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_R8;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&ExtLine1Point, &ExtLine2Point, &LinePosition, RotationAngle);
	return CvdDimension(pDispatch);
}

void CvdBlock::ChangeOrder(LPDISPATCH Object, short ToBack)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_I2;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Object, ToBack);
}

CvdPoint CvdBlock::AddPoint(const VARIANT& Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Point);
	return CvdPoint(pDispatch);
}

CString CvdBlock::GetXrefPath()
{
	CString result;
	InvokeHelper(0x24, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdBlock::SetXrefPath(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x24, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

short CvdBlock::GetXrefFlag()
{
	short result;
	InvokeHelper(0x25, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdBlock::SetXrefFlag(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x25, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CvdLayers CvdBlock::GetXrefLayers()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x26, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayers(pDispatch);
}

void CvdBlock::XrefLayerControl()
{
	InvokeHelper(0x27, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdBlock::XrefReLoad()
{
	InvokeHelper(0x28, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

Cvd3DFace CvdBlock::Add3DFace(const VARIANT& VertexList)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x12c, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&VertexList);
	return Cvd3DFace(pDispatch);
}

CvdPolyface CvdBlock::AddPolyFace(const VARIANT& VertexList, const VARIANT& FaceList)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x12d, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&VertexList, &FaceList);
	return CvdPolyface(pDispatch);
}

CvdDimension CvdBlock::AddDimDiameter(const VARIANT& DefPoint1, const VARIANT& DefPoint2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x12e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&DefPoint1, &DefPoint2);
	return CvdDimension(pDispatch);
}

CvdDimension CvdBlock::AddDimRadial(const VARIANT& CenterPoint, const VARIANT& DefPoint2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x12f, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, &DefPoint2);
	return CvdDimension(pDispatch);
}

CvdPolyhatch CvdBlock::AddPolyHatch()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x130, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdPolyhatch(pDispatch);
}

CvdViewport CvdBlock::AddViewPort(const VARIANT& CenterPoint, double Width, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x131, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, Width, Height);
	return CvdViewport(pDispatch);
}

CvdDimension CvdBlock::AddDimAngular(const VARIANT& AngleVertex, const VARIANT& FirstEndPoint, const VARIANT& SecondEndPoint, const VARIANT& LinePosition)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x258, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&AngleVertex, &FirstEndPoint, &SecondEndPoint, &LinePosition);
	return CvdDimension(pDispatch);
}

LPDISPATCH CvdBlock::RenderToBitmap(long ImageWidth, long ImageHeight)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x3f2, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		ImageWidth, ImageHeight);
	return result;
}
