// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdcommand.h"


/////////////////////////////////////////////////////////////////////////////
// CvdCommand properties

/////////////////////////////////////////////////////////////////////////////
// CvdCommand operations

long CvdCommand::GetOpenLoops()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdCommand::Zoom(const VARIANT& Type, const VARIANT& FirstCorner, const VARIANT& OtherCorner)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Type, &FirstCorner, &OtherCorner);
}

void CvdCommand::Cancel()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CvdCommand::CmdPrintDialog(const VARIANT& WindowPoints, const VARIANT& Scale)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&WindowPoints, &Scale);
	return result;
}

void CvdCommand::RegenAll()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdCommand::LayerControl()
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CvdCommand::CmdLine(const VARIANT& ParamList)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&ParamList);
	return result;
}

BOOL CvdCommand::CmdPolyLine(const VARIANT& ParamList)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&ParamList);
	return result;
}

BOOL CvdCommand::CmdArc(const VARIANT& CenterPoint, const VARIANT& Radius, const VARIANT& StartAngle, const VARIANT& EndAngle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&CenterPoint, &Radius, &StartAngle, &EndAngle);
	return result;
}

BOOL CvdCommand::CmdCircle(const VARIANT& CenterPoint, const VARIANT& Radius)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&CenterPoint, &Radius);
	return result;
}

void CvdCommand::EditAttrib(const VARIANT& EntityObject)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &EntityObject);
}

BOOL CvdCommand::CmdMove(const VARIANT& SelSet, const VARIANT& FromPoint, const VARIANT& ToPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &FromPoint, &ToPoint);
	return result;
}

BOOL CvdCommand::CmdRotate(const VARIANT& SelSet, const VARIANT& BasePoint, const VARIANT& Rotation)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &BasePoint, &Rotation);
	return result;
}

BOOL CvdCommand::CmdScale(const VARIANT& SelSet, const VARIANT& BasePoint, const VARIANT& ScaleFactor)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &BasePoint, &ScaleFactor);
	return result;
}

BOOL CvdCommand::CmdCopy(const VARIANT& SelSet, const VARIANT& FromPoint, const VARIANT& ToPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &FromPoint, &ToPoint);
	return result;
}

BOOL CvdCommand::CmdErase(const VARIANT& SelSet)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet);
	return result;
}

BOOL CvdCommand::CmdSelect(const VARIANT& SelectMode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelectMode);
	return result;
}

void CvdCommand::vdCommand(LPCTSTR CommandNameString, const VARIANT& Param1, const VARIANT& Param2, const VARIANT& Param3, const VARIANT& Param4, const VARIANT& Param5, const VARIANT& Param6, const VARIANT& Param7, const VARIANT& Param8, 
		const VARIANT& Param9, const VARIANT& Param10)
{
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 CommandNameString, &Param1, &Param2, &Param3, &Param4, &Param5, &Param6, &Param7, &Param8, &Param9, &Param10);
}

BOOL CvdCommand::CmdWriteBlock(const VARIANT& SelSetOrBlockName, const VARIANT& OriginPoint, const VARIANT& FileName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSetOrBlockName, &OriginPoint, &FileName);
	return result;
}

BOOL CvdCommand::CmdInsertBlockDialog()
{
	BOOL result;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CvdCommand::CmdInsert(const VARIANT& BlockName, const VARIANT& InsertionPoint, const VARIANT& ScaleX, const VARIANT& ScaleY, const VARIANT& Angle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&BlockName, &InsertionPoint, &ScaleX, &ScaleY, &Angle);
	return result;
}

BOOL CvdCommand::CmdMakeBlock(const VARIANT& BlockName, const VARIANT& InsertionPoint, const VARIANT& SelectionSet)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&BlockName, &InsertionPoint, &SelectionSet);
	return result;
}

BOOL CvdCommand::CmdClipCopy(const VARIANT& SelectionSet)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelectionSet);
	return result;
}

BOOL CvdCommand::CmdClipCut(const VARIANT& SelectionSet)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelectionSet);
	return result;
}

BOOL CvdCommand::CmdClipPaste(const VARIANT& InsertionPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&InsertionPoint);
	return result;
}

BOOL CvdCommand::CmdText(const VARIANT& TextString, const VARIANT& InsertionPoint, const VARIANT& RotationAngle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&TextString, &InsertionPoint, &RotationAngle);
	return result;
}

BOOL CvdCommand::CmdTextStyle(const VARIANT& StyleName, const VARIANT& FontFileName, const VARIANT& Height, const VARIANT& Width)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&StyleName, &FontFileName, &Height, &Width);
	return result;
}

BOOL CvdCommand::Undo(LPCTSTR Option)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Option);
	return result;
}

void CvdCommand::Redo()
{
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CvdCommand::CmdExplode(const VARIANT& SelSet)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet);
	return result;
}

BOOL CvdCommand::CmdExtend(const VARIANT& BoundEntities, const VARIANT& ObjectToExtend)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&BoundEntities, &ObjectToExtend);
	return result;
}

BOOL CvdCommand::CmdTrim(const VARIANT& BoundEntities, const VARIANT& ObjectToTrim)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&BoundEntities, &ObjectToTrim);
	return result;
}

BOOL CvdCommand::CmdFillet(const VARIANT& EntityObject1, const VARIANT& EntityObject2)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&EntityObject1, &EntityObject2);
	return result;
}

BOOL CvdCommand::CmdOffset(const VARIANT& entity, const VARIANT& dist, const VARIANT& side)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&entity, &dist, &side);
	return result;
}

BOOL CvdCommand::CmdBreak(const VARIANT& entity, const VARIANT& FirstPoint, const VARIANT& SecondPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&entity, &FirstPoint, &SecondPoint);
	return result;
}

void CvdCommand::Pan()
{
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CvdCommand::CmdImage(LPCTSTR FileName, const VARIANT& InsertionPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, &InsertionPoint);
	return result;
}

BOOL CvdCommand::CmdDim(long Type, const VARIANT& DefPoints, const VARIANT& Position, double Rotation)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT VTS_VARIANT VTS_R8;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Type, &DefPoints, &Position, Rotation);
	return result;
}

BOOL CvdCommand::CmdPoint(const VARIANT& Point)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Point);
	return result;
}

BOOL CvdCommand::View3D(const VARIANT& Arguments)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Arguments);
	return result;
}

BOOL CvdCommand::UCS(const VARIANT& org, const VARIANT& px, const VARIANT& py)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&org, &px, &py);
	return result;
}

BOOL CvdCommand::UCSWorld()
{
	BOOL result;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CvdCommand::LookAt(const VARIANT& cameraPosition, const VARIANT& targetPosition)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&cameraPosition, &targetPosition);
	return result;
}

BOOL CvdCommand::CmdRotate3d(const VARIANT& RotAxis, const VARIANT& SelSet, const VARIANT& AxisPoints, const VARIANT& RotationAngle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&RotAxis, &SelSet, &AxisPoints, &RotationAngle);
	return result;
}

BOOL CvdCommand::CmdMirror(const VARIANT& SelSet, const VARIANT& MirrorLinePoint1, const VARIANT& MirrorLinePoint2, const VARIANT& keepSourceObjects)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &MirrorLinePoint1, &MirrorLinePoint2, &keepSourceObjects);
	return result;
}

BOOL CvdCommand::CmdArrayRectangular(const VARIANT& SelSet, const VARIANT& NumberofRows, const VARIANT& NumberofColumns, const VARIANT& RowsDist, const VARIANT& ColumnsDist)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &NumberofRows, &NumberofColumns, &RowsDist, &ColumnsDist);
	return result;
}

BOOL CvdCommand::CmdArrayPolar(const VARIANT& SelSet, const VARIANT& CenterPoint, const VARIANT& NumOfItems, const VARIANT& FillAngle, const VARIANT& RotateObjects)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &CenterPoint, &NumOfItems, &FillAngle, &RotateObjects);
	return result;
}

BOOL CvdCommand::CmdBox3d(const VARIANT& InsertionPoint, const VARIANT& Length, const VARIANT& Width, const VARIANT& Height, const VARIANT& RotationAngle)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&InsertionPoint, &Length, &Width, &Height, &RotationAngle);
	return result;
}

BOOL CvdCommand::CmdCone(const VARIANT& CenterPoint, const VARIANT& BaseRadius, const VARIANT& TopRadius, const VARIANT& Height, const VARIANT& NumSegments)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&CenterPoint, &BaseRadius, &TopRadius, &Height, &NumSegments);
	return result;
}

BOOL CvdCommand::Cmd3DMesh(const VARIANT& Msize, const VARIANT& Nsize, const VARIANT& VertexList)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Msize, &Nsize, &VertexList);
	return result;
}

BOOL CvdCommand::CmdPlineToMesh(const VARIANT& PlineEntity, const VARIANT& Thickness, const VARIANT& EdgeVisibility)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&PlineEntity, &Thickness, &EdgeVisibility);
	return result;
}

BOOL CvdCommand::CmdSphere(const VARIANT& Center, const VARIANT& Radius, const VARIANT& longitudinalsegs, const VARIANT& latitudinalsegs)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Center, &Radius, &longitudinalsegs, &latitudinalsegs);
	return result;
}

BOOL CvdCommand::Cmd3dFace(const VARIANT& VeretxArray)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&VeretxArray);
	return result;
}

BOOL CvdCommand::CmdEllipse(const VARIANT& CenterPoint, const VARIANT& Axis1Pos, const VARIANT& Axis2Len)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&CenterPoint, &Axis1Pos, &Axis2Len);
	return result;
}

BOOL CvdCommand::CmdRect(const VARIANT& Point1, const VARIANT& Point2)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Point1, &Point2);
	return result;
}

BOOL CvdCommand::CmdXref(LPCTSTR CommandOption, LPCTSTR XrefName, double InsertionX, double InsertionY, double InsertionZ, double Xscale, double Yscale, double Zscale, double RotationAngle, short ToBack)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_I2;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		CommandOption, XrefName, InsertionX, InsertionY, InsertionZ, Xscale, Yscale, Zscale, RotationAngle, ToBack);
	return result;
}

void CvdCommand::LayOutControl()
{
	InvokeHelper(0x39, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CvdCommand::CmdStretch(const VARIANT& SelSet, const VARIANT& WindowPoint1, const VARIANT& WindowPoint2, const VARIANT& FromPoint, const VARIANT& ToPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&SelSet, &WindowPoint1, &WindowPoint2, &FromPoint, &ToPoint);
	return result;
}

void CvdCommand::Cancel1()
{
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
