// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vddimstyles.h"

// Dispatch interfaces referenced by this interface
#include "vddimstyle.h"


/////////////////////////////////////////////////////////////////////////////
// CvdDimstyles properties

/////////////////////////////////////////////////////////////////////////////
// CvdDimstyles operations

CvdDimstyle CvdDimstyles::GetStart()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdDimstyle(pDispatch);
}

CvdDimstyle CvdDimstyles::GetLast()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdDimstyle(pDispatch);
}

CvdDimstyle CvdDimstyles::GetNext()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ed, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdDimstyle(pDispatch);
}

CvdDimstyle CvdDimstyles::GetPrevious()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ee, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdDimstyle(pDispatch);
}

BOOL CvdDimstyles::SetPosition(LPDISPATCH entity)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3ef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity);
	return result;
}

CvdDimstyle CvdDimstyles::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdDimstyle(pDispatch);
}

long CvdDimstyles::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CvdDimstyle CvdDimstyles::Add(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdDimstyle(pDispatch);
}

CvdDimstyle CvdDimstyles::FindName(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdDimstyle(pDispatch);
}

BOOL CvdDimstyles::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdDimstyles::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}
