#if !defined(AFX_VDDIMSTYLE_H__FB61FBBC_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDDIMSTYLE_H__FB61FBBC_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdPrimary;
class CvdXProperties;

/////////////////////////////////////////////////////////////////////////////
// CvdDimstyle wrapper class

class CvdDimstyle : public COleDispatchDriver
{
public:
	CvdDimstyle() {}		// Calls COleDispatchDriver default constructor
	CvdDimstyle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdDimstyle(const CvdDimstyle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetLabel();
	void SetLabel(LPCTSTR lpszNewValue);
	CString GetType();
	long GetId();
	CString GetHandle();
	void Update();
	void Erase();
	CvdPrimary Copy();
	CvdXProperties GetXProperties();
	BOOL GetDeleted();
	void SetDeleted(BOOL bNewValue);
	CString GetStyleName();
	void SetStyleName(LPCTSTR lpszNewValue);
	CString GetArrowName();
	void SetArrowName(LPCTSTR lpszNewValue);
	double GetArrowSize();
	void SetArrowSize(double newValue);
	CString GetTextStyle();
	void SetTextStyle(LPCTSTR lpszNewValue);
	double GetTextHeight();
	void SetTextHeight(double newValue);
	double GetTextDist();
	void SetTextDist(double newValue);
	short GetTextHorJust();
	void SetTextHorJust(short nNewValue);
	short GetTextVerJust();
	void SetTextVerJust(short nNewValue);
	short GetTextHorRotation();
	void SetTextHorRotation(short nNewValue);
	short GetTextColor();
	void SetTextColor(short nNewValue);
	short GetExtLineColor();
	void SetExtLineColor(short nNewValue);
	double GetExtLineDist1();
	void SetExtLineDist1(double newValue);
	double GetExtLineDist2();
	void SetExtLineDist2(double newValue);
	short GetExtLineVisible();
	void SetExtLineVisible(short nNewValue);
	double GetScaleFactor();
	void SetScaleFactor(double newValue);
	short GetDecimalPrecision();
	void SetDecimalPrecision(short nNewValue);
	double GetLinearScaleFactor();
	void SetLinearScaleFactor(double newValue);
	short GetLineIsInvisible();
	long GetDimAunit();
	short GetDimAdec();
	long GetDimLunit();
	void SetLineIsInvisible(short nNewValue);
	void SetDimAunit(long nNewValue);
	void SetDimAdec(short nNewValue);
	void SetDimLunit(long nNewValue);
	short GetDimTol();
	double GetDimTp();
	void SetDimTol(short nNewValue);
	void SetDimTp(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDDIMSTYLE_H__FB61FBBC_F825_11D7_B650_0003B3008E71__INCLUDED_)
