#if !defined(AFX_VDDIMSTYLES_H__FB61FBBD_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDDIMSTYLES_H__FB61FBBD_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdDimstyle;

/////////////////////////////////////////////////////////////////////////////
// CvdDimstyles wrapper class

class CvdDimstyles : public COleDispatchDriver
{
public:
	CvdDimstyles() {}		// Calls COleDispatchDriver default constructor
	CvdDimstyles(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdDimstyles(const CvdDimstyles& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CvdDimstyle GetStart();
	CvdDimstyle GetLast();
	CvdDimstyle GetNext();
	CvdDimstyle GetPrevious();
	BOOL SetPosition(LPDISPATCH entity);
	CvdDimstyle GetItem(long Index);
	long GetCount();
	CvdDimstyle Add(LPCTSTR Name);
	CvdDimstyle FindName(LPCTSTR Name);
	BOOL AddItem(LPDISPATCH Object);
	BOOL RemoveItem(LPDISPATCH Object);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDDIMSTYLES_H__FB61FBBD_F825_11D7_B650_0003B3008E71__INCLUDED_)
