// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vddocument.h"

// Dispatch interfaces referenced by this interface
#include "vdblocks.h"
#include "vdentities.h"
#include "vdLayers.h"
#include "vdprint.h"
#include "vdselections.h"
#include "vdTextstyles.h"
#include "vdFigure.h"
#include "vdPrimary.h"
#include "vddimstyles.h"
#include "vdLights.h"
#include "vdlayouts.h"
#include "vdlayout.h"


/////////////////////////////////////////////////////////////////////////////
// CvdDocument properties

/////////////////////////////////////////////////////////////////////////////
// CvdDocument operations

double CvdDocument::GetOriginX()
{
	double result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetOriginX(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetViewSize()
{
	double result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetViewSize(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x2, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetOriginY()
{
	double result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetOriginY(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x3, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

CString CvdDocument::GetFileName()
{
	CString result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetFileName(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

void CvdDocument::SetOrthoMode(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x5, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CvdDocument::GetOrthoMode()
{
	BOOL result;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CvdDocument::GetIDCount()
{
	long result;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveColor(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetActiveColor()
{
	long result;
	InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetBasePoint(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x8, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT CvdDocument::GetBasePoint()
{
	VARIANT result;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetGridMode(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CvdDocument::GetGridMode()
{
	BOOL result;
	InvokeHelper(0x9, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetGridSpace(double xvalue, double yvalue)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 xvalue, yvalue);
}

void CvdDocument::GetGridSpace(double* xvalue, double* yvalue)
{
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(0xfd2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 xvalue, yvalue);
}

void CvdDocument::SetOsnapMode(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetOsnapMode()
{
	short result;
	InvokeHelper(0xb, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveLayer(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CvdDocument::GetActiveLayer()
{
	CString result;
	InvokeHelper(0xc, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveTextStyle(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CvdDocument::GetActiveTextStyle()
{
	CString result;
	InvokeHelper(0xd, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CvdBlocks CvdDocument::GetBlocks()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xe, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdBlocks(pDispatch);
}

CvdEntities CvdDocument::GetEntities()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xf, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdEntities(pDispatch);
}

CvdLayers CvdDocument::GetLayers()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x10, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayers(pDispatch);
}

CvdPrint CvdDocument::GetPrinter()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x11, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdPrint(pDispatch);
}

CvdSelections CvdDocument::GetSelections()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x12, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdSelections(pDispatch);
}

CvdTextstyles CvdDocument::GetTextStyles()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x13, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdTextstyles(pDispatch);
}

void CvdDocument::SetActivePenWidth(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x14, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetActivePenWidth()
{
	double result;
	InvokeHelper(0x14, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveTextHeight(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x15, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetActiveTextHeight()
{
	double result;
	InvokeHelper(0x15, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveFillMode(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x16, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetActiveFillMode()
{
	short result;
	InvokeHelper(0x16, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveFillColor(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x17, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetActiveFillColor()
{
	long result;
	InvokeHelper(0x17, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveFillBkColor(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x18, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetActiveFillBkColor()
{
	long result;
	InvokeHelper(0x18, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveTextHorJustify(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x19, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetActiveTextHorJustify()
{
	long result;
	InvokeHelper(0x19, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActiveTextVerJustify(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetActiveTextVerJustify()
{
	long result;
	InvokeHelper(0x1a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetLineTypeScale(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x1b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetLineTypeScale()
{
	double result;
	InvokeHelper(0x1b, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetDwgAlternateFontFile(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CvdDocument::GetDwgAlternateFontFile()
{
	CString result;
	InvokeHelper(0x1c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

double CvdDocument::GetViewWidth()
{
	double result;
	InvokeHelper(0x1d, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

BOOL CvdDocument::SaveAs(LPCTSTR FileName, long CadVer)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, CadVer);
	return result;
}

VARIANT CvdDocument::GetBoundExtends()
{
	VARIANT result;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

BOOL CvdDocument::New()
{
	BOOL result;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CvdFigure CvdDocument::GetEntityFromPOINT(const VARIANT& Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Point);
	return CvdFigure(pDispatch);
}

BOOL CvdDocument::IsModified()
{
	BOOL result;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CvdDocument::Save()
{
	BOOL result;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CvdDocument::Open(LPCTSTR FileName, long WindowHandleToPlaceCaption, short DwgFileChecking)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I2;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, WindowHandleToPlaceCaption, DwgFileChecking);
	return result;
}

CvdPrimary CvdDocument::GetFromID(long ID)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		ID);
	return CvdPrimary(pDispatch);
}

void CvdDocument::SetSnapMode(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x27, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CvdDocument::GetSnapMode()
{
	BOOL result;
	InvokeHelper(0x27, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetSnapSpace(double xvalue, double yvalue)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 xvalue, yvalue);
}

void CvdDocument::GetSnapSpace(double* xvalue, double* yvalue)
{
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(0xfd3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 xvalue, yvalue);
}

VARIANT CvdDocument::GetLimits()
{
	VARIANT result;
	InvokeHelper(0x29, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetLimits(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x29, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

void CvdDocument::SetSupportPath(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CvdDocument::GetSupportPath()
{
	CString result;
	InvokeHelper(0x2a, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CvdDocument::GetGripFromPOINT(const VARIANT& Point, LPDISPATCH* entity, short* Index)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_PDISPATCH VTS_PI2;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Point, entity, Index);
	return result;
}

void CvdDocument::SetActiveDimStyle(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CvdDocument::GetActiveDimStyle()
{
	CString result;
	InvokeHelper(0x2c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CvdDimstyles CvdDocument::GetDimStyles()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x2d, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdDimstyles(pDispatch);
}

CvdPrimary CvdDocument::GetFromHandle(LPCTSTR Handle)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Handle);
	return CvdPrimary(pDispatch);
}

void CvdDocument::SetPtSize(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x2f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetPtSize()
{
	double result;
	InvokeHelper(0x2f, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetPtMode(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x30, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetPtMode()
{
	long result;
	InvokeHelper(0x30, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetActivePenStyle(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x31, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetActivePenStyle()
{
	short result;
	InvokeHelper(0x31, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

LPDISPATCH CvdDocument::RenderToBitmap(long ImageWidth, long ImageHeight, const VARIANT& LowerLeftPoint, const VARIANT& UperRightPoint)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		ImageWidth, ImageHeight, &LowerLeftPoint, &UperRightPoint);
	return result;
}

CvdFigure CvdDocument::Get3dEntityFromPOINT(const VARIANT& Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Point);
	return CvdFigure(pDispatch);
}

void CvdDocument::SetAxis3DRotations(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x34, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT CvdDocument::GetAxis3DRotations()
{
	VARIANT result;
	InvokeHelper(0x34, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetTargetPoint(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x35, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT CvdDocument::GetTargetPoint()
{
	VARIANT result;
	InvokeHelper(0x35, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetView3DMode(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x36, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdDocument::GetView3DMode()
{
	long result;
	InvokeHelper(0x36, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetShowEdge(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x37, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetShowEdge()
{
	short result;
	InvokeHelper(0x37, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetLensAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x136, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetLensAngle()
{
	double result;
	InvokeHelper(0x136, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetFocalLength(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x137, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetFocalLength()
{
	double result;
	InvokeHelper(0x137, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetPerspectiveMod(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x138, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetPerspectiveMod()
{
	short result;
	InvokeHelper(0x138, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::RenderToDC(long destDC, const VARIANT& LowerLeftPoint, const VARIANT& UperRirghtPoint, short destWidthPix, short destHeightPix)
{
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT VTS_VARIANT VTS_I2 VTS_I2;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 destDC, &LowerLeftPoint, &UperRirghtPoint, destWidthPix, destHeightPix);
}

VARIANT CvdDocument::Purge(LPCTSTR PurgeFlag)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		PurgeFlag);
	return result;
}

void CvdDocument::SetModifiedFlag(BOOL Value)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Value);
}

CvdLights CvdDocument::GetLights()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x12c, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLights(pDispatch);
}

long CvdDocument::SaveToMemory(VARIANT* ByteArray)
{
	long result;
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x12d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ByteArray);
	return result;
}

void CvdDocument::CreateFromMemory(const VARIANT& ByteArray, long size)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_I4;
	InvokeHelper(0x12e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ByteArray, size);
}

double CvdDocument::GetPixelSize()
{
	double result;
	InvokeHelper(0x12f, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

CvdLayouts CvdDocument::GetLayOuts()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x130, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayouts(pDispatch);
}

void CvdDocument::SetRefActiveLayOut(LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x131, DISPATCH_PROPERTYPUTREF, VT_EMPTY, NULL, parms,
		 newValue);
}

CvdLayout CvdDocument::GetActiveLayOut()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x131, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayout(pDispatch);
}

CvdEntities CvdDocument::GetActiveLayOutEntities()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x132, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdEntities(pDispatch);
}

void CvdDocument::AddPictureToList(LPCTSTR Name, const VARIANT& ByteArray)
{
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x134, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Name, &ByteArray);
}

CString CvdDocument::GetFileVersion()
{
	CString result;
	InvokeHelper(0x199, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetDefaultLineWeight(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x3e8, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetDefaultLineWeight()
{
	short result;
	InvokeHelper(0x3e8, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetLineWeightDisplay(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetLineWeightDisplay()
{
	short result;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetUndoLimit(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xe11, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetUndoLimit()
{
	short result;
	InvokeHelper(0xe11, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

VARIANT CvdDocument::GetLastPoint()
{
	VARIANT result;
	InvokeHelper(0xe57, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetAngbase(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0xec9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

void CvdDocument::SetAngdir(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xeca, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CvdDocument::SetAunits(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xecb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CvdDocument::SetAuprec(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xecc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CvdDocument::SetLunits(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xecd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CvdDocument::SetLuprec(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xece, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

double CvdDocument::GetAngbase()
{
	double result;
	InvokeHelper(0xec9, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

short CvdDocument::GetAngdir()
{
	short result;
	InvokeHelper(0xeca, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

long CvdDocument::GetAunits()
{
	long result;
	InvokeHelper(0xecb, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

short CvdDocument::GetAuprec()
{
	short result;
	InvokeHelper(0xecc, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

long CvdDocument::GetLunits()
{
	long result;
	InvokeHelper(0xecd, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

short CvdDocument::GetLuprec()
{
	short result;
	InvokeHelper(0xece, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::ClearUndoMem()
{
	InvokeHelper(0xfac, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CvdLayout CvdDocument::GetModel()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xfaf, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayout(pDispatch);
}

void CvdDocument::SetSnapAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0xfd4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double CvdDocument::GetSnapAngle()
{
	double result;
	InvokeHelper(0xfd4, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetSnapStyle(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xfd5, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetSnapStyle()
{
	short result;
	InvokeHelper(0xfd5, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetSnapIso(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xfd6, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short CvdDocument::GetSnapIso()
{
	short result;
	InvokeHelper(0xfd6, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetSnapBase(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xfd7, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT CvdDocument::GetSnapBase()
{
	VARIANT result;
	InvokeHelper(0xfd7, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CvdFigure CvdDocument::GetEntityFromPointEx(const VARIANT& Point, LPDISPATCH* mat)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_PDISPATCH;
	InvokeHelper(0xfd8, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Point, mat);
	return CvdFigure(pDispatch);
}

BOOL CvdDocument::GetMouseOverEntity(const VARIANT& pt, LPDISPATCH* Outer, LPDISPATCH* Inner, LPDISPATCH* mat2world)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_PDISPATCH VTS_PDISPATCH VTS_PDISPATCH;
	InvokeHelper(0x1003, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&pt, Outer, Inner, mat2world);
	return result;
}

void CvdDocument::SetGripBlock(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfe8, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CvdDocument::GetGripBlock()
{
	BOOL result;
	InvokeHelper(0xfe8, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetKeepAttributeHeight(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xff2, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CvdDocument::GetKeepAttributeHeight()
{
	BOOL result;
	InvokeHelper(0xff2, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CvdDocument::SetFileProperties(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xff3, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT CvdDocument::GetFileProperties()
{
	VARIANT result;
	InvokeHelper(0xff3, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

long CvdDocument::GetFileError()
{
	long result;
	InvokeHelper(0xff6, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}
