// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdentities.h"

// Dispatch interfaces referenced by this interface
#include "vdFigure.h"
#include "vdPolyline.h"
#include "vdLine.h"
#include "vdArc.h"
#include "vdText.h"
#include "vdCircle.h"
#include "vdInsert.h"
#include "vdAttrib.h"
#include "vdEllipse.h"
#include "vdRect.h"
#include "vdImage.h"
#include "vdDimension.h"
#include "vdPoint.h"
#include "vd3DFace.h"
#include "vdPolyface.h"
#include "vdPolyhatch.h"
#include "vdViewport.h"


/////////////////////////////////////////////////////////////////////////////
// CvdEntities properties

/////////////////////////////////////////////////////////////////////////////
// CvdEntities operations

CvdFigure CvdEntities::GetStart()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdEntities::GetLast()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdEntities::GetNext()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ed, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdEntities::GetPrevious()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ee, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

BOOL CvdEntities::SetPosition(LPDISPATCH entity)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3ef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity);
	return result;
}

CvdFigure CvdEntities::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdFigure(pDispatch);
}

long CvdEntities::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CvdFigure CvdEntities::Add(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdFigure(pDispatch);
}

CvdFigure CvdEntities::FindName(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdFigure(pDispatch);
}

BOOL CvdEntities::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdEntities::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

void CvdEntities::ChangeOrder(LPDISPATCH Object, short ToBack)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_I2;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Object, ToBack);
}

void CvdEntities::EraseAll()
{
	InvokeHelper(0x64, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CvdPolyline CvdEntities::AddPolyLine(const VARIANT& VertexArray)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&VertexArray);
	return CvdPolyline(pDispatch);
}

CvdLine CvdEntities::AddLine(const VARIANT& StartPoint, const VARIANT& EndPoint)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&StartPoint, &EndPoint);
	return CvdLine(pDispatch);
}

CvdArc CvdEntities::AddArc(const VARIANT& CenterPoint, double Radius, double StartAngle, double EndAngle)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x67, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, Radius, StartAngle, EndAngle);
	return CvdArc(pDispatch);
}

CvdText CvdEntities::AddText(LPCTSTR TextString, const VARIANT& InsertionPoint, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_R8;
	InvokeHelper(0x68, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		TextString, &InsertionPoint, Height);
	return CvdText(pDispatch);
}

CvdCircle CvdEntities::AddCircle(const VARIANT& CenterPoint, double Radius)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8;
	InvokeHelper(0x69, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, Radius);
	return CvdCircle(pDispatch);
}

CvdInsert CvdEntities::InsertBlock(const VARIANT& InsertionPoint, LPCTSTR Name, double Xscale, double Yscale, double Rotation)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_BSTR VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&InsertionPoint, Name, Xscale, Yscale, Rotation);
	return CvdInsert(pDispatch);
}

CvdAttrib CvdEntities::AddAttrib(BOOL InVisibleMode, LPCTSTR TagString, LPCTSTR PromptString, LPCTSTR ValueString, const VARIANT& InsPoint, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BOOL VTS_BSTR VTS_BSTR VTS_BSTR VTS_VARIANT VTS_R8;
	InvokeHelper(0x6b, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		InVisibleMode, TagString, PromptString, ValueString, &InsPoint, Height);
	return CvdAttrib(pDispatch);
}

CvdEllipse CvdEntities::AddEllipse(const VARIANT& CenterPoint, double MajorLength, double MinorLength)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, MajorLength, MinorLength);
	return CvdEllipse(pDispatch);
}

CvdRect CvdEntities::AddRect(const VARIANT& InsertionPoint, double Width, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x6f, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&InsertionPoint, Width, Height);
	return CvdRect(pDispatch);
}

CvdImage CvdEntities::AddImage(LPCTSTR FileName, const VARIANT& InsertionPoint, double Scale)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_R8;
	InvokeHelper(0x70, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		FileName, &InsertionPoint, Scale);
	return CvdImage(pDispatch);
}

CvdDimension CvdEntities::AddDimAligned(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x71, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&ExtLine1Point, &ExtLine2Point, &LinePosition);
	return CvdDimension(pDispatch);
}

CvdDimension CvdEntities::AddDimRotated(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition, double RotationAngle)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_R8;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&ExtLine1Point, &ExtLine2Point, &LinePosition, RotationAngle);
	return CvdDimension(pDispatch);
}

CvdPoint CvdEntities::AddPoint(const VARIANT& Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Point);
	return CvdPoint(pDispatch);
}

Cvd3DFace CvdEntities::Add3DFace(const VARIANT& VertexList)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&VertexList);
	return Cvd3DFace(pDispatch);
}

CvdPolyface CvdEntities::AddPolyFace(const VARIANT& VertexList, const VARIANT& FaceList)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&VertexList, &FaceList);
	return CvdPolyface(pDispatch);
}

CvdDimension CvdEntities::AddDimDiameter(const VARIANT& DefPoint1, const VARIANT& DefPoint2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&DefPoint1, &DefPoint2);
	return CvdDimension(pDispatch);
}

CvdDimension CvdEntities::AddDimRadial(const VARIANT& CenterPoint, const VARIANT& DefPoint2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, &DefPoint2);
	return CvdDimension(pDispatch);
}

CvdPolyhatch CvdEntities::AddPolyHatch()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdPolyhatch(pDispatch);
}

CvdViewport CvdEntities::AddViewPort(const VARIANT& CenterPoint, double Width, double Height)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&CenterPoint, Width, Height);
	return CvdViewport(pDispatch);
}

CvdDimension CvdEntities::AddDimAngular(const VARIANT& AngleVertex, const VARIANT& FirstEndPoint, const VARIANT& SecondEndPoint, const VARIANT& LinePosition)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&AngleVertex, &FirstEndPoint, &SecondEndPoint, &LinePosition);
	return CvdDimension(pDispatch);
}
