#if !defined(AFX_VDENTITIES_H__FB61FBA4_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDENTITIES_H__FB61FBA4_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdFigure;
class CvdPolyline;
class CvdLine;
class CvdArc;
class CvdText;
class CvdCircle;
class CvdInsert;
class CvdAttrib;
class CvdEllipse;
class CvdRect;
class CvdImage;
class CvdDimension;
class CvdPoint;
class Cvd3DFace;
class CvdPolyface;
class CvdPolyhatch;
class CvdViewport;

/////////////////////////////////////////////////////////////////////////////
// CvdEntities wrapper class

class dllExport CvdEntities : public COleDispatchDriver
{
public:
	CvdEntities() {}		// Calls COleDispatchDriver default constructor
	CvdEntities(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdEntities(const CvdEntities& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CvdFigure GetStart();
	CvdFigure GetLast();
	CvdFigure GetNext();
	CvdFigure GetPrevious();
	BOOL SetPosition(LPDISPATCH entity);
	CvdFigure GetItem(long Index);
	long GetCount();
	CvdFigure Add(LPCTSTR Name);
	CvdFigure FindName(LPCTSTR Name);
	BOOL AddItem(LPDISPATCH Object);
	BOOL RemoveItem(LPDISPATCH Object);
	void ChangeOrder(LPDISPATCH Object, short ToBack);
	void EraseAll();
	CvdPolyline AddPolyLine(const VARIANT& VertexArray);
	CvdLine AddLine(const VARIANT& StartPoint, const VARIANT& EndPoint);
	CvdArc AddArc(const VARIANT& CenterPoint, double Radius, double StartAngle, double EndAngle);
	CvdText AddText(LPCTSTR TextString, const VARIANT& InsertionPoint, double Height);
	CvdCircle AddCircle(const VARIANT& CenterPoint, double Radius);
	CvdInsert InsertBlock(const VARIANT& InsertionPoint, LPCTSTR Name, double Xscale, double Yscale, double Rotation);
	CvdAttrib AddAttrib(BOOL InVisibleMode, LPCTSTR TagString, LPCTSTR PromptString, LPCTSTR ValueString, const VARIANT& InsPoint, double Height);
	CvdEllipse AddEllipse(const VARIANT& CenterPoint, double MajorLength, double MinorLength);
	CvdRect AddRect(const VARIANT& InsertionPoint, double Width, double Height);
	CvdImage AddImage(LPCTSTR FileName, const VARIANT& InsertionPoint, double Scale);
	CvdDimension AddDimAligned(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition);
	CvdDimension AddDimRotated(const VARIANT& ExtLine1Point, const VARIANT& ExtLine2Point, const VARIANT& LinePosition, double RotationAngle);
	CvdPoint AddPoint(const VARIANT& Point);
	Cvd3DFace Add3DFace(const VARIANT& VertexList);
	CvdPolyface AddPolyFace(const VARIANT& VertexList, const VARIANT& FaceList);
	CvdDimension AddDimDiameter(const VARIANT& DefPoint1, const VARIANT& DefPoint2);
	CvdDimension AddDimRadial(const VARIANT& CenterPoint, const VARIANT& DefPoint2);
	CvdPolyhatch AddPolyHatch();
	CvdViewport AddViewPort(const VARIANT& CenterPoint, double Width, double Height);
	CvdDimension AddDimAngular(const VARIANT& AngleVertex, const VARIANT& FirstEndPoint, const VARIANT& SecondEndPoint, const VARIANT& LinePosition);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDENTITIES_H__FB61FBA4_F825_11D7_B650_0003B3008E71__INCLUDED_)
