#if !defined(AFX_VDLAYER_H__FB61FBB8_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDLAYER_H__FB61FBB8_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdPrimary;
class CvdXProperties;

/////////////////////////////////////////////////////////////////////////////
// CvdLayer wrapper class

class dllExport CvdLayer : public COleDispatchDriver
{
public:
	CvdLayer() {}		// Calls COleDispatchDriver default constructor
	CvdLayer(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdLayer(const CvdLayer& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetLabel();
	void SetLabel(LPCTSTR lpszNewValue);
	CString GetType();
	long GetId();
	CString GetHandle();
	void Update();
	void Erase();
	CvdPrimary Copy();
	CvdXProperties GetXProperties();
	BOOL GetDeleted();
	void SetDeleted(BOOL bNewValue);
	CString GetLayerName();
	void SetLayerName(LPCTSTR lpszNewValue);
	long GetPenColor();
	void SetPenColor(long nNewValue);
	long GetPenStyle();
	void SetPenStyle(long nNewValue);
	void SetFrozen(short nNewValue);
	short GetFrozen();
	void SetLock(short nNewValue);
	short GetLock();
	short GetLineWeight();
	void SetLineWeight(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDLAYER_H__FB61FBB8_F825_11D7_B650_0003B3008E71__INCLUDED_)
