// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdlayouts.h"

// Dispatch interfaces referenced by this interface
#include "vdLayout.h"


/////////////////////////////////////////////////////////////////////////////
// CvdLayouts properties

/////////////////////////////////////////////////////////////////////////////
// CvdLayouts operations

CvdLayout CvdLayouts::GetStart()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayout(pDispatch);
}

CvdLayout CvdLayouts::GetLast()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayout(pDispatch);
}

CvdLayout CvdLayouts::GetNext()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ed, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayout(pDispatch);
}

CvdLayout CvdLayouts::GetPrevious()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ee, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdLayout(pDispatch);
}

BOOL CvdLayouts::SetPosition(LPDISPATCH entity)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3ef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity);
	return result;
}

CvdLayout CvdLayouts::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdLayout(pDispatch);
}

long CvdLayouts::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CvdLayout CvdLayouts::Add(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdLayout(pDispatch);
}

CvdLayout CvdLayouts::FindName(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdLayout(pDispatch);
}

BOOL CvdLayouts::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdLayouts::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

void CvdLayouts::ChangeOrder(LPDISPATCH Object, short ToBack)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_I2;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Object, ToBack);
}
