#if !defined(AFX_VDLAYERS_H__FB61FBC4_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDLAYERS_H__FB61FBC4_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdLayer;

/////////////////////////////////////////////////////////////////////////////
// CvdLayers wrapper class

class dllExport CvdLayers : public COleDispatchDriver
{
public:
	CvdLayers() {}		// Calls COleDispatchDriver default constructor
	CvdLayers(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdLayers(const CvdLayers& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CvdLayer GetStart();
	CvdLayer GetLast();
	CvdLayer GetNext();
	CvdLayer GetPrevious();
	BOOL SetPosition(LPDISPATCH entity);
	CvdLayer GetItem(long Index);
	long GetCount();
	CvdLayer Add(LPCTSTR Name);
	CvdLayer FindName(LPCTSTR Name);
	BOOL AddItem(LPDISPATCH Object);
	BOOL RemoveItem(LPDISPATCH Object);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDLAYERS_H__FB61FBC4_F825_11D7_B650_0003B3008E71__INCLUDED_)
