#if !defined(AFX_VDLIGHTS_H__FB61FBCF_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDLIGHTS_H__FB61FBCF_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdLight;

/////////////////////////////////////////////////////////////////////////////
// CvdLights wrapper class

class CvdLights : public COleDispatchDriver
{
public:
	CvdLights() {}		// Calls COleDispatchDriver default constructor
	CvdLights(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdLights(const CvdLights& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CvdLight GetItem(long Index);
	long GetCount();
	CvdLight Add(LPCTSTR Name);
	CvdLight FindName(LPCTSTR Name);
	BOOL AddItem(LPDISPATCH Object);
	void ChangeOrder(LPDISPATCH Object, short ToBack);
	CvdLight GetDefault();
	BOOL RemoveItem(const VARIANT& Item);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDLIGHTS_H__FB61FBCF_F825_11D7_B650_0003B3008E71__INCLUDED_)
