#if !defined(AFX_VDLIGHT_H__FB61FBBB_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDLIGHT_H__FB61FBBB_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CvdLight wrapper class

class CvdLight : public COleDispatchDriver
{
public:
	CvdLight() {}		// Calls COleDispatchDriver default constructor
	CvdLight(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdLight(const CvdLight& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetEnableLight();
	void SetEnableLight(BOOL bNewValue);
	VARIANT GetPosition();
	void SetPosition(const VARIANT& newValue);
	VARIANT GetAmbient();
	void SetAmbient(const VARIANT& newValue);
	VARIANT GetDiffuse();
	void SetDiffuse(const VARIANT& newValue);
	VARIANT GetSpecular();
	void SetSpecular(const VARIANT& newValue);
	VARIANT GetSpotdirection();
	void SetSpotdirection(const VARIANT& newValue);
	double GetSpotexponent();
	void SetSpotexponent(double newValue);
	double GetSpotcutoff();
	void SetSpotcutoff(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDLIGHT_H__FB61FBBB_F825_11D7_B650_0003B3008E71__INCLUDED_)
