#if !defined(AFX_VDMATRIX_H__FB61FBC6_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDMATRIX_H__FB61FBC6_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class Cvdxyz;

/////////////////////////////////////////////////////////////////////////////
// Cvdmatrix wrapper class

class Cvdmatrix : public COleDispatchDriver
{
public:
	Cvdmatrix() {}		// Calls COleDispatchDriver default constructor
	Cvdmatrix(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	Cvdmatrix(const Cvdmatrix& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetItem(short Index0, short Index1);
	void SetItem(short Index0, short Index1, double newValue);
	void Init();
	void RotateX(double rotvalue);
	void RotateY(double rotvalue);
	void RotateZ(double rotvalue);
	void Translate(double dx, double dy, double dz);
	void ScaleMatrix(double xvalue, double yvalue, double zvalue);
	void Mult(LPDISPATCH mat);
	void Inverse();
	Cvdxyz GetRotations();
	void ExtrudeMatrix(double extrutionX, double extrutionY, double extrutionZ);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDMATRIX_H__FB61FBC6_F825_11D7_B650_0003B3008E71__INCLUDED_)
