#if !defined(AFX_VDPOLYLINE_H__FB61FBBE_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDPOLYLINE_H__FB61FBBE_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdPrimary;
class CvdXProperties;
class CvdLayer;

/////////////////////////////////////////////////////////////////////////////
// CvdPolyline wrapper class

class dllExport CvdPolyline : public COleDispatchDriver
{
public:
	CvdPolyline() {}		// Calls COleDispatchDriver default constructor
	CvdPolyline(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdPolyline(const CvdPolyline& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetLabel();
	void SetLabel(LPCTSTR lpszNewValue);
	CString GetType();
	long GetId();
	CString GetHandle();
	void Update();
	void Erase();
	CvdPrimary Copy();
	CvdXProperties GetXProperties();
	BOOL GetDeleted();
	void SetDeleted(BOOL bNewValue);
	CString GetLayerName();
	void SetLayerName(LPCTSTR lpszNewValue);
	long GetHighLight();
	void SetHighLight(long nNewValue);
	long GetPenColor();
	void SetPenColor(long nNewValue);
	long GetPenStyle();
	void SetPenStyle(long nNewValue);
	double GetPenWidth();
	void SetPenWidth(double newValue);
	BOOL GetVisibleOnScreen();
	BOOL GetVisible();
	void Invalidate();
	VARIANT GetBoundingBox();
	void Move(const VARIANT& FromPoint, const VARIANT& ToPoint);
	void Rotate(const VARIANT& BasePoint, double RotAngle);
	void Scale(const VARIANT& BasePoint, double ScaleFactor);
	VARIANT IntersectWith(LPDISPATCH pEntity, long intersectOption);
	void ScaleEntity(const VARIANT& BasePoint, double ScaleFactor);
	short GetShowGrips();
	void SetShowGrips(short nNewValue);
	VARIANT GetGrips();
	void DrawGrips();
	void MoveGripPointsAt(const VARIANT& Indexes, double dx, double dy, double dz);
	double GetThickness();
	void SetThickness(double newValue);
	double GetArea();
	double GetLength();
	CString GetUrl();
	void SetUrl(LPCTSTR lpszNewValue);
	CString GetToolTip();
	void SetToolTip(LPCTSTR lpszNewValue);
	CvdLayer GetLayerEntity();
	VARIANT Explode(BOOL KeepEntity);
	double GetLineTypeScale();
	void SetLineTypeScale(double newValue);
	short GetLineWeight();
	void SetLineWeight(short nNewValue);
	VARIANT GetExtrusionVector();
	void SetExtrusionVector(const VARIANT& newValue);
	void Transformby(LPDISPATCH mat);
	long GetFillBkColor();
	void SetFillBkColor(long nNewValue);
	long GetFillColor();
	void SetFillColor(long nNewValue);
	long GetFillMode();
	void SetFillMode(long nNewValue);
	VARIANT GetVertexList();
	void SetVertexList(const VARIANT& newValue);
	short GetNumVerticies();
	BOOL AppendVertex(const VARIANT& Point);
	VARIANT GetVertexAt(short VertexNumber);
	BOOL SetVertexAt(short VertexNumber, const VARIANT& CoordPoint);
	void SetBulge(long Index, double Value);
	double GetBulge(long Index);
	CString GetHatchBlock();
	void SetHatchBlock(LPCTSTR lpszNewValue);
	double GetHatchScale();
	void SetHatchScale(double newValue);
	void FilletRadius(double Radius);
	void InsertVertex(long IndexAfter, const VARIANT& vertex);
	void RemoveVertex(long Index);
	long SegmentIndexFromPoint(const VARIANT& Point, double equality);
	void FilletRadiusAtIndex(double Radius, long Index);
	long GetSPlineFlag();
	void SetSPlineFlag(long nNewValue);
	double GetHatchAngle();
	void SetHatchAngle(double newValue);
	VARIANT GetNearestPoint(const VARIANT& FromPoint);
	short GetFlag();
	void SetFlag(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDPOLYLINE_H__FB61FBBE_F825_11D7_B650_0003B3008E71__INCLUDED_)
