#if !defined(AFX_VDPRINT_H__FB61FBB2_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDPRINT_H__FB61FBB2_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CvdPrint wrapper class

class CvdPrint : public COleDispatchDriver
{
public:
	CvdPrint() {}		// Calls COleDispatchDriver default constructor
	CvdPrint(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdPrint(const CvdPrint& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetPrintScale();
	void SetPrintScale(const VARIANT& newValue);
	VARIANT GetPrintWindow();
	void SetPrintWindow(const VARIANT& newValue);
	BOOL GetOutInBlackWhite();
	void SetOutInBlackWhite(BOOL bNewValue);
	long GetPrinterDC();
	double GetPenWidth(short ColorIndex);
	void SetPenWidth(short ColorIndex, double newValue);
	void PrintExtends();
	void Preview();
	VARIANT PrintScaleToFit();
	void PrintOut();
	BOOL AttachPreview(long WindowHandle);
	CString GetDocumentName();
	void SetDocumentName(LPCTSTR lpszNewValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	short PrinterSetup();
	void PrinterDeviceDefaults(long* hDevNames, long* hDevMode, long Mode);
	VARIANT GetMargins();
	void SetMargins(const VARIANT& newValue);
	short GetPrintAsAPIWhenPossible();
	void SetPrintAsAPIWhenPossible(short nNewValue);
	void GetPrinterInfo(BSTR* DriverName, BSTR* DeviceName, BSTR* PortName, long* WidthInMM, long* HeightInMM, long* WindthInPixels, long* HeightInRasterLines);
	short GetMaxBitmapSize();
	void SetMaxBitmapSize(short nNewValue);
	CString GetPrinterName();
	void SetPrinterName(LPCTSTR lpszNewValue);
	VARIANT GetMode();
	void SetMode(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDPRINT_H__FB61FBB2_F825_11D7_B650_0003B3008E71__INCLUDED_)
