#if !defined(AFX_VDPRIMARY_H__FB61FBD1_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDPRIMARY_H__FB61FBD1_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdXProperties;

/////////////////////////////////////////////////////////////////////////////
// CvdPrimary wrapper class

class dllExport CvdPrimary : public COleDispatchDriver
{
public:
	CvdPrimary() {}		// Calls COleDispatchDriver default constructor
	CvdPrimary(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdPrimary(const CvdPrimary& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetLabel();
	void SetLabel(LPCTSTR lpszNewValue);
	CString GetType();
	long GetId();
	CString GetHandle();
	void Update();
	void Erase();
	CvdPrimary Copy();
	CvdXProperties GetXProperties();
	BOOL GetDeleted();
	void SetDeleted(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDPRIMARY_H__FB61FBD1_F825_11D7_B650_0003B3008E71__INCLUDED_)
