#if !defined(AFX_VDRAW_H__FB61FBCE_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDRAW_H__FB61FBCE_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdDocument;
class CvdCommand;
class CvdUtility;
class CPicture;
class COleFont;
class CvdRender;
class CvdActions;
class CvdPrimary;

/////////////////////////////////////////////////////////////////////////////
// CVdraw wrapper class

class CVdraw : public CWnd
{
protected:
	DECLARE_DYNCREATE(CVdraw)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x50efad92, 0x4089, 0x4653, { 0xaf, 0xa2, 0x8f, 0x3c, 0xaf, 0xcb, 0xce, 0x3a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetBkColor();
	void SetBkColor(long);
	short GetPickSize();
	void SetPickSize(short);
	short GetCrossSize();
	void SetCrossSize(short);
	short GetScrollBar();
	void SetScrollBar(short);
	BOOL GetStatusBar();
	void SetStatusBar(BOOL);
	CString GetPropFileName();
	void SetPropFileName(LPCTSTR);
	long GetHWndView();
	void SetHWndView(long);
	long GetHDCView();
	void SetHDCView(long);
	CvdDocument GetActiveDocument();
	void SetActiveDocument(LPDISPATCH);
	CvdCommand GetCommandAction();
	void SetCommandAction(LPDISPATCH);
	CvdUtility GetUtility();
	void SetUtility(LPDISPATCH);
	BOOL GetEnableProgressBar();
	void SetEnableProgressBar(BOOL);
	BOOL GetStatusBarOptionGrid();
	void SetStatusBarOptionGrid(BOOL);
	BOOL GetStatusBarOptionOrtho();
	void SetStatusBarOptionOrtho(BOOL);
	BOOL GetStatusBarOptionOsnap();
	void SetStatusBarOptionOsnap(BOOL);
	short GetMousePointer();
	void SetMousePointer(short);
	CString GetVDrawFmp();
	void SetVDrawFmp(LPCTSTR);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH);
	BOOL GetUndoMode();
	void SetUndoMode(BOOL);
	long GetReadyState();
	CString GetLicVAL();
	void SetLicVAL(LPCTSTR);
	short GetGripSize();
	void SetGripSize(short);
	long GetGripColor();
	void SetGripColor(long);
	BOOL GetStatusBarOptionSnap();
	void SetStatusBarOptionSnap(BOOL);
	CString GetDwgCodePage();
	void SetDwgCodePage(LPCTSTR);
	BOOL GetDwgCnvDosChars();
	void SetDwgCnvDosChars(BOOL);
	short GetDwgSaveVer();
	void SetDwgSaveVer(short);
	COleFont GetAltTTFFont();
	void SetAltTTFFont(LPDISPATCH);
	CString GetVdrawRes();
	void SetVdrawRes(LPCTSTR);
	long GetActionValidates();
	void SetActionValidates(long);
	short GetPenCaps();
	void SetPenCaps(short);
	long GetCurveResolution();
	void SetCurveResolution(long);
	CString GetDwgHatchMap();
	void SetDwgHatchMap(LPCTSTR);
	BOOL GetEnableToolTips();
	void SetEnableToolTips(BOOL);
	BOOL GetEnableURLs();
	void SetEnableURLs(BOOL);
	long GetOSnapColor();
	void SetOSnapColor(long);
	short GetOSnapSize();
	void SetOSnapSize(short);
	long GetVdReadyState();
	long GetWMFSaveSize();
	void SetWMFSaveSize(long);
	short GetShowWCSAxis();
	void SetShowWCSAxis(short);
	CString GetVersion();
	void SetVersion(LPCTSTR);
	CvdRender GetRender();
	void SetRender(LPDISPATCH);
	CString GetLoadingInfo();
	void SetLoadingInfo(LPCTSTR);
	VARIANT GetCursorPos();
	void SetCursorPos(const VARIANT&);
	CvdActions GetActions();
	void SetActions(LPDISPATCH);
	long GetPanWaitTime();
	void SetPanWaitTime(long);
	CvdRender GetScreenRender();
	void SetScreenRender(LPDISPATCH);

// Operations
public:
	void Redraw();
	void SizeToContent(long WindowHandle);
	void ResetScrollPosition();
	BOOL Prompt(LPCTSTR String);
	BOOL DrawEntity(LPDISPATCH entity, short UpdateBoundRect);
	VARIANT PixelToVdView(const VARIANT& PixPoint);
	VARIANT VdViewToPixel(const VARIANT& VdViewPoint);
	long VdColorIndexToRGB(short Index);
	BOOL IsValidVDObject(LPDISPATCH Object);
	BOOL RGBToVdColorIndex(short RedValue, short GreenValue, short BlueValue, short Index);
	CvdPrimary CreateNewVdFigure(LPCTSTR FigureName);
	BOOL PostCommandString(LPCTSTR String);
	BOOL DetachMaterial(short ID);
	BOOL AttachMaterial(LPCTSTR FileName, short ID);
	BOOL SetMaterialScale(short ID, double Scale);
	double GetMaterialScale(short ID);
	BOOL SetColorTrasparency(short Index, double Value);
	double GetColorTrasparency(short Index);
	void AboutBox();
	void SetProgressBarPercent(double percent);
	void DoEvents();
	void SetEventParamValue(long Position, LPCTSTR Value);
	BOOL GetInterfaceInfo(LPDISPATCH Entitiy, short CreateIfnotExist);
	void FreezeDrawEvents(short bFreeze);
	void FreezeEntityEvents(short bFreeze);
	void Scroll(double dx, double dy);
	LPDISPATCH CreateInstance(long ObjectType);
	void ReFresh();
	void SetTimer(long timerid, long milliseconds);
	void KillTimer(long timerid);
	void FreezeEvents(BOOL bFreeze);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDRAW_H__FB61FBCE_F825_11D7_B650_0003B3008E71__INCLUDED_)
