// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdraw.h"

// Dispatch interfaces referenced by this interface
#include "vddocument.h"
#include "vdcommand.h"
#include "vdutility.h"
#include "picture.h"
#include "font.h"
#include "vdrender.h"
#include "vdactions.h"
#include "vdPrimary.h"

/////////////////////////////////////////////////////////////////////////////
// CVdraw

IMPLEMENT_DYNCREATE(CVdraw, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CVdraw properties

long CVdraw::GetBkColor()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetBkColor(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

short CVdraw::GetPickSize()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetPickSize(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

short CVdraw::GetCrossSize()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetCrossSize(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

short CVdraw::GetScrollBar()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetScrollBar(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

BOOL CVdraw::GetStatusBar()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetStatusBar(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

CString CVdraw::GetPropFileName()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetPropFileName(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

long CVdraw::GetHWndView()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetHWndView(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

long CVdraw::GetHDCView()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetHDCView(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

CvdDocument CVdraw::GetActiveDocument()
{
	LPDISPATCH pDispatch;
	GetProperty(0x9, VT_DISPATCH, (void*)&pDispatch);
	return CvdDocument(pDispatch);
}

void CVdraw::SetActiveDocument(LPDISPATCH propVal)
{
	SetProperty(0x9, VT_DISPATCH, propVal);
}

CvdCommand CVdraw::GetCommandAction()
{
	LPDISPATCH pDispatch;
	GetProperty(0xa, VT_DISPATCH, (void*)&pDispatch);
	return CvdCommand(pDispatch);
}

void CVdraw::SetCommandAction(LPDISPATCH propVal)
{
	SetProperty(0xa, VT_DISPATCH, propVal);
}

CvdUtility CVdraw::GetUtility()
{
	LPDISPATCH pDispatch;
	GetProperty(0xb, VT_DISPATCH, (void*)&pDispatch);
	return CvdUtility(pDispatch);
}

void CVdraw::SetUtility(LPDISPATCH propVal)
{
	SetProperty(0xb, VT_DISPATCH, propVal);
}

BOOL CVdraw::GetEnableProgressBar()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetEnableProgressBar(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CVdraw::GetStatusBarOptionGrid()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetStatusBarOptionGrid(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

BOOL CVdraw::GetStatusBarOptionOrtho()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetStatusBarOptionOrtho(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

BOOL CVdraw::GetStatusBarOptionOsnap()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetStatusBarOptionOsnap(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

short CVdraw::GetMousePointer()
{
	short result;
	GetProperty(0x11, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetMousePointer(short propVal)
{
	SetProperty(0x11, VT_I2, propVal);
}

CString CVdraw::GetVDrawFmp()
{
	CString result;
	GetProperty(0x12, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetVDrawFmp(LPCTSTR propVal)
{
	SetProperty(0x12, VT_BSTR, propVal);
}

CPicture CVdraw::GetMouseIcon()
{
	LPDISPATCH pDispatch;
	GetProperty(0x13, VT_DISPATCH, (void*)&pDispatch);
	return CPicture(pDispatch);
}

void CVdraw::SetMouseIcon(LPDISPATCH propVal)
{
	SetProperty(0x13, VT_DISPATCH, propVal);
}

BOOL CVdraw::GetUndoMode()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetUndoMode(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

long CVdraw::GetReadyState()
{
	long result;
	GetProperty(DISPID_READYSTATE, VT_I4, (void*)&result);
	return result;
}

CString CVdraw::GetLicVAL()
{
	CString result;
	GetProperty(0x15, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetLicVAL(LPCTSTR propVal)
{
	SetProperty(0x15, VT_BSTR, propVal);
}

short CVdraw::GetGripSize()
{
	short result;
	GetProperty(0x16, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetGripSize(short propVal)
{
	SetProperty(0x16, VT_I2, propVal);
}

long CVdraw::GetGripColor()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetGripColor(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

BOOL CVdraw::GetStatusBarOptionSnap()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetStatusBarOptionSnap(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

CString CVdraw::GetDwgCodePage()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetDwgCodePage(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

BOOL CVdraw::GetDwgCnvDosChars()
{
	BOOL result;
	GetProperty(0x1a, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetDwgCnvDosChars(BOOL propVal)
{
	SetProperty(0x1a, VT_BOOL, propVal);
}

short CVdraw::GetDwgSaveVer()
{
	short result;
	GetProperty(0x1b, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetDwgSaveVer(short propVal)
{
	SetProperty(0x1b, VT_I2, propVal);
}

COleFont CVdraw::GetAltTTFFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1c, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CVdraw::SetAltTTFFont(LPDISPATCH propVal)
{
	SetProperty(0x1c, VT_DISPATCH, propVal);
}

CString CVdraw::GetVdrawRes()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetVdrawRes(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

long CVdraw::GetActionValidates()
{
	long result;
	GetProperty(0x1e, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetActionValidates(long propVal)
{
	SetProperty(0x1e, VT_I4, propVal);
}

short CVdraw::GetPenCaps()
{
	short result;
	GetProperty(0x1f, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetPenCaps(short propVal)
{
	SetProperty(0x1f, VT_I2, propVal);
}

long CVdraw::GetCurveResolution()
{
	long result;
	GetProperty(0x20, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetCurveResolution(long propVal)
{
	SetProperty(0x20, VT_I4, propVal);
}

CString CVdraw::GetDwgHatchMap()
{
	CString result;
	GetProperty(0x21, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetDwgHatchMap(LPCTSTR propVal)
{
	SetProperty(0x21, VT_BSTR, propVal);
}

BOOL CVdraw::GetEnableToolTips()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetEnableToolTips(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

BOOL CVdraw::GetEnableURLs()
{
	BOOL result;
	GetProperty(0x23, VT_BOOL, (void*)&result);
	return result;
}

void CVdraw::SetEnableURLs(BOOL propVal)
{
	SetProperty(0x23, VT_BOOL, propVal);
}

long CVdraw::GetOSnapColor()
{
	long result;
	GetProperty(0x514, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetOSnapColor(long propVal)
{
	SetProperty(0x514, VT_I4, propVal);
}

short CVdraw::GetOSnapSize()
{
	short result;
	GetProperty(0x515, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetOSnapSize(short propVal)
{
	SetProperty(0x515, VT_I2, propVal);
}

long CVdraw::GetVdReadyState()
{
	long result;
	GetProperty(0xfa4, VT_I4, (void*)&result);
	return result;
}

long CVdraw::GetWMFSaveSize()
{
	long result;
	GetProperty(0xfa5, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetWMFSaveSize(long propVal)
{
	SetProperty(0xfa5, VT_I4, propVal);
}

short CVdraw::GetShowWCSAxis()
{
	short result;
	GetProperty(0xfa6, VT_I2, (void*)&result);
	return result;
}

void CVdraw::SetShowWCSAxis(short propVal)
{
	SetProperty(0xfa6, VT_I2, propVal);
}

CString CVdraw::GetVersion()
{
	CString result;
	GetProperty(0xfa7, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetVersion(LPCTSTR propVal)
{
	SetProperty(0xfa7, VT_BSTR, propVal);
}

CvdRender CVdraw::GetRender()
{
	LPDISPATCH pDispatch;
	GetProperty(0xfb2, VT_DISPATCH, (void*)&pDispatch);
	return CvdRender(pDispatch);
}

void CVdraw::SetRender(LPDISPATCH propVal)
{
	SetProperty(0xfb2, VT_DISPATCH, propVal);
}

CString CVdraw::GetLoadingInfo()
{
	CString result;
	GetProperty(0xfc7, VT_BSTR, (void*)&result);
	return result;
}

void CVdraw::SetLoadingInfo(LPCTSTR propVal)
{
	SetProperty(0xfc7, VT_BSTR, propVal);
}

VARIANT CVdraw::GetCursorPos()
{
	VARIANT result;
	GetProperty(0x1001, VT_VARIANT, (void*)&result);
	return result;
}

void CVdraw::SetCursorPos(const VARIANT& propVal)
{
	SetProperty(0x1001, VT_VARIANT, &propVal);
}

CvdActions CVdraw::GetActions()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1002, VT_DISPATCH, (void*)&pDispatch);
	return CvdActions(pDispatch);
}

void CVdraw::SetActions(LPDISPATCH propVal)
{
	SetProperty(0x1002, VT_DISPATCH, propVal);
}

long CVdraw::GetPanWaitTime()
{
	long result;
	GetProperty(0xfe5, VT_I4, (void*)&result);
	return result;
}

void CVdraw::SetPanWaitTime(long propVal)
{
	SetProperty(0xfe5, VT_I4, propVal);
}

CvdRender CVdraw::GetScreenRender()
{
	LPDISPATCH pDispatch;
	GetProperty(0xffc, VT_DISPATCH, (void*)&pDispatch);
	return CvdRender(pDispatch);
}

void CVdraw::SetScreenRender(LPDISPATCH propVal)
{
	SetProperty(0xffc, VT_DISPATCH, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CVdraw operations

void CVdraw::Redraw()
{
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CVdraw::SizeToContent(long WindowHandle)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 WindowHandle);
}

void CVdraw::ResetScrollPosition()
{
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CVdraw::Prompt(LPCTSTR String)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		String);
	return result;
}

BOOL CVdraw::DrawEntity(LPDISPATCH entity, short UpdateBoundRect)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH VTS_I2;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity, UpdateBoundRect);
	return result;
}

VARIANT CVdraw::PixelToVdView(const VARIANT& PixPoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&PixPoint);
	return result;
}

VARIANT CVdraw::VdViewToPixel(const VARIANT& VdViewPoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&VdViewPoint);
	return result;
}

long CVdraw::VdColorIndexToRGB(short Index)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Index);
	return result;
}

BOOL CVdraw::IsValidVDObject(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CVdraw::RGBToVdColorIndex(short RedValue, short GreenValue, short BlueValue, short Index)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		RedValue, GreenValue, BlueValue, Index);
	return result;
}

CvdPrimary CVdraw::CreateNewVdFigure(LPCTSTR FigureName)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		FigureName);
	return CvdPrimary(pDispatch);
}

BOOL CVdraw::PostCommandString(LPCTSTR String)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		String);
	return result;
}

BOOL CVdraw::DetachMaterial(short ID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ID);
	return result;
}

BOOL CVdraw::AttachMaterial(LPCTSTR FileName, short ID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, ID);
	return result;
}

BOOL CVdraw::SetMaterialScale(short ID, double Scale)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_R8;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ID, Scale);
	return result;
}

double CVdraw::GetMaterialScale(short ID)
{
	double result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		ID);
	return result;
}

BOOL CVdraw::SetColorTrasparency(short Index, double Value)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_R8;
	InvokeHelper(0xe1a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Index, Value);
	return result;
}

double CVdraw::GetColorTrasparency(short Index)
{
	double result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xe1b, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		Index);
	return result;
}

void CVdraw::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CVdraw::SetProgressBarPercent(double percent)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x12c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 percent);
}

void CVdraw::DoEvents()
{
	InvokeHelper(0x140, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CVdraw::SetEventParamValue(long Position, LPCTSTR Value)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0xbb9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Position, Value);
}

BOOL CVdraw::GetInterfaceInfo(LPDISPATCH Entitiy, short CreateIfnotExist)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH VTS_I2;
	InvokeHelper(0xd4a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Entitiy, CreateIfnotExist);
	return result;
}

void CVdraw::FreezeDrawEvents(short bFreeze)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xd4b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bFreeze);
}

void CVdraw::FreezeEntityEvents(short bFreeze)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xd4c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bFreeze);
}

void CVdraw::Scroll(double dx, double dy)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8;
	InvokeHelper(0xd4d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 dx, dy);
}

LPDISPATCH CVdraw::CreateInstance(long ObjectType)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1004, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		ObjectType);
	return result;
}

void CVdraw::ReFresh()
{
	InvokeHelper(0xfed, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CVdraw::SetTimer(long timerid, long milliseconds)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xff7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 timerid, milliseconds);
}

void CVdraw::KillTimer(long timerid)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xff8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 timerid);
}

void CVdraw::FreezeEvents(BOOL bFreeze)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xff4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bFreeze);
}
