#if !defined(AFX_VDRENDER_H__FB61FBC3_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDRENDER_H__FB61FBC3_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class Cvdmatrix;

/////////////////////////////////////////////////////////////////////////////
// CvdRender wrapper class

class dllExport CvdRender : public COleDispatchDriver
{
public:
	CvdRender() {}		// Calls COleDispatchDriver default constructor
	CvdRender(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdRender(const CvdRender& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void ViewToPixel(double x1, double y1, long* xx, long* yy);
	void PixelToView(long x, long y, double* xx, double* yy);
	long GetHdc();
	double GetPixelSize();
	long GetLeft();
	long GetTop();
	long GetWidth();
	long GetHeight();
	void Select_Pen(long PenStyle, long color, double PenWidth);
	void Moveto(double x, double y, double z);
	void Lineto(double x, double y, double z);
	long Setrop(long newRop);
	void Drawline(double x1, double y1, double z1, double x2, double y2, double z2, double Thickness);
	void Drawpolyline(LPDISPATCH pointlist, double Thickness);
	void Drawtext(LPCTSTR TextString, double x1, double y1, double z1, LPDISPATCH Style, double Height, double Rotation, long horjust, long verjust);
	BOOL GetTextSize(LPCTSTR TextString, LPDISPATCH tstyle, double Height, double* duWidth, double* duHeight);
	void Drawarc(double cenx, double ceny, double cenz, double Radius, double sangle, double eangle);
	void Drawcircle(double cenx, double ceny, double cenz, double Radius);
	long GetPrinterMode();
	long GetDrawMode();
	void SetDrawMode(long nNewValue);
	void ClearBkColor(long color);
	void GetWindowExt(long* Left, long* Top, long* Right, long* Bottom);
	void PushMatrix();
	void PopMatrix();
	void SelectWorldMatrix();
	void WorldToView(double* x1, double* y1, double* z1);
	void ViewToWorld(double* x1, double* y1, double* z1);
	void GetViewCenter(double* x1, double* y1, double* z1);
	long GetCurveResolution();
	void SetCurveResolution(long nNewValue);
	void BeginFillRegion(long FillColor, long FillMode);
	void CombineFillRegion(long Mode);
	void FillRegion(const VARIANT& props);
	void ClearFillRegion();
	Cvdmatrix GetMatrix();
	void SetMatrix(LPDISPATCH newValue);
	void DrawImage(LPDISPATCH Picture, LPDISPATCH lowerLeft, double destHeight, short Flag);
	void DrawEntity(LPDISPATCH entity);
	void LockPen(long PenColor, long FillColor, long FillBkColor, long PenStyle, double PenWidth);
	void UnLockPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDRENDER_H__FB61FBC3_F825_11D7_B650_0003B3008E71__INCLUDED_)
