// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdrender.h"

// Dispatch interfaces referenced by this interface
#include "vdmatrix.h"


/////////////////////////////////////////////////////////////////////////////
// CvdRender properties

/////////////////////////////////////////////////////////////////////////////
// CvdRender operations

void CvdRender::ViewToPixel(double x1, double y1, long* xx, long* yy)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_PI4 VTS_PI4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x1, y1, xx, yy);
}

void CvdRender::PixelToView(long x, long y, double* xx, double* yy)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_PR8 VTS_PR8;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x, y, xx, yy);
}

long CvdRender::GetHdc()
{
	long result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

double CvdRender::GetPixelSize()
{
	double result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

long CvdRender::GetLeft()
{
	long result;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CvdRender::GetTop()
{
	long result;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CvdRender::GetWidth()
{
	long result;
	InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CvdRender::GetHeight()
{
	long result;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdRender::Select_Pen(long PenStyle, long color, double PenWidth)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_R8;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PenStyle, color, PenWidth);
}

void CvdRender::Moveto(double x, double y, double z)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x, y, z);
}

void CvdRender::Lineto(double x, double y, double z)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x, y, z);
}

long CvdRender::Setrop(long newRop)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		newRop);
	return result;
}

void CvdRender::Drawline(double x1, double y1, double z1, double x2, double y2, double z2, double Thickness)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x1, y1, z1, x2, y2, z2, Thickness);
}

void CvdRender::Drawpolyline(LPDISPATCH pointlist, double Thickness)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_R8;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pointlist, Thickness);
}

void CvdRender::Drawtext(LPCTSTR TextString, double x1, double y1, double z1, LPDISPATCH Style, double Height, double Rotation, long horjust, long verjust)
{
	static BYTE parms[] =
		VTS_BSTR VTS_R8 VTS_R8 VTS_R8 VTS_DISPATCH VTS_R8 VTS_R8 VTS_I4 VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 TextString, x1, y1, z1, Style, Height, Rotation, horjust, verjust);
}

BOOL CvdRender::GetTextSize(LPCTSTR TextString, LPDISPATCH tstyle, double Height, double* duWidth, double* duHeight)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_DISPATCH VTS_R8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		TextString, tstyle, Height, duWidth, duHeight);
	return result;
}

void CvdRender::Drawarc(double cenx, double ceny, double cenz, double Radius, double sangle, double eangle)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cenx, ceny, cenz, Radius, sangle, eangle);
}

void CvdRender::Drawcircle(double cenx, double ceny, double cenz, double Radius)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cenx, ceny, cenz, Radius);
}

long CvdRender::GetPrinterMode()
{
	long result;
	InvokeHelper(0x12, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CvdRender::GetDrawMode()
{
	long result;
	InvokeHelper(0x13, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdRender::SetDrawMode(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x13, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CvdRender::ClearBkColor(long color)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 color);
}

void CvdRender::GetWindowExt(long* Left, long* Top, long* Right, long* Bottom)
{
	static BYTE parms[] =
		VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Left, Top, Right, Bottom);
}

void CvdRender::PushMatrix()
{
	InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdRender::PopMatrix()
{
	InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdRender::SelectWorldMatrix()
{
	InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdRender::WorldToView(double* x1, double* y1, double* z1)
{
	static BYTE parms[] =
		VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x1, y1, z1);
}

void CvdRender::ViewToWorld(double* x1, double* y1, double* z1)
{
	static BYTE parms[] =
		VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x1, y1, z1);
}

void CvdRender::GetViewCenter(double* x1, double* y1, double* z1)
{
	static BYTE parms[] =
		VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x1, y1, z1);
}

long CvdRender::GetCurveResolution()
{
	long result;
	InvokeHelper(0x1c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdRender::SetCurveResolution(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void CvdRender::BeginFillRegion(long FillColor, long FillMode)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FillColor, FillMode);
}

void CvdRender::CombineFillRegion(long Mode)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Mode);
}

void CvdRender::FillRegion(const VARIANT& props)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &props);
}

void CvdRender::ClearFillRegion()
{
	InvokeHelper(0x20, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

Cvdmatrix CvdRender::GetMatrix()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x21, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return Cvdmatrix(pDispatch);
}

void CvdRender::SetMatrix(LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x21, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

void CvdRender::DrawImage(LPDISPATCH Picture, LPDISPATCH lowerLeft, double destHeight, short Flag)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_DISPATCH VTS_R8 VTS_I2;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Picture, lowerLeft, destHeight, Flag);
}

void CvdRender::DrawEntity(LPDISPATCH entity)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 entity);
}

void CvdRender::LockPen(long PenColor, long FillColor, long FillBkColor, long PenStyle, double PenWidth)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_R8;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PenColor, FillColor, FillBkColor, PenStyle, PenWidth);
}

void CvdRender::UnLockPen()
{
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
