// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdselection.h"

// Dispatch interfaces referenced by this interface
#include "vdFigure.h"


/////////////////////////////////////////////////////////////////////////////
// CvdSelection properties

/////////////////////////////////////////////////////////////////////////////
// CvdSelection operations

CvdFigure CvdSelection::GetStart()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdSelection::GetLast()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdSelection::GetNext()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ed, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

CvdFigure CvdSelection::GetPrevious()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ee, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdFigure(pDispatch);
}

BOOL CvdSelection::SetPosition(LPDISPATCH entity)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3ef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity);
	return result;
}

CvdFigure CvdSelection::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdFigure(pDispatch);
}

long CvdSelection::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CvdFigure CvdSelection::Add(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdFigure(pDispatch);
}

CvdFigure CvdSelection::FindName(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdFigure(pDispatch);
}

BOOL CvdSelection::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdSelection::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

CString CvdSelection::GetName()
{
	CString result;
	InvokeHelper(0x64, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CvdSelection::SetName(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x64, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

void CvdSelection::RemoveAll()
{
	InvokeHelper(0x65, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdSelection::Free()
{
	InvokeHelper(0x66, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdSelection::Update()
{
	InvokeHelper(0x67, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdSelection::SetHighLight(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CvdSelection::GetHighLight()
{
	long result;
	InvokeHelper(0x68, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CvdSelection::ClearAll()
{
	InvokeHelper(0x69, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CvdSelection::Select(const VARIANT& Mode, const VARIANT& FirstCorner, const VARIANT& OtherCorner)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Mode, &FirstCorner, &OtherCorner);
}

VARIANT CvdSelection::GetBoundExtends()
{
	VARIANT result;
	InvokeHelper(0x6b, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CvdFigure CvdSelection::SelectAtPoint(const VARIANT& Point)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6c, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Point);
	return CvdFigure(pDispatch);
}

void CvdSelection::Invalidate()
{
	InvokeHelper(0x6d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CvdSelection::StartSelectAtWindow(const VARIANT& RefPoint, BOOL RemoveMode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_BOOL;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&RefPoint, RemoveMode);
	return result;
}

void CvdSelection::Transformby(LPDISPATCH mat)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0xfe7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 mat);
}

void CvdSelection::ShowGrips(short nvalue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xffb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nvalue);
}

LPDISPATCH CvdSelection::RenderToBitmap(long ImageWidth, long ImageHeight)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x3f2, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		ImageWidth, ImageHeight);
	return result;
}
