// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdselections.h"

// Dispatch interfaces referenced by this interface
#include "vdSelection.h"
#include "vdFilterObject.h"


/////////////////////////////////////////////////////////////////////////////
// CvdSelections properties

/////////////////////////////////////////////////////////////////////////////
// CvdSelections operations

CvdSelection CvdSelections::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdSelection(pDispatch);
}

long CvdSelections::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CvdSelection CvdSelections::Add(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdSelection(pDispatch);
}

CvdSelection CvdSelections::FindName(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdSelection(pDispatch);
}

BOOL CvdSelections::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdSelections::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

void CvdSelections::FreeAll()
{
	InvokeHelper(0x64, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CvdSelection CvdSelections::FilterSelect(LPCTSTR Name, LPDISPATCH filter)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR VTS_DISPATCH;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name, filter);
	return CvdSelection(pDispatch);
}

CvdFilterObject CvdSelections::CreateFilter(const VARIANT& Types, const VARIANT& Layers)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xfe3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Types, &Layers);
	return CvdFilterObject(pDispatch);
}
