#if !defined(AFX_VDSECTIONCLIP_H__FB61FBCA_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDSECTIONCLIP_H__FB61FBCA_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class Cvdxyz;

/////////////////////////////////////////////////////////////////////////////
// CvdSectionClip wrapper class

class CvdSectionClip : public COleDispatchDriver
{
public:
	CvdSectionClip() {}		// Calls COleDispatchDriver default constructor
	CvdSectionClip(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdSectionClip(const CvdSectionClip& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	Cvdxyz GetOriginPoint();
	void SetOriginPoint(LPDISPATCH newValue);
	Cvdxyz GetDirection();
	void SetDirection(LPDISPATCH newValue);
	BOOL GetEnable();
	void SetEnable(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDSECTIONCLIP_H__FB61FBCA_F825_11D7_B650_0003B3008E71__INCLUDED_)
