#if !defined(AFX_VDTEXTSTYLE_H__FB61FBAF_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDTEXTSTYLE_H__FB61FBAF_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdPrimary;
class CvdXProperties;

/////////////////////////////////////////////////////////////////////////////
// CvdTextstyle wrapper class

class CvdTextstyle : public COleDispatchDriver
{
public:
	CvdTextstyle() {}		// Calls COleDispatchDriver default constructor
	CvdTextstyle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdTextstyle(const CvdTextstyle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetLabel();
	void SetLabel(LPCTSTR lpszNewValue);
	CString GetType();
	long GetId();
	CString GetHandle();
	void Update();
	void Erase();
	CvdPrimary Copy();
	CvdXProperties GetXProperties();
	BOOL GetDeleted();
	void SetDeleted(BOOL bNewValue);
	CString GetFontFile();
	void SetFontFile(LPCTSTR lpszNewValue);
	CString GetStyleName();
	void SetStyleName(LPCTSTR lpszNewValue);
	double GetHeight();
	void SetHeight(double newValue);
	double GetWidth();
	void SetWidth(double newValue);
	short GetExtra();
	void SetExtra(short nNewValue);
	CString GetBigFontFile();
	void SetBigFontFile(LPCTSTR lpszNewValue);
	short GetFlag();
	void SetFlag(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDTEXTSTYLE_H__FB61FBAF_F825_11D7_B650_0003B3008E71__INCLUDED_)
