#if !defined(AFX_VDUTILITY_H__FB61FBA9_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDUTILITY_H__FB61FBA9_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdFigure;
class Cvdxyzlist;

/////////////////////////////////////////////////////////////////////////////
// CvdUtility wrapper class

class dllExport CvdUtility : public COleDispatchDriver
{
public:
	CvdUtility() {}		// Calls COleDispatchDriver default constructor
	CvdUtility(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdUtility(const CvdUtility& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetCoordMode();
	void SetCoordMode(short nNewValue);
	VARIANT GetLine(const VARIANT& referencePoint);
	VARIANT GetPoint();
	VARIANT GetCorner(const VARIANT& referencePoint);
	VARIANT GetAngle(const VARIANT& referencePoint);
	VARIANT GetDist(const VARIANT& referencePoint);
	VARIANT GetArcEndAngle(const VARIANT& Center, const VARIANT& Radius, const VARIANT& StartAngle);
	CvdFigure GetEntity(VARIANT* PickPoint);
	LPDISPATCH GetFilePicture(LPCTSTR FileName);
	short GetColorDlg(short EnableExtraButtons, short colorNo, LPCTSTR ButtonCaption);
	VARIANT GetOpenFileName(short DefExt, LPCTSTR FileName, short MultiSelect);
	void WorldToCCS(VARIANT* PointOrObject);
	void CCSToWorld(VARIANT* PointOrObject);
	BOOL GetString(BSTR* String);
	BOOL GetInt(long* IntValue);
	BOOL GetReal(double* RealValue);
	VARIANT geomInters(short Option, const VARIANT& p1, const VARIANT& p2, const VARIANT& p3, const VARIANT& p4);
	VARIANT geomPolar(const VARIANT& p1, double Angle, double distance);
	double geomDistance(const VARIANT& p1, const VARIANT& p2);
	double geomAngle(const VARIANT& p1, const VARIANT& p2);
	VARIANT geomDivide(LPDISPATCH entity, long NumSegments);
	VARIANT geomMeasure(LPDISPATCH entity, double Length);
	double geomAreaFromPoints(const VARIANT& PointArray);
	BOOL PointOnLine(const VARIANT& Point, const VARIANT& LineP1, const VARIANT& LineP2);
	Cvdxyzlist OffsetPoints(LPDISPATCH PointsArray, const VARIANT& SideToOffset, double OffsetDistance);
	BOOL getOsnapPoint(const VARIANT& checkPoint, const VARIANT& referencePoint, short osnap, VARIANT* retPoint);
	BOOL Fillet2ObjectsRadius(double Radius, LPDISPATCH Entity1, const VARIANT& Entity1_Point, LPDISPATCH Entity2, const VARIANT& Entity2_Point, LPDISPATCH* newArcObject);
	BOOL ExportPictureToFile(LPDISPATCH Picture, LPCTSTR FileName);
	VARIANT GetArcEndAngle2(const VARIANT& Center, const VARIANT& Radius, const VARIANT& StartAngle);
	VARIANT GetCircleRad(const VARIANT& referencePoint);
	void grDraw(const VARIANT& from, const VARIANT& to, short isInPixels, long color, double PenWidth);
	VARIANT GetExtrusionVector(const VARIANT& p1, const VARIANT& p2, const VARIANT& p3);
	BOOL ModifyLineType(long LineTypeId, LPCTSTR Description, long NumOfDashElements, const VARIANT& DashedElements);
	BOOL GetLineTypeProperties(long LineTypeId, BSTR* Description, long* NumOfDashElements, VARIANT* DashedElements);
	short GetLineWeightDlg(short defaultValue);
	void GetFonts(VARIANT* TTFList, VARIANT* SHXList, VARIANT* BigFontList);
	CString FindFile(LPCTSTR FileName);
	CString LReal2StringUnits(double Value, long unit, long precision);
	double LStringUnits2Real(LPCTSTR stringvalue, long unit, long precision);
	CString AReal2StringUnits(double Value, long unit, long precision, double base, long Direction);
	double AStringUnits2Real(LPCTSTR stringvalue, long unit, long precision, double base, long Direction);
	void grDrawArc(const VARIANT& cen, double Radius, double StartAngle, double EndAngle, short isInPixels, long color, double PenWidth);
	VARIANT NormalizeVector(const VARIANT& vector);
	VARIANT geomMidPoint(const VARIANT& Point1, const VARIANT& Point2);
	BOOL geom3PointCenter(const VARIANT& Point1, const VARIANT& Point2, const VARIANT& Point3, VARIANT* PCenter);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDUTILITY_H__FB61FBA9_F825_11D7_B650_0003B3008E71__INCLUDED_)
