// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdutility.h"

// Dispatch interfaces referenced by this interface
#include "vdFigure.h"
#include "vdxyzlist.h"


/////////////////////////////////////////////////////////////////////////////
// CvdUtility properties

/////////////////////////////////////////////////////////////////////////////
// CvdUtility operations

short CvdUtility::GetCoordMode()
{
	short result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CvdUtility::SetCoordMode(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

VARIANT CvdUtility::GetLine(const VARIANT& referencePoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&referencePoint);
	return result;
}

VARIANT CvdUtility::GetPoint()
{
	VARIANT result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CvdUtility::GetCorner(const VARIANT& referencePoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&referencePoint);
	return result;
}

VARIANT CvdUtility::GetAngle(const VARIANT& referencePoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&referencePoint);
	return result;
}

VARIANT CvdUtility::GetDist(const VARIANT& referencePoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&referencePoint);
	return result;
}

VARIANT CvdUtility::GetArcEndAngle(const VARIANT& Center, const VARIANT& Radius, const VARIANT& StartAngle)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&Center, &Radius, &StartAngle);
	return result;
}

CvdFigure CvdUtility::GetEntity(VARIANT* PickPoint)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		PickPoint);
	return CvdFigure(pDispatch);
}

LPDISPATCH CvdUtility::GetFilePicture(LPCTSTR FileName)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		FileName);
	return result;
}

short CvdUtility::GetColorDlg(short EnableExtraButtons, short colorNo, LPCTSTR ButtonCaption)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		EnableExtraButtons, colorNo, ButtonCaption);
	return result;
}

VARIANT CvdUtility::GetOpenFileName(short DefExt, LPCTSTR FileName, short MultiSelect)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR VTS_I2;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		DefExt, FileName, MultiSelect);
	return result;
}

void CvdUtility::WorldToCCS(VARIANT* PointOrObject)
{
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PointOrObject);
}

void CvdUtility::CCSToWorld(VARIANT* PointOrObject)
{
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PointOrObject);
}

BOOL CvdUtility::GetString(BSTR* String)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		String);
	return result;
}

BOOL CvdUtility::GetInt(long* IntValue)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		IntValue);
	return result;
}

BOOL CvdUtility::GetReal(double* RealValue)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PR8;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		RealValue);
	return result;
}

VARIANT CvdUtility::geomInters(short Option, const VARIANT& p1, const VARIANT& p2, const VARIANT& p3, const VARIANT& p4)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		Option, &p1, &p2, &p3, &p4);
	return result;
}

VARIANT CvdUtility::geomPolar(const VARIANT& p1, double Angle, double distance)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&p1, Angle, distance);
	return result;
}

double CvdUtility::geomDistance(const VARIANT& p1, const VARIANT& p2)
{
	double result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		&p1, &p2);
	return result;
}

double CvdUtility::geomAngle(const VARIANT& p1, const VARIANT& p2)
{
	double result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		&p1, &p2);
	return result;
}

VARIANT CvdUtility::geomDivide(LPDISPATCH entity, long NumSegments)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_DISPATCH VTS_I4;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		entity, NumSegments);
	return result;
}

VARIANT CvdUtility::geomMeasure(LPDISPATCH entity, double Length)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_DISPATCH VTS_R8;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		entity, Length);
	return result;
}

double CvdUtility::geomAreaFromPoints(const VARIANT& PointArray)
{
	double result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		&PointArray);
	return result;
}

BOOL CvdUtility::PointOnLine(const VARIANT& Point, const VARIANT& LineP1, const VARIANT& LineP2)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Point, &LineP1, &LineP2);
	return result;
}

Cvdxyzlist CvdUtility::OffsetPoints(LPDISPATCH PointsArray, const VARIANT& SideToOffset, double OffsetDistance)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_DISPATCH VTS_VARIANT VTS_R8;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		PointsArray, &SideToOffset, OffsetDistance);
	return Cvdxyzlist(pDispatch);
}

BOOL CvdUtility::getOsnapPoint(const VARIANT& checkPoint, const VARIANT& referencePoint, short osnap, VARIANT* retPoint)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_I2 VTS_PVARIANT;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&checkPoint, &referencePoint, osnap, retPoint);
	return result;
}

BOOL CvdUtility::Fillet2ObjectsRadius(double Radius, LPDISPATCH Entity1, const VARIANT& Entity1_Point, LPDISPATCH Entity2, const VARIANT& Entity2_Point, LPDISPATCH* newArcObject)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R8 VTS_DISPATCH VTS_VARIANT VTS_DISPATCH VTS_VARIANT VTS_PDISPATCH;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Radius, Entity1, &Entity1_Point, Entity2, &Entity2_Point, newArcObject);
	return result;
}

BOOL CvdUtility::ExportPictureToFile(LPDISPATCH Picture, LPCTSTR FileName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Picture, FileName);
	return result;
}

VARIANT CvdUtility::GetArcEndAngle2(const VARIANT& Center, const VARIANT& Radius, const VARIANT& StartAngle)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&Center, &Radius, &StartAngle);
	return result;
}

VARIANT CvdUtility::GetCircleRad(const VARIANT& referencePoint)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&referencePoint);
	return result;
}

void CvdUtility::grDraw(const VARIANT& from, const VARIANT& to, short isInPixels, long color, double PenWidth)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_I2 VTS_I4 VTS_R8;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &from, &to, isInPixels, color, PenWidth);
}

VARIANT CvdUtility::GetExtrusionVector(const VARIANT& p1, const VARIANT& p2, const VARIANT& p3)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&p1, &p2, &p3);
	return result;
}

BOOL CvdUtility::ModifyLineType(long LineTypeId, LPCTSTR Description, long NumOfDashElements, const VARIANT& DashedElements)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4 VTS_VARIANT;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		LineTypeId, Description, NumOfDashElements, &DashedElements);
	return result;
}

BOOL CvdUtility::GetLineTypeProperties(long LineTypeId, BSTR* Description, long* NumOfDashElements, VARIANT* DashedElements)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_PBSTR VTS_PI4 VTS_PVARIANT;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		LineTypeId, Description, NumOfDashElements, DashedElements);
	return result;
}

short CvdUtility::GetLineWeightDlg(short defaultValue)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		defaultValue);
	return result;
}

void CvdUtility::GetFonts(VARIANT* TTFList, VARIANT* SHXList, VARIANT* BigFontList)
{
	static BYTE parms[] =
		VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 TTFList, SHXList, BigFontList);
}

CString CvdUtility::FindFile(LPCTSTR FileName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		FileName);
	return result;
}

CString CvdUtility::LReal2StringUnits(double Value, long unit, long precision)
{
	CString result;
	static BYTE parms[] =
		VTS_R8 VTS_I4 VTS_I4;
	InvokeHelper(0xed3, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Value, unit, precision);
	return result;
}

double CvdUtility::LStringUnits2Real(LPCTSTR stringvalue, long unit, long precision)
{
	double result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0xed4, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		stringvalue, unit, precision);
	return result;
}

CString CvdUtility::AReal2StringUnits(double Value, long unit, long precision, double base, long Direction)
{
	CString result;
	static BYTE parms[] =
		VTS_R8 VTS_I4 VTS_I4 VTS_R8 VTS_I4;
	InvokeHelper(0xed5, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Value, unit, precision, base, Direction);
	return result;
}

double CvdUtility::AStringUnits2Real(LPCTSTR stringvalue, long unit, long precision, double base, long Direction)
{
	double result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_R8 VTS_I4;
	InvokeHelper(0xed6, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		stringvalue, unit, precision, base, Direction);
	return result;
}

void CvdUtility::grDrawArc(const VARIANT& cen, double Radius, double StartAngle, double EndAngle, short isInPixels, long color, double PenWidth)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_R8 VTS_R8 VTS_R8 VTS_I2 VTS_I4 VTS_R8;
	InvokeHelper(0xfab, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &cen, Radius, StartAngle, EndAngle, isInPixels, color, PenWidth);
}

VARIANT CvdUtility::NormalizeVector(const VARIANT& vector)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xfb1, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&vector);
	return result;
}

VARIANT CvdUtility::geomMidPoint(const VARIANT& Point1, const VARIANT& Point2)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xfc5, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&Point1, &Point2);
	return result;
}

BOOL CvdUtility::geom3PointCenter(const VARIANT& Point1, const VARIANT& Point2, const VARIANT& Point3, VARIANT* PCenter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_PVARIANT;
	InvokeHelper(0xfc6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		&Point1, &Point2, &Point3, PCenter);
	return result;
}
