// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vdxproperties.h"

// Dispatch interfaces referenced by this interface
#include "vdxproperty.h"


/////////////////////////////////////////////////////////////////////////////
// CvdXProperties properties

/////////////////////////////////////////////////////////////////////////////
// CvdXProperties operations

CvdXProperty CvdXProperties::GetStart()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdXProperty(pDispatch);
}

CvdXProperty CvdXProperties::GetLast()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdXProperty(pDispatch);
}

CvdXProperty CvdXProperties::GetNext()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ed, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdXProperty(pDispatch);
}

CvdXProperty CvdXProperties::GetPrevious()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3ee, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CvdXProperty(pDispatch);
}

BOOL CvdXProperties::SetPosition(LPDISPATCH entity)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3ef, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		entity);
	return result;
}

CvdXProperty CvdXProperties::GetItem(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CvdXProperty(pDispatch);
}

long CvdXProperties::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CvdXProperties::AddItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

BOOL CvdXProperties::RemoveItem(LPDISPATCH Object)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Object);
	return result;
}

void CvdXProperties::EraseAll()
{
	InvokeHelper(0x64, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CvdXProperty CvdXProperties::AddXProperty(LPCTSTR Name, long Type, const VARIANT& Value)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_VARIANT;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name, Type, &Value);
	return CvdXProperty(pDispatch);
}

CvdXProperties CvdXProperties::GetFilterData(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdXProperties(pDispatch);
}

CvdXProperty CvdXProperties::FindName(LPCTSTR Name)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x67, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Name);
	return CvdXProperty(pDispatch);
}
