#if !defined(AFX_VDXPROPERTY_H__FB61FBA8_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDXPROPERTY_H__FB61FBA8_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CvdXProperty wrapper class

class dllExport CvdXProperty : public COleDispatchDriver
{
public:
	CvdXProperty() {}		// Calls COleDispatchDriver default constructor
	CvdXProperty(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdXProperty(const CvdXProperty& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	VARIANT GetValue();
	void SetValue(const VARIANT& newValue);
	long GetType();
	void SetType(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDXPROPERTY_H__FB61FBA8_F825_11D7_B650_0003B3008E71__INCLUDED_)
