#if !defined(AFX_VDXPROPERTIES_H__FB61FBB1_F825_11D7_B650_0003B3008E71__INCLUDED_)
#define AFX_VDXPROPERTIES_H__FB61FBB1_F825_11D7_B650_0003B3008E71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CvdXProperty;

/////////////////////////////////////////////////////////////////////////////
// CvdXProperties wrapper class

class dllExport CvdXProperties : public COleDispatchDriver
{
public:
	CvdXProperties() {}		// Calls COleDispatchDriver default constructor
	CvdXProperties(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CvdXProperties(const CvdXProperties& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CvdXProperty GetStart();
	CvdXProperty GetLast();
	CvdXProperty GetNext();
	CvdXProperty GetPrevious();
	BOOL SetPosition(LPDISPATCH entity);
	CvdXProperty GetItem(long Index);
	long GetCount();
	BOOL AddItem(LPDISPATCH Object);
	BOOL RemoveItem(LPDISPATCH Object);
	void EraseAll();
	CvdXProperty AddXProperty(LPCTSTR Name, long Type, const VARIANT& Value);
	CvdXProperties GetFilterData(LPCTSTR Name);
	CvdXProperty FindName(LPCTSTR Name);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VDXPROPERTIES_H__FB61FBB1_F825_11D7_B650_0003B3008E71__INCLUDED_)
