
#include "stdafx.h"
#include "MathConst.h"
#include "cmn_resource.h"
#include "Register.h"
#include "StrgList.h"
#include "DbAllEntities.h"
#include "DbIterator.h"
#include "Model.h"
#include "ModelText.h"

#define MAXLEN 80


////////////////////////////////////////////////////////////////////////

CModelText::CModelText()
	: m_enabled(false)
{
	CString	path = CRegister::StringGetV( "Debug", "$RESULT", "" );

	m_is_rtl_running = (path.GetLength() > 0);
}

CModelText::~CModelText()
{
}


CReturn
CModelText::Dump( const CString& filepath, const CModel& model )
{
	CReturn status;

	if (m_enabled == true)
	{
		CDbIterator iter;
		FILE* f = NULL;

		if (filepath.GetLength() > 0)
			f = fopen( filepath, "w" );

		if (f == NULL)
		{
			status.User( IDS_INTERNAL_ERROR, "CModelText::Dump()" );
			return status;
		}

		Summarize( model, f );

		VarListDump( f, model.Header(), "Header:" );

		VarListDump( f, model.Default(), "Defaults:" );

		iter.Init( model.Db(), DBWORKPLANE );
		while (1)
		{
			const CDbEntity* dbEntity = iter();
			if (dbEntity == NULL)
				break;

			EntityDump( (*dbEntity), f );

			iter.Next();
		}

		fclose( f );
	}

	return status;
}

void
CModelText::Summarize( const CModel& model, FILE* f )
{
	EDbEntityType	type;
	int				count, total, indx;

	total = 0;

	fprintf( f, "------------------------------\n" );
	fprintf( f, "Summary\n" );
	fprintf( f, "------------------------------\n" );

	fprintf( f, "header:   %d\n", model.Header().countVar() );

	for (indx = DBLAYER; indx < DBTERMINAL; ++indx)
	{
		type = (EDbEntityType) indx;

		count = model.Db().Count( type );
		fprintf( f, "%s%d\n", Label( type ), count );

		total += count;
	}

	fprintf( f, "------------------------------\n" );
	fprintf( f, "total:    %d\n", total );
	fprintf( f, "------------------------------\n" );
	fprintf( f, "\n" );
}

void
CModelText::EntityDump( const CDbEntity& dbEntity, FILE* f )
{
	CDbWorkplane*	dbWork = dbEntity.Workplane();
	CDbTool*		dbTool = dbEntity.Tool();
	CDbSequence*	dbSeq = dbEntity.Sequence();
	CDbEntity*		dbOwn = dbEntity.Owner();
	CString			desc = EntityDescription( dbEntity );

	// Put the target name for this entity.
	if (dbEntity.Name().GetLength() > 0)
	{
		fprintf( f, "%s, name=\"%s\", refcnt=%d, flags=0x%04x",
				 desc, dbEntity.Name(), dbEntity.RefCnt(), dbEntity.Flags() );
	}
	else
	{
		fprintf( f, "%s, refcnt=%d, flags=0x%04x",
				desc, dbEntity.RefCnt(), dbEntity.Flags() );
	}

	// Put the links to the details.

	fprintf( f, ", tool=%d",	((dbTool == NULL)  ? 0 : dbTool->Id()) );
	fprintf( f, ", work=%d",	((dbWork == NULL)  ? 0 : dbWork->Id()) );
	fprintf( f, ", owner=%d",	((dbOwn == NULL)   ? 0 : dbOwn->Id()) );
	fprintf( f, ", seq=%d\n",	((dbSeq == NULL)   ? 0 : dbSeq->Id()) );

	AttributesDump( dbEntity, f );
	ReferencesDump( dbEntity, f );
	OwnsDump( dbEntity, f );
	CanonicalDump( dbEntity, f );

	fprintf( f, "\n" );
}

void
CModelText::VarListDump( 
	FILE*	f,
	const CVarList& varlist,
	const CString& title )
{
	CString	tmp;
	CString	name;
	CVar*	var;
	int		count, indx;
	int		tlen, slen;

	fprintf( f, "%s\n", title );

	count = varlist.countVar();
	if (count > 0)
	{
		fprintf( f, "\t" );

		tlen = 0;
		for (indx = 0; indx < count; ++indx)
		{
			var = varlist.getVar(indx);
			name = var->getName();

			if ( CanPrint( name ) )
			{
				tmp.Format( "%s = %s,", name, var->getString() );

				slen = tmp.GetLength();
				tlen += slen;

				if (tlen > MAXLEN)
				{
					fprintf( f, "\n\t" );
					tlen = slen;
				}

				fprintf( f, "%s", tmp );
			}
		}
		fprintf( f, "\n" );
	}
}

// As the file generated by this class is intended to by used for
// RTL analysis, all of an entity's attributes are written to a
// single output line, ensuring that diff doesn't go berserk.
void
CModelText::AttributesDump( const CDbEntity& dbEntity, FILE* f )
{
	const CVar* var;
	CString	tmp;
	CString name;
	CString value;
	char	type;
	int		count, indx;
	int		tlen, slen;

	const CVarList& attribs = dbEntity.Attrib();

	count = attribs.countVar();
	if (count > 0)
	{
		fprintf( f, "\t------------------- attribs -------------------\n" );

		tlen = 0;
		for (indx = 0; indx < count; ++indx)
		{
			var = attribs.getVar( indx );
			name = var->getName();
			value = var->getString();

			switch (var->getType())
			{
			case VAR_INT: type = 'i'; break;
			case VAR_REAL: type = 'r'; break;
			case VAR_STRING: type = 's'; break;
			default: type = 'u'; break;
			}

			if (indx == 0)
				fprintf( f, "\t" );

			tmp.Format( "(%c)%s=\"%s\",", type, name, value );

			slen = tmp.GetLength();
			tlen += slen;

			if (tlen > MAXLEN)
			{
				fprintf( f, "\n\t" );
				tlen = slen;
			}

			fprintf( f, "%s", tmp );
		}

		fprintf( f, "\n" );
	}
}

void
CModelText::ReferencesDump( const CDbEntity& dbEntity, FILE* f )
{
	if ( CanReference( dbEntity ) )
	{
		CDbEntityList refs;
		CString	name;
		int	count, indx;
		int	slen, tlen;

		dbEntity.RefsTo( &refs );

		count = refs.Count();
		if (count > 0)
		{
			fprintf( f, "\t------------------- references -------------------\n" );
			fprintf( f, "\t" );

			tlen = 0;
			for (indx = 0; indx < count; ++indx)
			{
				name = refs[indx]->Name();

				slen = (name.GetLength() + 1);  // ie. plus the comma
				tlen += slen;

				if (tlen > MAXLEN)
				{
					fprintf( f, "\n\t" );
					tlen = slen;
				}

				fprintf( f, "%s,", name );
			}

			fprintf( f, "\n" );
		}
	}
}

void
CModelText::OwnsDump( const CDbEntity& dbEntity, FILE* f )
{
	const CDbContainer* dbContainer = dynamic_cast<const CDbContainer*>( &dbEntity );
	if (dbContainer != NULL)
	{
		CString	name;
		int	count, indx;
		int	tlen, slen;

		count = dbContainer->Count();
		if (count > 0)
		{
			fprintf( f, "\t------------------- owns -------------------\n" );
			fprintf( f, "\t" );

			tlen = 0;
			for (indx = 0; indx < count; ++indx)
			{
				name = (*dbContainer)[indx]->Name();

				slen = (name.GetLength() + 1);  // ie. plus the comma
				tlen += slen;

				if (tlen > MAXLEN)
				{
					fprintf( f, "\n\t" );
					tlen = slen;
				}

				fprintf( f, "%s,", name );
			}
		}

		fprintf( f, "\n" );
	}
}

void
CModelText::CanonicalDump( const CDbEntity& dbEntity, FILE* f )
{
	if ( HasCanonicalData( dbEntity ) )
	{
		C3dCoord pt, pc;
		C3dCoord ps, pe;
		C3x4Matrix xform;
		C3dVec vec;

		fprintf( f, "\t------------------- data -------------------\n" );

		switch (dbEntity.Type())
		{
		case DBWORKPLANE:
			{
			const CDbWorkplane& dbWork = (const CDbWorkplane&) dbEntity;

			xform = dbWork.Transform();

			vec = xform.getI();
			fprintf( f, "\tivec: x=%11.6f, y=%11.6f, z=%11.6f\n", vec.X(), vec.Y(), vec.Z() );

			vec = xform.getJ();
			fprintf( f, "\tjvec: x=%11.6f, y=%11.6f, z=%11.6f\n", vec.X(), vec.Y(), vec.Z() );

			vec = xform.getK();
			fprintf( f, "\tkvec: x=%11.6f, y=%11.6f, z=%11.6f\n", vec.X(), vec.Y(), vec.Z() );

			pt = xform.getT();
			fprintf( f, "\t   t: x=%11.6f, y=%11.6f, z=%11.6f\n", pt.X(), pt.Y(), pt.Z() );
			}
			break;

		case DBTOOL:
			break;

		case DBPOINT:
			pt = ((const CDbPoint&) dbEntity).Coord();
			fprintf( f, "\tx=%11.6f, y=%11.6f, z=%11.6f\n", pt.X(), pt.Y(), pt.Z() );
			break;

		case DBLINE:
			{
			const CDbLine& dbLine = (const CDbLine&) dbEntity;

			ps = dbLine.StartPt();
			pe = dbLine.EndPt();

			vec = pe - ps;

			fprintf( f, "\tps: x=%11.6f, y=%11.6f, z=%11.6f\n", ps.X(), ps.Y(), ps.Z() );
			fprintf( f, "\tpe: x=%11.6f, y=%11.6f, z=%11.6f\n", pe.X(), pe.Y(), pe.Z() );
			fprintf( f, "\t3dLen=%11.6f\n", vec.Length() );
			}
			break;

		case DBARC:
			{
			const CDbArc& dbArc = (const CDbArc&) dbEntity;

			ps = dbArc.StartPt();
			pe = dbArc.EndPt();
			pc = dbArc.CenterPt();

			fprintf( f, "\tps: x=%11.6f, y=%11.6f, z=%11.6f\n", ps.X(), ps.Y(), ps.Z() );
			fprintf( f, "\tpe: x=%11.6f, y=%11.6f, z=%11.6f\n", pe.X(), pe.Y(), pe.Z() );
			fprintf( f, "\tpc: x=%11.6f, y=%11.6f, z=%11.6f\n", pc.X(), pc.Y(), pc.Z() );
			fprintf( f, "\trad=%11.6f, dir=%d", dbArc.Radius(), dbArc.Dir() );
			}
			break;

		case DBHOLE:
			{
			const CDbHole& dbHole = (const CDbHole&) dbEntity;
			
			pt = dbHole.Coord();

			fprintf( f, "\tpc: x=%11.6f, y=%11.6f, z=%11.6f\n", pt.X(), pt.Y(), pt.Z() );
			fprintf( f, "\tdiam=%11.6f, depth=%11.6f\n", dbHole.Diam(), dbHole.Depth() );
			}
			break;

		case DBPROFILE:
			{
			const CDbProfile& dbProfile = (const CDbProfile&) dbEntity;
			fprintf( f, "\tassoc=%d\n", (dbProfile.IsAssociated() ? 1 : 0) );
			}
			break;

		case DBCOMMAND:
			{
			const CDbCommand& dbCmd = (const CDbCommand&) dbEntity;
			
			pt = dbCmd.Coord();

			fprintf( f, "\tx=%11.6f, y=%11.6f, z=%11.6f\n, '%s'",
					 pt.X(), pt.Y(), pt.Z(), dbCmd.Text()  );
			}
			break;

		case DBFEATURE:
		case DBSEQUENCE:
		case DBPATTERN:
			break;

		default:
			ASSERT( FALSE );  // Invalid case.
		}
	}
}

CString
CModelText::EntityDescription( const CDbEntity& dbEntity )
{
	CString desc;
	CString name;

	switch (dbEntity.Type())
	{
	case DBWORKPLANE:	name.Format(  "Workplane: id=%d", dbEntity.Id() );	break;
	case DBTOOL:		name.Format(  "Tool: id=%d", dbEntity.Id() );		break;
	case DBPOINT:		name.Format(  "Point: id=%d", dbEntity.Id() );		break;
	case DBLINE:		name.Format(  "Line: id=%d", dbEntity.Id() );		break;
	case DBARC:			name.Format(  "Arc: id=%d", dbEntity.Id() );		break;
	case DBHOLE:		name.Format(  "Hole: id=%d", dbEntity.Id() );		break;
	case DBPROFILE:		name.Format(  "Profile: id=%d", dbEntity.Id() );	break;
	case DBCOMMAND:		name.Format(  "Command: id=%d", dbEntity.Id() );	break;
	case DBFEATURE:		name.Format(  "Feature: id=%d", dbEntity.Id() );	break;
	case DBSEQUENCE:	name.Format(  "Sequence: id=%d", dbEntity.Id() );	break;
	case DBPATTERN:		name.Format(  "Pattern: id=%d", dbEntity.Id() );	break;
	default:			name.Format(  "UNKNOWN: id=%d", dbEntity.Id() );	break;
	}

	if ( dbEntity.IsDeleted() )
		desc.Format( "<font color=\"#FF0000\">%s</font>", name );
	else
		desc = name;

	return desc;
}

bool
CModelText::CanReference( const CDbEntity& dbEntity )
{
	switch (dbEntity.Type())
	{
	case DBWORKPLANE:	return FALSE;	break;
	case DBTOOL:		return FALSE;	break;
	case DBPOINT:		return FALSE;	break;
	case DBLINE:		return TRUE;	break;
	case DBARC:			return TRUE;	break;
	case DBHOLE:		return FALSE;	break;
	case DBPROFILE:		return TRUE;	break;
	case DBCOMMAND:		return FALSE;	break;
	case DBFEATURE:		return TRUE;	break;
	case DBSEQUENCE:	return TRUE;	break;
	case DBPATTERN:		return FALSE;	break;
	default:			return FALSE;	break;
	}
}

bool
CModelText::HasCanonicalData( const CDbEntity& dbEntity )
{
	switch (dbEntity.Type())
	{
	case DBWORKPLANE:
	case DBPOINT:
	case DBLINE:
	case DBARC:
	case DBHOLE:
	case DBPROFILE:
	case DBCOMMAND:
		return TRUE;
	default:
		return FALSE;
	}
}

CString
CModelText::Label( EDbEntityType type )
{
	switch( type )
	{
	case DBLAYER:		return "layer:    ";
	case DBWORKPLANE:	return "work:     ";
	case DBTOOL:		return "tool:     ";
	case DBPOINT:		return "point:    ";
	case DBLINE:		return "line:     ";
	case DBARC:			return "arc:      ";
	case DBHOLE:		return "hole:     ";
	case DBPROFILE:		return "profile:  ";
	case DBCOMMAND:		return "command:  ";
	case DBFEATURE:		return "feature:  ";
	case DBPATTERN:		return "pattern:  ";
	case DBSEQUENCE:	return "sequence: ";
	default:			return "unknown:  ";
	}
}

// NOTE: CModelText was written for RTL analysis.  As such, we
// prevent various attributes from being written to the text file
// because 1) the corresponding values are expected to change
// 2) the values are not relevant to the status of the test.
bool
CModelText::CanPrint( const CString& name )
{
	char	first;
	bool	can_print;

	can_print = true;

	first = name.GetAt(0);
	if ((first == 'P') || (first =='p'))
	{
		// Just don't ever want to see this useless attribute.
		can_print = (name.CompareNoCase("ProjNum") != 0);

		// And this one will change as rtl files get relocated.
		if (can_print && m_is_rtl_running)
			can_print = (name.CompareNoCase("pdb_file") != 0);
	}

	return can_print;
}