
#line 3 "CmdLexer.cpp"

#define  CMD_YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define CMD_YY_FLEX_MAJOR_VERSION 2
#define CMD_YY_FLEX_MINOR_VERSION 5
#define CMD_YY_FLEX_SUBMINOR_VERSION 35
#if CMD_YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define CMD_YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define CMD_YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef CMD_YY_USE_CONST
#define cmd_yyconst const
#else
#define cmd_yyconst
#endif

/* Returned upon end-of-file. */
#define CMD_YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define CMD_YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (cmd_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The CMD_YYSTATE alias is for lex
 * compatibility.
 */
#define CMD_YY_START (((cmd_yy_start) - 1) / 2)
#define CMD_YYSTATE CMD_YY_START

/* Action number for EOF rule of a given start state. */
#define CMD_YY_STATE_EOF(state) (CMD_YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define CMD_YY_NEW_FILE cmd_yyrestart(cmd_yyin  )

#define CMD_YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef CMD_YY_BUF_SIZE
#define CMD_YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define CMD_YY_STATE_BUF_SIZE   ((CMD_YY_BUF_SIZE + 2) * sizeof(cmd_yy_state_type))

#ifndef CMD_YY_TYPEDEF_CMD_YY_BUFFER_STATE
#define CMD_YY_TYPEDEF_CMD_YY_BUFFER_STATE
typedef struct cmd_yy_buffer_state *CMD_YY_BUFFER_STATE;
#endif

extern int cmd_yyleng;

extern FILE *cmd_yyin, *cmd_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define CMD_YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define cmd_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cmd_yytext. */ \
        int cmd_yyless_macro_arg = (n); \
        CMD_YY_LESS_LINENO(cmd_yyless_macro_arg);\
		*cmd_yy_cp = (cmd_yy_hold_char); \
		CMD_YY_RESTORE_CMD_YY_MORE_OFFSET \
		(cmd_yy_c_buf_p) = cmd_yy_cp = cmd_yy_bp + cmd_yyless_macro_arg - CMD_YY_MORE_ADJ; \
		CMD_YY_DO_BEFORE_ACTION; /* set up cmd_yytext again */ \
		} \
	while ( 0 )

#define unput(c) cmd_yyunput( c, (cmd_yytext_ptr)  )

#ifndef CMD_YY_TYPEDEF_CMD_YY_SIZE_T
#define CMD_YY_TYPEDEF_CMD_YY_SIZE_T
typedef size_t cmd_yy_size_t;
#endif

#ifndef CMD_YY_STRUCT_CMD_YY_BUFFER_STATE
#define CMD_YY_STRUCT_CMD_YY_BUFFER_STATE
struct cmd_yy_buffer_state
	{
	FILE *cmd_yy_input_file;

	char *cmd_yy_ch_buf;		/* input buffer */
	char *cmd_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	cmd_yy_size_t cmd_yy_buf_size;

	/* Number of characters read into cmd_yy_ch_buf, not including EOB
	 * characters.
	 */
	int cmd_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int cmd_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int cmd_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int cmd_yy_at_bol;

    int cmd_yy_bs_lineno; /**< The line count. */
    int cmd_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int cmd_yy_fill_buffer;

	int cmd_yy_buffer_status;

#define CMD_YY_BUFFER_NEW 0
#define CMD_YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as CMD_YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cmd_yyrestart()), so that the user can continue scanning by
	 * just pointing cmd_yyin at a new input file.
	 */
#define CMD_YY_BUFFER_EOF_PENDING 2

	};
#endif /* !CMD_YY_STRUCT_CMD_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t cmd_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t cmd_yy_buffer_stack_max = 0; /**< capacity of stack. */
static CMD_YY_BUFFER_STATE * cmd_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define CMD_YY_CURRENT_BUFFER ( (cmd_yy_buffer_stack) \
                          ? (cmd_yy_buffer_stack)[(cmd_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define CMD_YY_CURRENT_BUFFER_LVALUE (cmd_yy_buffer_stack)[(cmd_yy_buffer_stack_top)]

/* cmd_yy_hold_char holds the character lost when cmd_yytext is formed. */
static char cmd_yy_hold_char;
static int cmd_yy_n_chars;		/* number of characters read into cmd_yy_ch_buf */
int cmd_yyleng;

/* Points to current character in buffer. */
static char *cmd_yy_c_buf_p = (char *) 0;
static int cmd_yy_init = 0;		/* whether we need to initialize */
static int cmd_yy_start = 0;	/* start state number */

/* Flag which is used to allow cmd_yywrap()'s to do buffer switches
 * instead of setting up a fresh cmd_yyin.  A bit of a hack ...
 */
static int cmd_yy_did_buffer_switch_on_eof;

void cmd_yyrestart (FILE *input_file  );
void cmd_yy_switch_to_buffer (CMD_YY_BUFFER_STATE new_buffer  );
CMD_YY_BUFFER_STATE cmd_yy_create_buffer (FILE *file,int size  );
void cmd_yy_delete_buffer (CMD_YY_BUFFER_STATE b  );
void cmd_yy_flush_buffer (CMD_YY_BUFFER_STATE b  );
void cmd_yypush_buffer_state (CMD_YY_BUFFER_STATE new_buffer  );
void cmd_yypop_buffer_state (void );

static void cmd_yyensure_buffer_stack (void );
static void cmd_yy_load_buffer_state (void );
static void cmd_yy_init_buffer (CMD_YY_BUFFER_STATE b,FILE *file  );

#define CMD_YY_FLUSH_BUFFER cmd_yy_flush_buffer(CMD_YY_CURRENT_BUFFER )

CMD_YY_BUFFER_STATE cmd_yy_scan_buffer (char *base,cmd_yy_size_t size  );
CMD_YY_BUFFER_STATE cmd_yy_scan_string (cmd_yyconst char *cmd_yy_str  );
CMD_YY_BUFFER_STATE cmd_yy_scan_bytes (cmd_yyconst char *bytes,int len  );

void *cmd_yyalloc (cmd_yy_size_t  );
void *cmd_yyrealloc (void *,cmd_yy_size_t  );
void cmd_yyfree (void *  );

#define cmd_yy_new_buffer cmd_yy_create_buffer

#define cmd_yy_set_interactive(is_interactive) \
	{ \
	if ( ! CMD_YY_CURRENT_BUFFER ){ \
        cmd_yyensure_buffer_stack (); \
		CMD_YY_CURRENT_BUFFER_LVALUE =    \
            cmd_yy_create_buffer(cmd_yyin,CMD_YY_BUF_SIZE ); \
	} \
	CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_is_interactive = is_interactive; \
	}

#define cmd_yy_set_bol(at_bol) \
	{ \
	if ( ! CMD_YY_CURRENT_BUFFER ){\
        cmd_yyensure_buffer_stack (); \
		CMD_YY_CURRENT_BUFFER_LVALUE =    \
            cmd_yy_create_buffer(cmd_yyin,CMD_YY_BUF_SIZE ); \
	} \
	CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_at_bol = at_bol; \
	}

#define CMD_YY_AT_BOL() (CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char CMD_YY_CHAR;

FILE *cmd_yyin = (FILE *) 0, *cmd_yyout = (FILE *) 0;

typedef int cmd_yy_state_type;

extern int cmd_yylineno;

int cmd_yylineno = 1;

extern char *cmd_yytext;
#define cmd_yytext_ptr cmd_yytext

static cmd_yy_state_type cmd_yy_get_previous_state (void );
static cmd_yy_state_type cmd_yy_try_NUL_trans (cmd_yy_state_type current_state  );
static int cmd_yy_get_next_buffer (void );
static void cmd_yy_fatal_error (cmd_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cmd_yytext.
 */
#define CMD_YY_DO_BEFORE_ACTION \
	(cmd_yytext_ptr) = cmd_yy_bp; \
	cmd_yyleng = (size_t) (cmd_yy_cp - cmd_yy_bp); \
	(cmd_yy_hold_char) = *cmd_yy_cp; \
	*cmd_yy_cp = '\0'; \
	(cmd_yy_c_buf_p) = cmd_yy_cp;

#define CMD_YY_NUM_RULES 12
#define CMD_YY_END_OF_BUFFER 13
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct cmd_yy_trans_info
	{
	flex_int32_t cmd_yy_verify;
	flex_int32_t cmd_yy_nxt;
	};
static cmd_yyconst flex_int16_t cmd_yy_accept[28] =
    {   0,
        0,    0,   13,   12,    1,    9,   11,   12,    3,    4,
       12,   12,   11,    0,   10,    4,    8,    7,    2,    0,
        0,    2,    0,    6,    0,    5,    0
    } ;

static cmd_yyconst flex_int32_t cmd_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    5,    1,    1,    6,    1,
        1,    1,    7,    8,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    8,    1,    1,
        8,    1,    1,    5,   13,   13,   13,   13,   14,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   13,    1,   13,   13,   13,   13,

       14,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static cmd_yyconst flex_int32_t cmd_yy_meta[15] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    4,    5,
        1,    6,    7,    7
    } ;

static cmd_yyconst flex_int16_t cmd_yy_base[34] =
    {   0,
        0,    0,   55,   56,   56,   56,    0,   48,   56,   43,
       40,   40,    0,   44,   56,   39,    3,    4,    0,   36,
       35,    0,   34,   32,   28,   20,   56,   13,   20,   24,
       30,   35,   39
    } ;

static cmd_yyconst flex_int16_t cmd_yy_def[34] =
    {   0,
       27,    1,   27,   27,   27,   27,   28,   29,   27,   30,
       27,   27,   28,   29,   27,   30,   27,   27,   31,   32,
       33,   31,   27,   27,   27,   27,    0,   27,   27,   27,
       27,   27,   27
    } ;

static cmd_yyconst flex_int16_t cmd_yy_nxt[71] =
    {   0,
        4,    5,    4,    6,    7,    8,    4,    9,   10,   11,
       12,   10,    7,    7,   18,   18,   20,   21,   13,   13,
       14,   14,   14,   14,   14,   14,   14,   16,   16,   16,
       22,   26,   22,   22,   22,   22,   22,   23,   23,   26,
       23,   25,   25,   24,   25,   24,   26,   24,   17,   15,
       19,   18,   17,   15,   27,    3,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27
    } ;

static cmd_yyconst flex_int16_t cmd_yy_chk[71] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   17,   18,   17,   18,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   30,   30,   30,
       31,   26,   31,   31,   31,   31,   31,   32,   32,   25,
       32,   33,   33,   24,   33,   23,   21,   20,   16,   14,
       12,   11,   10,    8,    3,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27
    } ;

static cmd_yy_state_type cmd_yy_last_accepting_state;
static char *cmd_yy_last_accepting_cpos;

extern int cmd_yy_flex_debug;
int cmd_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define cmd_yymore() cmd_yymore_used_but_not_detected
#define CMD_YY_MORE_ADJ 0
#define CMD_YY_RESTORE_CMD_YY_MORE_OFFSET
char *cmd_yytext;

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// NOTE: This source file is was generated by cygwin's flex.exe
//   i.e. flex -L -oCmdLexer.cpp CmdLexer.l
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#include "stdafx.h"
#include <io.h>

#include "VarList.h"
#include "Command.h"
#include "CmdParser.h"

#define BUFFER_MAX 1024
static char buffer[BUFFER_MAX];  // must match definition of m_string in CmdParser.y
static const char* string_get( char terminal_char );

// Otherwise the lexer is file-based.
#define CMD_YY_ALWAYS_INTERACTIVE 1

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// Do the usual stuff to avoid the lex-generated input()
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#define EOS '\0'

extern char cmd_getc();

// The following macro is defined to obtain one character of input.
// The lexer generates it's own similar macro but we define this one
// as an override since we are using a char sting as the input.
// The function jos_getc() acts as the interface.
#define CMD_YY_INPUT(buf,result,max_size) \
{ \
	int c = cmd_getc(); \
	if ( c == EOF || c == EOS ) \
	{ \
		buf[0] = EOS; \
		result = 0; \
	} \
	else \
	{ \
		buf[0] = (char) c; \
		result = 1; \
	} \
}

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#define INITIAL 0

#ifndef CMD_YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
// #include <unistd.h>
#endif

#ifndef CMD_YY_EXTRA_TYPE
#define CMD_YY_EXTRA_TYPE void *
#endif

static int cmd_yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cmd_yylex_destroy (void );

int cmd_yyget_debug (void );

void cmd_yyset_debug (int debug_flag  );

CMD_YY_EXTRA_TYPE cmd_yyget_extra (void );

void cmd_yyset_extra (CMD_YY_EXTRA_TYPE user_defined  );

FILE *cmd_yyget_in (void );

void cmd_yyset_in  (FILE * in_str  );

FILE *cmd_yyget_out (void );

void cmd_yyset_out  (FILE * out_str  );

int cmd_yyget_leng (void );

char *cmd_yyget_text (void );

int cmd_yyget_lineno (void );

void cmd_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef CMD_YY_SKIP_CMD_YYWRAP
#ifdef __cplusplus
extern "C" int cmd_yywrap (void );
#else
extern int cmd_yywrap (void );
#endif
#endif

    static void cmd_yyunput (int c,char *buf_ptr  );
    
#ifndef cmd_yytext_ptr
static void cmd_yy_flex_strncpy (char *,cmd_yyconst char *,int );
#endif

#ifdef CMD_YY_NEED_STRLEN
static int cmd_yy_flex_strlen (cmd_yyconst char * );
#endif

#ifndef CMD_YY_NO_INPUT

#ifdef __cplusplus
static int cmd_yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef CMD_YY_READ_BUF_SIZE
#define CMD_YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( cmd_yytext, cmd_yyleng, 1, cmd_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or CMD_YY_NULL,
 * is returned in "result".
 */
#ifndef CMD_YY_INPUT
#define CMD_YY_INPUT(buf,result,max_size) \
	if ( CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cmd_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cmd_yyin ) ) \
			CMD_YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cmd_yyin))==0 && ferror(cmd_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				CMD_YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cmd_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "cmd_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef cmd_yyterminate
#define cmd_yyterminate() return CMD_YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef CMD_YY_START_STACK_INCR
#define CMD_YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef CMD_YY_FATAL_ERROR
#define CMD_YY_FATAL_ERROR(msg) cmd_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef CMD_YY_DECL
#define CMD_YY_DECL_IS_OURS 1

extern int cmd_yylex (void);

#define CMD_YY_DECL int cmd_yylex (void)
#endif /* !CMD_YY_DECL */

/* Code executed at the beginning of each rule, after cmd_yytext and cmd_yyleng
 * have been set up.
 */
#ifndef CMD_YY_USER_ACTION
#define CMD_YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef CMD_YY_BREAK
#define CMD_YY_BREAK break;
#endif

#define CMD_YY_RULE_SETUP \
	CMD_YY_USER_ACTION

/** The main scanner function which does all the work.
 */
CMD_YY_DECL
{
	register cmd_yy_state_type cmd_yy_current_state;
	register char *cmd_yy_cp, *cmd_yy_bp;
	register int cmd_yy_act;
    
	if ( !(cmd_yy_init) )
		{
		(cmd_yy_init) = 1;

#ifdef CMD_YY_USER_INIT
		CMD_YY_USER_INIT;
#endif

		if ( ! (cmd_yy_start) )
			(cmd_yy_start) = 1;	/* first start state */

		if ( ! cmd_yyin )
			cmd_yyin = stdin;

		if ( ! cmd_yyout )
			cmd_yyout = stdout;

		if ( ! CMD_YY_CURRENT_BUFFER ) {
			cmd_yyensure_buffer_stack ();
			CMD_YY_CURRENT_BUFFER_LVALUE =
				cmd_yy_create_buffer(cmd_yyin,CMD_YY_BUF_SIZE );
		}

		cmd_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		cmd_yy_cp = (cmd_yy_c_buf_p);

		/* Support of cmd_yytext. */
		*cmd_yy_cp = (cmd_yy_hold_char);

		/* cmd_yy_bp points to the position in cmd_yy_ch_buf of the start of
		 * the current run.
		 */
		cmd_yy_bp = cmd_yy_cp;

		cmd_yy_current_state = (cmd_yy_start);
cmd_yy_match:
		do
			{
			register CMD_YY_CHAR cmd_yy_c = cmd_yy_ec[CMD_YY_SC_TO_UI(*cmd_yy_cp)];
			if ( cmd_yy_accept[cmd_yy_current_state] )
				{
				(cmd_yy_last_accepting_state) = cmd_yy_current_state;
				(cmd_yy_last_accepting_cpos) = cmd_yy_cp;
				}
			while ( cmd_yy_chk[cmd_yy_base[cmd_yy_current_state] + cmd_yy_c] != cmd_yy_current_state )
				{
				cmd_yy_current_state = (int) cmd_yy_def[cmd_yy_current_state];
				if ( cmd_yy_current_state >= 28 )
					cmd_yy_c = cmd_yy_meta[(unsigned int) cmd_yy_c];
				}
			cmd_yy_current_state = cmd_yy_nxt[cmd_yy_base[cmd_yy_current_state] + (unsigned int) cmd_yy_c];
			++cmd_yy_cp;
			}
		while ( cmd_yy_base[cmd_yy_current_state] != 56 );

cmd_yy_find_action:
		cmd_yy_act = cmd_yy_accept[cmd_yy_current_state];
		if ( cmd_yy_act == 0 )
			{ /* have to back up */
			cmd_yy_cp = (cmd_yy_last_accepting_cpos);
			cmd_yy_current_state = (cmd_yy_last_accepting_state);
			cmd_yy_act = cmd_yy_accept[cmd_yy_current_state];
			}

		CMD_YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( cmd_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of CMD_YY_DO_BEFORE_ACTION */
			*cmd_yy_cp = (cmd_yy_hold_char);
			cmd_yy_cp = (cmd_yy_last_accepting_cpos);
			cmd_yy_current_state = (cmd_yy_last_accepting_state);
			goto cmd_yy_find_action;

case 1:
CMD_YY_RULE_SETUP
;
	CMD_YY_BREAK
case 2:
CMD_YY_RULE_SETUP
;
	CMD_YY_BREAK
case 3:
CMD_YY_RULE_SETUP
{ return cmd_yytext[0]; }
	CMD_YY_BREAK
case 4:
CMD_YY_RULE_SETUP
{ cmd_yylval.m_int = atoi(cmd_yytext); return INT; }
	CMD_YY_BREAK
case 5:
CMD_YY_RULE_SETUP
{ cmd_yylval.m_real = atof(cmd_yytext); return REAL; }
	CMD_YY_BREAK
case 6:
CMD_YY_RULE_SETUP
{ cmd_yylval.m_real = atof(cmd_yytext); return REAL; }
	CMD_YY_BREAK
case 7:
CMD_YY_RULE_SETUP
{ cmd_yylval.m_real = atof(cmd_yytext); return REAL; }
	CMD_YY_BREAK
case 8:
CMD_YY_RULE_SETUP
{ cmd_yylval.m_real = atof(cmd_yytext); return REAL; }
	CMD_YY_BREAK
case 9:
CMD_YY_RULE_SETUP
{ 
				strcpy( cmd_yylval.m_string, string_get('"') );
				return STRING;
			}
	CMD_YY_BREAK
case 10:
/* rule 10 can match eol */
CMD_YY_RULE_SETUP
{ 
							if (strlen(cmd_yytext) < 3)
							{
								cmd_yylval.m_string[0] = '\0';
							}
							else
							{
								cmd_yytext[ strlen(cmd_yytext)-1 ] = 0;
								strcpy( cmd_yylval.m_string, (cmd_yytext+1) );
							}
							return STRING;
						}
	CMD_YY_BREAK
case 11:
CMD_YY_RULE_SETUP
{ 
							strcpy( cmd_yylval.m_string, cmd_yytext );
							return IDENTIFIER;
						}
	CMD_YY_BREAK
case 12:
CMD_YY_RULE_SETUP
ECHO;
	CMD_YY_BREAK
case CMD_YY_STATE_EOF(INITIAL):
	cmd_yyterminate();

	case CMD_YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int cmd_yy_amount_of_matched_text = (int) (cmd_yy_cp - (cmd_yytext_ptr)) - 1;

		/* Undo the effects of CMD_YY_DO_BEFORE_ACTION. */
		*cmd_yy_cp = (cmd_yy_hold_char);
		CMD_YY_RESTORE_CMD_YY_MORE_OFFSET

		if ( CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buffer_status == CMD_YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cmd_yyin at a new source and called
			 * cmd_yylex().  If so, then we have to assure
			 * consistency between CMD_YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(cmd_yy_n_chars) = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars;
			CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_input_file = cmd_yyin;
			CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buffer_status = CMD_YY_BUFFER_NORMAL;
			}

		/* Note that here we test for cmd_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since cmd_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (cmd_yy_c_buf_p) <= &CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[(cmd_yy_n_chars)] )
			{ /* This was really a NUL. */
			cmd_yy_state_type cmd_yy_next_state;

			(cmd_yy_c_buf_p) = (cmd_yytext_ptr) + cmd_yy_amount_of_matched_text;

			cmd_yy_current_state = cmd_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * cmd_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			cmd_yy_next_state = cmd_yy_try_NUL_trans( cmd_yy_current_state );

			cmd_yy_bp = (cmd_yytext_ptr) + CMD_YY_MORE_ADJ;

			if ( cmd_yy_next_state )
				{
				/* Consume the NUL. */
				cmd_yy_cp = ++(cmd_yy_c_buf_p);
				cmd_yy_current_state = cmd_yy_next_state;
				goto cmd_yy_match;
				}

			else
				{
				cmd_yy_cp = (cmd_yy_c_buf_p);
				goto cmd_yy_find_action;
				}
			}

		else switch ( cmd_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(cmd_yy_did_buffer_switch_on_eof) = 0;

				if ( cmd_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * cmd_yy_get_next_buffer() to have set up
					 * cmd_yytext, we can now set up
					 * cmd_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * CMD_YY_NULL, it'll still work - another
					 * CMD_YY_NULL will get returned.
					 */
					(cmd_yy_c_buf_p) = (cmd_yytext_ptr) + CMD_YY_MORE_ADJ;

					cmd_yy_act = CMD_YY_STATE_EOF(CMD_YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (cmd_yy_did_buffer_switch_on_eof) )
						CMD_YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(cmd_yy_c_buf_p) =
					(cmd_yytext_ptr) + cmd_yy_amount_of_matched_text;

				cmd_yy_current_state = cmd_yy_get_previous_state(  );

				cmd_yy_cp = (cmd_yy_c_buf_p);
				cmd_yy_bp = (cmd_yytext_ptr) + CMD_YY_MORE_ADJ;
				goto cmd_yy_match;

			case EOB_ACT_LAST_MATCH:
				(cmd_yy_c_buf_p) =
				&CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[(cmd_yy_n_chars)];

				cmd_yy_current_state = cmd_yy_get_previous_state(  );

				cmd_yy_cp = (cmd_yy_c_buf_p);
				cmd_yy_bp = (cmd_yytext_ptr) + CMD_YY_MORE_ADJ;
				goto cmd_yy_find_action;
			}
		break;
		}

	default:
		CMD_YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cmd_yylex */

/* cmd_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int cmd_yy_get_next_buffer (void)
{
    	register char *dest = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf;
	register char *source = (cmd_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (cmd_yy_c_buf_p) > &CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[(cmd_yy_n_chars) + 1] )
		CMD_YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (cmd_yy_c_buf_p) - (cmd_yytext_ptr) - CMD_YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((cmd_yy_c_buf_p) - (cmd_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buffer_status == CMD_YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars = (cmd_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			CMD_YY_BUFFER_STATE b = CMD_YY_CURRENT_BUFFER;

			int cmd_yy_c_buf_p_offset =
				(int) ((cmd_yy_c_buf_p) - b->cmd_yy_ch_buf);

			if ( b->cmd_yy_is_our_buffer )
				{
				int new_size = b->cmd_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->cmd_yy_buf_size += b->cmd_yy_buf_size / 8;
				else
					b->cmd_yy_buf_size *= 2;

				b->cmd_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cmd_yyrealloc((void *) b->cmd_yy_ch_buf,b->cmd_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->cmd_yy_ch_buf = 0;

			if ( ! b->cmd_yy_ch_buf )
				CMD_YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(cmd_yy_c_buf_p) = &b->cmd_yy_ch_buf[cmd_yy_c_buf_p_offset];

			num_to_read = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > CMD_YY_READ_BUF_SIZE )
			num_to_read = CMD_YY_READ_BUF_SIZE;

		/* Read in more data. */
		CMD_YY_INPUT( (&CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[number_to_move]),
			(cmd_yy_n_chars), (size_t) num_to_read );

		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars = (cmd_yy_n_chars);
		}

	if ( (cmd_yy_n_chars) == 0 )
		{
		if ( number_to_move == CMD_YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cmd_yyrestart(cmd_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buffer_status =
				CMD_YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((cmd_yy_size_t) ((cmd_yy_n_chars) + number_to_move) > CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		cmd_yy_size_t new_size = (cmd_yy_n_chars) + number_to_move + ((cmd_yy_n_chars) >> 1);
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf = (char *) cmd_yyrealloc((void *) CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf,new_size  );
		if ( ! CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf )
			CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yy_get_next_buffer()" );
	}

	(cmd_yy_n_chars) += number_to_move;
	CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[(cmd_yy_n_chars)] = CMD_YY_END_OF_BUFFER_CHAR;
	CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[(cmd_yy_n_chars) + 1] = CMD_YY_END_OF_BUFFER_CHAR;

	(cmd_yytext_ptr) = &CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[0];

	return ret_val;
}

/* cmd_yy_get_previous_state - get the state just before the EOB char was reached */

    static cmd_yy_state_type cmd_yy_get_previous_state (void)
{
	register cmd_yy_state_type cmd_yy_current_state;
	register char *cmd_yy_cp;
    
	cmd_yy_current_state = (cmd_yy_start);

	for ( cmd_yy_cp = (cmd_yytext_ptr) + CMD_YY_MORE_ADJ; cmd_yy_cp < (cmd_yy_c_buf_p); ++cmd_yy_cp )
		{
		register CMD_YY_CHAR cmd_yy_c = (*cmd_yy_cp ? cmd_yy_ec[CMD_YY_SC_TO_UI(*cmd_yy_cp)] : 1);
		if ( cmd_yy_accept[cmd_yy_current_state] )
			{
			(cmd_yy_last_accepting_state) = cmd_yy_current_state;
			(cmd_yy_last_accepting_cpos) = cmd_yy_cp;
			}
		while ( cmd_yy_chk[cmd_yy_base[cmd_yy_current_state] + cmd_yy_c] != cmd_yy_current_state )
			{
			cmd_yy_current_state = (int) cmd_yy_def[cmd_yy_current_state];
			if ( cmd_yy_current_state >= 28 )
				cmd_yy_c = cmd_yy_meta[(unsigned int) cmd_yy_c];
			}
		cmd_yy_current_state = cmd_yy_nxt[cmd_yy_base[cmd_yy_current_state] + (unsigned int) cmd_yy_c];
		}

	return cmd_yy_current_state;
}

/* cmd_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = cmd_yy_try_NUL_trans( current_state );
 */
    static cmd_yy_state_type cmd_yy_try_NUL_trans  (cmd_yy_state_type cmd_yy_current_state )
{
	register int cmd_yy_is_jam;
    	register char *cmd_yy_cp = (cmd_yy_c_buf_p);

	register CMD_YY_CHAR cmd_yy_c = 1;
	if ( cmd_yy_accept[cmd_yy_current_state] )
		{
		(cmd_yy_last_accepting_state) = cmd_yy_current_state;
		(cmd_yy_last_accepting_cpos) = cmd_yy_cp;
		}
	while ( cmd_yy_chk[cmd_yy_base[cmd_yy_current_state] + cmd_yy_c] != cmd_yy_current_state )
		{
		cmd_yy_current_state = (int) cmd_yy_def[cmd_yy_current_state];
		if ( cmd_yy_current_state >= 28 )
			cmd_yy_c = cmd_yy_meta[(unsigned int) cmd_yy_c];
		}
	cmd_yy_current_state = cmd_yy_nxt[cmd_yy_base[cmd_yy_current_state] + (unsigned int) cmd_yy_c];
	cmd_yy_is_jam = (cmd_yy_current_state == 27);

	return cmd_yy_is_jam ? 0 : cmd_yy_current_state;
}

    static void cmd_yyunput (int c, register char * cmd_yy_bp )
{
	register char *cmd_yy_cp;
    
    cmd_yy_cp = (cmd_yy_c_buf_p);

	/* undo effects of setting up cmd_yytext */
	*cmd_yy_cp = (cmd_yy_hold_char);

	if ( cmd_yy_cp < CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (cmd_yy_n_chars) + 2;
		register char *dest = &CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[
					CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_size + 2];
		register char *source =
				&CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[number_to_move];

		while ( source > CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf )
			*--dest = *--source;

		cmd_yy_cp += (int) (dest - source);
		cmd_yy_bp += (int) (dest - source);
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars =
			(cmd_yy_n_chars) = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_size;

		if ( cmd_yy_cp < CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf + 2 )
			CMD_YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--cmd_yy_cp = (char) c;

	(cmd_yytext_ptr) = cmd_yy_bp;
	(cmd_yy_hold_char) = *cmd_yy_cp;
	(cmd_yy_c_buf_p) = cmd_yy_cp;
}

#ifndef CMD_YY_NO_INPUT
#ifdef __cplusplus
    static int cmd_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(cmd_yy_c_buf_p) = (cmd_yy_hold_char);

	if ( *(cmd_yy_c_buf_p) == CMD_YY_END_OF_BUFFER_CHAR )
		{
		/* cmd_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (cmd_yy_c_buf_p) < &CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_ch_buf[(cmd_yy_n_chars)] )
			/* This was really a NUL. */
			*(cmd_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (cmd_yy_c_buf_p) - (cmd_yytext_ptr);
			++(cmd_yy_c_buf_p);

			switch ( cmd_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because cmd_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cmd_yyrestart(cmd_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cmd_yywrap( ) )
						return EOF;

					if ( ! (cmd_yy_did_buffer_switch_on_eof) )
						CMD_YY_NEW_FILE;
#ifdef __cplusplus
					return cmd_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(cmd_yy_c_buf_p) = (cmd_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (cmd_yy_c_buf_p);	/* cast for 8-bit char's */
	*(cmd_yy_c_buf_p) = '\0';	/* preserve cmd_yytext */
	(cmd_yy_hold_char) = *++(cmd_yy_c_buf_p);

	return c;
}
#endif	/* ifndef CMD_YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cmd_yyrestart  (FILE * input_file )
{
    
	if ( ! CMD_YY_CURRENT_BUFFER ){
        cmd_yyensure_buffer_stack ();
		CMD_YY_CURRENT_BUFFER_LVALUE =
            cmd_yy_create_buffer(cmd_yyin,CMD_YY_BUF_SIZE );
	}

	cmd_yy_init_buffer(CMD_YY_CURRENT_BUFFER,input_file );
	cmd_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cmd_yy_switch_to_buffer  (CMD_YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cmd_yypop_buffer_state();
	 *		cmd_yypush_buffer_state(new_buffer);
     */
	cmd_yyensure_buffer_stack ();
	if ( CMD_YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( CMD_YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(cmd_yy_c_buf_p) = (cmd_yy_hold_char);
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_pos = (cmd_yy_c_buf_p);
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars = (cmd_yy_n_chars);
		}

	CMD_YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cmd_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cmd_yywrap()) processing, but the only time this flag
	 * is looked at is after cmd_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(cmd_yy_did_buffer_switch_on_eof) = 1;
}

static void cmd_yy_load_buffer_state  (void)
{
    	(cmd_yy_n_chars) = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars;
	(cmd_yytext_ptr) = (cmd_yy_c_buf_p) = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_pos;
	cmd_yyin = CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_input_file;
	(cmd_yy_hold_char) = *(cmd_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c CMD_YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    CMD_YY_BUFFER_STATE cmd_yy_create_buffer  (FILE * file, int  size )
{
	CMD_YY_BUFFER_STATE b;
    
	b = (CMD_YY_BUFFER_STATE) cmd_yyalloc(sizeof( struct cmd_yy_buffer_state )  );
	if ( ! b )
		CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yy_create_buffer()" );

	b->cmd_yy_buf_size = size;

	/* cmd_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->cmd_yy_ch_buf = (char *) cmd_yyalloc(b->cmd_yy_buf_size + 2  );
	if ( ! b->cmd_yy_ch_buf )
		CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yy_create_buffer()" );

	b->cmd_yy_is_our_buffer = 1;

	cmd_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cmd_yy_create_buffer()
 * 
 */
    void cmd_yy_delete_buffer (CMD_YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == CMD_YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		CMD_YY_CURRENT_BUFFER_LVALUE = (CMD_YY_BUFFER_STATE) 0;

	if ( b->cmd_yy_is_our_buffer )
		cmd_yyfree((void *) b->cmd_yy_ch_buf  );

	cmd_yyfree((void *) b  );
}

#ifndef __cplusplus
// extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cmd_yyrestart() or at EOF.
 */
    static void cmd_yy_init_buffer  (CMD_YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cmd_yy_flush_buffer(b );

	b->cmd_yy_input_file = file;
	b->cmd_yy_fill_buffer = 1;

    /* If b is the current buffer, then cmd_yy_init_buffer was _probably_
     * called from cmd_yyrestart() or through cmd_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != CMD_YY_CURRENT_BUFFER){
        b->cmd_yy_bs_lineno = 1;
        b->cmd_yy_bs_column = 0;
    }

        b->cmd_yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, CMD_YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c CMD_YY_CURRENT_BUFFER.
 * 
 */
    void cmd_yy_flush_buffer (CMD_YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->cmd_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->cmd_yy_ch_buf[0] = CMD_YY_END_OF_BUFFER_CHAR;
	b->cmd_yy_ch_buf[1] = CMD_YY_END_OF_BUFFER_CHAR;

	b->cmd_yy_buf_pos = &b->cmd_yy_ch_buf[0];

	b->cmd_yy_at_bol = 1;
	b->cmd_yy_buffer_status = CMD_YY_BUFFER_NEW;

	if ( b == CMD_YY_CURRENT_BUFFER )
		cmd_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cmd_yypush_buffer_state (CMD_YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cmd_yyensure_buffer_stack();

	/* This block is copied from cmd_yy_switch_to_buffer. */
	if ( CMD_YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(cmd_yy_c_buf_p) = (cmd_yy_hold_char);
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_buf_pos = (cmd_yy_c_buf_p);
		CMD_YY_CURRENT_BUFFER_LVALUE->cmd_yy_n_chars = (cmd_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (CMD_YY_CURRENT_BUFFER)
		(cmd_yy_buffer_stack_top)++;
	CMD_YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cmd_yy_switch_to_buffer. */
	cmd_yy_load_buffer_state( );
	(cmd_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cmd_yypop_buffer_state (void)
{
    	if (!CMD_YY_CURRENT_BUFFER)
		return;

	cmd_yy_delete_buffer(CMD_YY_CURRENT_BUFFER );
	CMD_YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((cmd_yy_buffer_stack_top) > 0)
		--(cmd_yy_buffer_stack_top);

	if (CMD_YY_CURRENT_BUFFER) {
		cmd_yy_load_buffer_state( );
		(cmd_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cmd_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(cmd_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(cmd_yy_buffer_stack) = (struct cmd_yy_buffer_state**)cmd_yyalloc
								(num_to_alloc * sizeof(struct cmd_yy_buffer_state*)
								);
		if ( ! (cmd_yy_buffer_stack) )
			CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yyensure_buffer_stack()" );
								  
		memset((cmd_yy_buffer_stack), 0, num_to_alloc * sizeof(struct cmd_yy_buffer_state*));
				
		(cmd_yy_buffer_stack_max) = num_to_alloc;
		(cmd_yy_buffer_stack_top) = 0;
		return;
	}

	if ((cmd_yy_buffer_stack_top) >= ((cmd_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (cmd_yy_buffer_stack_max) + grow_size;
		(cmd_yy_buffer_stack) = (struct cmd_yy_buffer_state**)cmd_yyrealloc
								((cmd_yy_buffer_stack),
								num_to_alloc * sizeof(struct cmd_yy_buffer_state*)
								);
		if ( ! (cmd_yy_buffer_stack) )
			CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((cmd_yy_buffer_stack) + (cmd_yy_buffer_stack_max), 0, grow_size * sizeof(struct cmd_yy_buffer_state*));
		(cmd_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
CMD_YY_BUFFER_STATE cmd_yy_scan_buffer  (char * base, cmd_yy_size_t  size )
{
	CMD_YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != CMD_YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != CMD_YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (CMD_YY_BUFFER_STATE) cmd_yyalloc(sizeof( struct cmd_yy_buffer_state )  );
	if ( ! b )
		CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yy_scan_buffer()" );

	b->cmd_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->cmd_yy_buf_pos = b->cmd_yy_ch_buf = base;
	b->cmd_yy_is_our_buffer = 0;
	b->cmd_yy_input_file = 0;
	b->cmd_yy_n_chars = b->cmd_yy_buf_size;
	b->cmd_yy_is_interactive = 0;
	b->cmd_yy_at_bol = 1;
	b->cmd_yy_fill_buffer = 0;
	b->cmd_yy_buffer_status = CMD_YY_BUFFER_NEW;

	cmd_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cmd_yylex() will
 * scan from a @e copy of @a str.
 * @param cmd_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cmd_yy_scan_bytes() instead.
 */
CMD_YY_BUFFER_STATE cmd_yy_scan_string (cmd_yyconst char * cmd_yystr )
{
    
	return cmd_yy_scan_bytes(cmd_yystr,strlen(cmd_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cmd_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
CMD_YY_BUFFER_STATE cmd_yy_scan_bytes  (cmd_yyconst char * cmd_yybytes, int  _cmd_yybytes_len )
{
	CMD_YY_BUFFER_STATE b;
	char *buf;
	cmd_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _cmd_yybytes_len + 2;
	buf = (char *) cmd_yyalloc(n  );
	if ( ! buf )
		CMD_YY_FATAL_ERROR( "out of dynamic memory in cmd_yy_scan_bytes()" );

	for ( i = 0; i < _cmd_yybytes_len; ++i )
		buf[i] = cmd_yybytes[i];

	buf[_cmd_yybytes_len] = buf[_cmd_yybytes_len+1] = CMD_YY_END_OF_BUFFER_CHAR;

	b = cmd_yy_scan_buffer(buf,n );
	if ( ! b )
		CMD_YY_FATAL_ERROR( "bad buffer in cmd_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->cmd_yy_is_our_buffer = 1;

	return b;
}

#ifndef CMD_YY_EXIT_FAILURE
#define CMD_YY_EXIT_FAILURE 2
#endif

static void cmd_yy_fatal_error (cmd_yyconst char* msg )
{
    	TRACE( "%s\n", msg );
	return;
}

/* Redefine cmd_yyless() so it works in section 3 code. */

#undef cmd_yyless
#define cmd_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cmd_yytext. */ \
        int cmd_yyless_macro_arg = (n); \
        CMD_YY_LESS_LINENO(cmd_yyless_macro_arg);\
		cmd_yytext[cmd_yyleng] = (cmd_yy_hold_char); \
		(cmd_yy_c_buf_p) = cmd_yytext + cmd_yyless_macro_arg; \
		(cmd_yy_hold_char) = *(cmd_yy_c_buf_p); \
		*(cmd_yy_c_buf_p) = '\0'; \
		cmd_yyleng = cmd_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cmd_yyget_lineno  (void)
{
        
    return cmd_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *cmd_yyget_in  (void)
{
        return cmd_yyin;
}

/** Get the output stream.
 * 
 */
FILE *cmd_yyget_out  (void)
{
        return cmd_yyout;
}

/** Get the length of the current token.
 * 
 */
int cmd_yyget_leng  (void)
{
        return cmd_yyleng;
}

/** Get the current token.
 * 
 */

char *cmd_yyget_text  (void)
{
        return cmd_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cmd_yyset_lineno (int  line_number )
{
    
    cmd_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cmd_yy_switch_to_buffer
 */
void cmd_yyset_in (FILE *  in_str )
{
        cmd_yyin = in_str ;
}

void cmd_yyset_out (FILE *  out_str )
{
        cmd_yyout = out_str ;
}

int cmd_yyget_debug  (void)
{
        return cmd_yy_flex_debug;
}

void cmd_yyset_debug (int  bdebug )
{
        cmd_yy_flex_debug = bdebug ;
}

static int cmd_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cmd_yylex_destroy(), so don't allocate here.
     */

    (cmd_yy_buffer_stack) = 0;
    (cmd_yy_buffer_stack_top) = 0;
    (cmd_yy_buffer_stack_max) = 0;
    (cmd_yy_c_buf_p) = (char *) 0;
    (cmd_yy_init) = 0;
    (cmd_yy_start) = 0;

/* Defined in main.c */
#ifdef CMD_YY_STDINIT
    cmd_yyin = stdin;
    cmd_yyout = stdout;
#else
    cmd_yyin = (FILE *) 0;
    cmd_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cmd_yylex_init()
     */
    return 0;
}

/* cmd_yylex_destroy is for both reentrant and non-reentrant scanners. */
int cmd_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(CMD_YY_CURRENT_BUFFER){
		cmd_yy_delete_buffer(CMD_YY_CURRENT_BUFFER  );
		CMD_YY_CURRENT_BUFFER_LVALUE = NULL;
		cmd_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	cmd_yyfree((cmd_yy_buffer_stack) );
	(cmd_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cmd_yylex() is called, initialization will occur. */
    cmd_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef cmd_yytext_ptr
static void cmd_yy_flex_strncpy (char* s1, cmd_yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef CMD_YY_NEED_STRLEN
static int cmd_yy_flex_strlen (cmd_yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cmd_yyalloc (cmd_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cmd_yyrealloc  (void * ptr, cmd_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cmd_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see cmd_yyrealloc() for (char *) cast */
}

#define CMD_YYTABLES_NAME "cmd_yytables"

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

static const char* string_get( char terminal_char )
{
	char c;
	int nchars = 0;

	while (c = cmd_yyinput())
	{
		if (nchars >= (BUFFER_MAX-1))
			break;

		if (c == terminal_char)
			break;
/*
		if (c == '\\')  // the escape-character
		{
			char next_c = cmd_yyinput();
			switch (next_c)
			{
			case 'n':  c = '\n';  break;
			case 't':  c = '\t';  break;
			case '\\': c = '\\';  break;
			case '"':  c = '"';   break;
			default:   c = next_c;  break;
			}
		}
*/
		buffer[nchars] = c;
		++nchars;
	}

	buffer[nchars] = '\0';

	return buffer;
}

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// According to the Bison documentation, the default implementation
// of cmd_yywrap() always returns 1. So, that is what we do too :-)
//
int cmd_yywrap()  { return 1; }

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// 2006.11.26 (PE) -- Introduced this only after much pain & suffering.
// It should be called from cmd_yyerror() after processing the error.
// Prior to introducing this function (and for not well understood reasons)
// the parser would puke on a subsequent statement.
//
//    eg. Given the command sequence
//        admin:prepare:          (pass)
//        a^ttrib:headset: .....  (fail, intentional typo)
//        admin:commit:           (fail, lexer in bad state?)
//
// So, now we force the damn thing to be in a decent state.
// NOTE: The failure of admin:commit: may be the reason why the undo buffer
// quits working (as reported by Jonathan McRight).
//
void cmd_yyForceRestart()  { cmd_yyrestart(cmd_yyin ); }

void CmdLexerTerminate()
{
#if 0
	if (cmd_yy_current_buffer != NULL)
	{
		if (cmd_yy_current_buffer->cmd_yy_ch_buf != NULL)
		{
			free( cmd_yy_current_buffer->cmd_yy_ch_buf );
			cmd_yy_current_buffer->cmd_yy_ch_buf = NULL;
		}

		free( cmd_yy_current_buffer );
		cmd_yy_current_buffer = NULL;
	}
#endif
}

