#ifndef lint
static const char cmd_yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#define CMD_YYBYACC 1
#define CMD_YYMAJOR 1
#define CMD_YYMINOR 9

#define CMD_YYEMPTY        (-1)
#define cmd_yyclearin      (cmd_yychar = CMD_YYEMPTY)
#define cmd_yyerrok        (cmd_yyerrflag = 0)
#define CMD_YYRECOVERING() (cmd_yyerrflag != 0)

#define CMD_YYPREFIX "cmd_yy"

#define CMD_YYPURE 0


/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/
/* BEGIN ** my additions ***/
/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/
/**/
/* NOTE: This source file is was generated by cygwin's byacc.exe*/
/*   i.e. byacc -d -l -o CmdParser.cpp CmdParser.y*/
/**/
/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/

#include "stdafx.h"
#include "cmn_resource.h"
#include "Return.h"
#include "VarList.h"
#include "Command.h"

/* The lexer (of course).*/
extern int cmd_yylex();

/* See also notes at cmd_yyForceRestart().*/
extern void cmd_yyForceRestart();

/* The current token from cmd_yylex(). For use by cmd_yyerror().*/
extern char* cmd_yytext;

/* A forward reference (compiler fodder)*/
int cmd_yyparse();

/* So that cmd_yyerror() can echo the input.*/
const char*	m_input_string;

/* m_cmd_string is the text we are parsing.*/
char*		m_cmd_string;

/* The application's recipient command structure.*/
CCommand*	m_cmd;

/* Transient var for compilation purposes.*/
CVar*		m_var;

#ifdef CMD_YYSTYPE
#undef  CMD_YYSTYPE_IS_DECLARED
#define CMD_YYSTYPE_IS_DECLARED 1
#endif
#ifndef CMD_YYSTYPE_IS_DECLARED
#define CMD_YYSTYPE_IS_DECLARED 1
typedef union
{
	void*	m_void;
	int		m_int;
	double	m_real;
/*	char	m_string[256];  // used char[] to avoid memory management issues!*/
	char	m_string[1024];  /* used char[] to avoid memory management issues!*/
} CMD_YYSTYPE;
#endif /* !CMD_YYSTYPE_IS_DECLARED */

/* compatibility with bison */
#ifdef CMD_YYPARSE_PARAM
/* compatibility with FreeBSD */
# ifdef CMD_YYPARSE_PARAM_TYPE
#  define CMD_YYPARSE_DECL() cmd_yyparse(CMD_YYPARSE_PARAM_TYPE CMD_YYPARSE_PARAM)
# else
#  define CMD_YYPARSE_DECL() cmd_yyparse(void *CMD_YYPARSE_PARAM)
# endif
#else
# define CMD_YYPARSE_DECL() cmd_yyparse(void)
#endif

/* Parameters sent to lex. */
#ifdef CMD_YYLEX_PARAM
# define CMD_YYLEX_DECL() cmd_yylex(void *CMD_YYLEX_PARAM)
# define CMD_YYLEX cmd_yylex(CMD_YYLEX_PARAM)
#else
# define CMD_YYLEX_DECL() cmd_yylex(void)
# define CMD_YYLEX cmd_yylex()
#endif

/* Parameters sent to cmd_yyerror. */
#ifndef CMD_YYERROR_DECL
#define CMD_YYERROR_DECL() cmd_yyerror(const char *s)
#endif
#ifndef CMD_YYERROR_CALL
#define CMD_YYERROR_CALL(msg) cmd_yyerror(msg)
#endif

extern int CMD_YYPARSE_DECL();

#define IDENTIFIER 257
#define STRING 258
#define INT 259
#define REAL 260
#define CMD_YYERRCODE 256
static const short cmd_yylhs[] = {                           -1,
    0,    0,    2,    2,    3,    3,    4,    5,    6,    6,
    7,    7,    1,    1,
};
static const short cmd_yylen[] = {                            2,
    1,    2,    0,    2,    1,    3,    2,    3,    1,    1,
    1,    1,    1,    1,
};
static const short cmd_yydefred[] = {                         3,
    0,    0,    0,    0,    4,    5,    7,    0,    0,   14,
   13,   11,   12,   10,    8,    9,    0,    6,
};
static const short cmd_yydgoto[] = {                          1,
   14,    2,    4,    5,    6,   15,   16,
};
static const short cmd_yysindex[] = {                         0,
    0, -252,  -54,  -38,    0,    0,    0, -257, -249,    0,
    0,    0,    0,    0,    0,    0,  -52,    0,
};
static const short cmd_yyrindex[] = {                         0,
    0,   10,    0,   11,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,
};
static const short cmd_yygindex[] = {                         0,
    0,    0,    0,    0,    3,    0,    0,
};
#define CMD_YYTABLESIZE 12
static const short cmd_yytable[] = {                         10,
   11,   12,   13,    7,    3,    9,    8,   17,    8,    1,
    2,   18,
};
static const short cmd_yycheck[] = {                        257,
  258,  259,  260,   58,  257,   44,   61,  257,   61,    0,
    0,    9,
};
#define CMD_YYFINAL 1
#ifndef CMD_YYDEBUG
#define CMD_YYDEBUG 0
#endif
#define CMD_YYMAXTOKEN 260
#if CMD_YYDEBUG
static const char *cmd_yyname[] = {

"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,"','",0,0,0,0,0,0,0,0,0,0,0,0,0,"':'",0,0,"'='",0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"IDENTIFIER","STRING",
"INT","REAL",
};
static const char *cmd_yyrule[] = {
"$accept : command",
"command : routes",
"command : routes parameters",
"routes :",
"routes : routes route",
"parameters : parameter",
"parameters : parameters ',' parameter",
"route : IDENTIFIER ':'",
"parameter : IDENTIFIER '=' value",
"value : number",
"value : text",
"number : INT",
"number : REAL",
"text : STRING",
"text : IDENTIFIER",

};
#endif

int      cmd_yydebug;
int      cmd_yynerrs;

int      cmd_yyerrflag;
int      cmd_yychar;
CMD_YYSTYPE  cmd_yyval;
CMD_YYSTYPE  cmd_yylval;

/* define the initial stack-sizes */
#ifdef CMD_YYSTACKSIZE
#undef CMD_YYMAXDEPTH
#define CMD_YYMAXDEPTH  CMD_YYSTACKSIZE
#else
#ifdef CMD_YYMAXDEPTH
#define CMD_YYSTACKSIZE CMD_YYMAXDEPTH
#else
#define CMD_YYSTACKSIZE 500
#define CMD_YYMAXDEPTH  500
#endif
#endif

#define CMD_YYINITSTACKSIZE 500

typedef struct {
    unsigned stacksize;
    short    *s_base;
    short    *s_mark;
    short    *s_last;
    CMD_YYSTYPE  *l_base;
    CMD_YYSTYPE  *l_mark;
} CMD_YYSTACKDATA;
/* variables for the parser stack */
static CMD_YYSTACKDATA cmd_yystack;

// ============================================================================

char cmd_getc()
{
	return (*m_cmd_string == 0) ? EOF : (*(m_cmd_string++));
}


int CmdParse( const char* cmd_string, CCommand* cmd_object )
{
	int	status;

	m_input_string = cmd_string;
	m_cmd_string = (char*) cmd_string;
	m_cmd = cmd_object;
	m_var = NULL;

	status = cmd_yyparse();

	return status;
}

void CmdParseTerminate()
{
#if 0
	free( cmd_yyss );
	cmd_yyss = NULL;

	free( cmd_yyvs );
	cmd_yyvs = NULL;
#endif
}

void cmd_yyerror( const char* in_error )
{
	CReturn	status;
	CString	msg;

	msg.Format( "CmdParse() error of <%s> near <%s>", m_input_string, cmd_yytext );
	status.Internal( IDS_INTERNAL_ERROR, msg );
	cmd_yyForceRestart();
}


#if CMD_YYDEBUG
#include <stdio.h>		/* needed for TRACE */
#endif

#include <stdlib.h>	/* needed for malloc, etc */
#include <string.h>	/* needed for memset */

/* allocate initial stack or double stack size, up to CMD_YYMAXDEPTH */
static int cmd_yygrowstack(CMD_YYSTACKDATA *data)
{
    int i;
    unsigned newsize;
    short *newss;
    CMD_YYSTYPE *newvs;

    if ((newsize = data->stacksize) == 0)
        newsize = CMD_YYINITSTACKSIZE;
    else if (newsize >= CMD_YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > CMD_YYMAXDEPTH)
        newsize = CMD_YYMAXDEPTH;

    i = data->s_mark - data->s_base;
    newss = (short *)realloc(data->s_base, newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    data->s_base = newss;
    data->s_mark = newss + i;

    newvs = (CMD_YYSTYPE *)realloc(data->l_base, newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    data->l_base = newvs;
    data->l_mark = newvs + i;

    data->stacksize = newsize;
    data->s_last = data->s_base + newsize - 1;
    return 0;
}

#if CMD_YYPURE || defined(CMD_YY_NO_LEAKS)
static void cmd_yyfreestack(CMD_YYSTACKDATA *data)
{
    free(data->s_base);
    free(data->l_base);
    memset(data, 0, sizeof(*data));
}
#else
#define cmd_yyfreestack(data) /* nothing */
#endif

#define CMD_YYABORT  goto cmd_yyabort
#define CMD_YYREJECT goto cmd_yyabort
#define CMD_YYACCEPT goto cmd_yyaccept
#define CMD_YYERROR  goto cmd_yyerrlab

int
CMD_YYPARSE_DECL()
{
    int cmd_yym, cmd_yyn, cmd_yystate;
#if CMD_YYDEBUG
    const char *cmd_yys;

    if ((cmd_yys = getenv("CMD_YYDEBUG")) != 0)
    {
        cmd_yyn = *cmd_yys;
        if (cmd_yyn >= '0' && cmd_yyn <= '9')
            cmd_yydebug = cmd_yyn - '0';
    }
#endif

    cmd_yynerrs = 0;
    cmd_yyerrflag = 0;
    cmd_yychar = CMD_YYEMPTY;
    cmd_yystate = 0;

#if CMD_YYPURE
    memset(&cmd_yystack, 0, sizeof(cmd_yystack));
#endif

    if (cmd_yystack.s_base == NULL && cmd_yygrowstack(&cmd_yystack)) goto cmd_yyoverflow;
    cmd_yystack.s_mark = cmd_yystack.s_base;
    cmd_yystack.l_mark = cmd_yystack.l_base;
    cmd_yystate = 0;
    *cmd_yystack.s_mark = 0;

cmd_yyloop:
    if ((cmd_yyn = cmd_yydefred[cmd_yystate]) != 0) goto cmd_yyreduce;
    if (cmd_yychar < 0)
    {
        if ((cmd_yychar = CMD_YYLEX) < 0) cmd_yychar = 0;
#if CMD_YYDEBUG
        if (cmd_yydebug)
        {
            cmd_yys = 0;
            if (cmd_yychar <= CMD_YYMAXTOKEN) cmd_yys = cmd_yyname[cmd_yychar];
            if (!cmd_yys) cmd_yys = "illegal-symbol";
            TRACE("%sdebug: state %d, reading %d (%s)\n",
                    CMD_YYPREFIX, cmd_yystate, cmd_yychar, cmd_yys);
        }
#endif
    }
    if ((cmd_yyn = cmd_yysindex[cmd_yystate]) && (cmd_yyn += cmd_yychar) >= 0 &&
            cmd_yyn <= CMD_YYTABLESIZE && cmd_yycheck[cmd_yyn] == cmd_yychar)
    {
#if CMD_YYDEBUG
        if (cmd_yydebug)
            TRACE("%sdebug: state %d, shifting to state %d\n",
                    CMD_YYPREFIX, cmd_yystate, cmd_yytable[cmd_yyn]);
#endif
        if (cmd_yystack.s_mark >= cmd_yystack.s_last && cmd_yygrowstack(&cmd_yystack))
        {
            goto cmd_yyoverflow;
        }
        cmd_yystate = cmd_yytable[cmd_yyn];
        *++cmd_yystack.s_mark = cmd_yytable[cmd_yyn];
        *++cmd_yystack.l_mark = cmd_yylval;
        cmd_yychar = CMD_YYEMPTY;
        if (cmd_yyerrflag > 0)  --cmd_yyerrflag;
        goto cmd_yyloop;
    }
    if ((cmd_yyn = cmd_yyrindex[cmd_yystate]) && (cmd_yyn += cmd_yychar) >= 0 &&
            cmd_yyn <= CMD_YYTABLESIZE && cmd_yycheck[cmd_yyn] == cmd_yychar)
    {
        cmd_yyn = cmd_yytable[cmd_yyn];
        goto cmd_yyreduce;
    }
    if (cmd_yyerrflag) goto cmd_yyinrecovery;

    cmd_yyerror("syntax error");

    goto cmd_yyerrlab;

cmd_yyerrlab:
    ++cmd_yynerrs;

cmd_yyinrecovery:
    if (cmd_yyerrflag < 3)
    {
        cmd_yyerrflag = 3;
        for (;;)
        {
            if ((cmd_yyn = cmd_yysindex[*cmd_yystack.s_mark]) && (cmd_yyn += CMD_YYERRCODE) >= 0 &&
                    cmd_yyn <= CMD_YYTABLESIZE && cmd_yycheck[cmd_yyn] == CMD_YYERRCODE)
            {
#if CMD_YYDEBUG
                if (cmd_yydebug)
                    TRACE("%sdebug: state %d, error recovery shifting\
 to state %d\n", CMD_YYPREFIX, *cmd_yystack.s_mark, cmd_yytable[cmd_yyn]);
#endif
                if (cmd_yystack.s_mark >= cmd_yystack.s_last && cmd_yygrowstack(&cmd_yystack))
                {
                    goto cmd_yyoverflow;
                }
                cmd_yystate = cmd_yytable[cmd_yyn];
                *++cmd_yystack.s_mark = cmd_yytable[cmd_yyn];
                *++cmd_yystack.l_mark = cmd_yylval;
                goto cmd_yyloop;
            }
            else
            {
#if CMD_YYDEBUG
                if (cmd_yydebug)
                    TRACE("%sdebug: error recovery discarding state %d\n",
                            CMD_YYPREFIX, *cmd_yystack.s_mark);
#endif
                if (cmd_yystack.s_mark <= cmd_yystack.s_base) goto cmd_yyabort;
                --cmd_yystack.s_mark;
                --cmd_yystack.l_mark;
            }
        }
    }
    else
    {
        if (cmd_yychar == 0) goto cmd_yyabort;
#if CMD_YYDEBUG
        if (cmd_yydebug)
        {
            cmd_yys = 0;
            if (cmd_yychar <= CMD_YYMAXTOKEN) cmd_yys = cmd_yyname[cmd_yychar];
            if (!cmd_yys) cmd_yys = "illegal-symbol";
            TRACE("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    CMD_YYPREFIX, cmd_yystate, cmd_yychar, cmd_yys);
        }
#endif
        cmd_yychar = CMD_YYEMPTY;
        goto cmd_yyloop;
    }

cmd_yyreduce:
#if CMD_YYDEBUG
    if (cmd_yydebug)
        TRACE("%sdebug: state %d, reducing by rule %d (%s)\n",
                CMD_YYPREFIX, cmd_yystate, cmd_yyn, cmd_yyrule[cmd_yyn]);
#endif
    cmd_yym = cmd_yylen[cmd_yyn];
    if (cmd_yym)
        cmd_yyval = cmd_yystack.l_mark[1-cmd_yym];
    else
        memset(&cmd_yyval, 0, sizeof cmd_yyval);
    switch (cmd_yyn)
    {
case 7:
	{ 
										m_cmd->add_route( cmd_yystack.l_mark[-1].m_string ); 
									}
break;
case 8:
	{
										if (m_var)
										{
											m_var->setName( cmd_yystack.l_mark[-2].m_string );

											/**/
											/* There must be better ways... */
											/**/
											/*
											if (dynamic_cast<CVarInt*>(m_var))
												m_cmd->setInt( m_var->getName(), m_var->getInt() );
											else
											if (dynamic_cast<CVarReal*>(m_var))
												m_cmd->setReal( m_var->getName(), m_var->getReal() );
											else
											if (dynamic_cast<CVarString*>(m_var))
												m_cmd->setString( m_var->getName(), m_var->getString() );
											*/
											m_cmd->setString( m_var->getName(), m_var->getString() );

											delete m_var; m_var = NULL;
										}
									}
break;
case 10:
	{ 
										if (cmd_yystack.l_mark[0].m_string)
										{
											if (m_var) delete m_var;
											m_var = new CVarString;
											m_var->setString( cmd_yystack.l_mark[0].m_string );
										}
									}
break;
case 11:
	{
										if (m_var) delete m_var;
										/*
										m_var = new CVarInt;
										m_var->setInt( $1 );
										*/
										CString tmp;
										tmp.Format( "%d", cmd_yystack.l_mark[0].m_int );
										m_var = new CVarString;
										m_var->setString( tmp );
									}
break;
case 12:
	{
										if (m_var) delete m_var;
										/*
										m_var = new CVarReal;
										m_var->setReal( $1 );
										*/
										/* 2005.12.17 (PE) -- changed format from %f to %-14.7f because*/
										/* precision was being lost, causing trim/extend to fail.*/
										CString tmp;
										tmp.Format( "%-14.7f", cmd_yystack.l_mark[0].m_real );
										m_var = new CVarString;
										m_var->setString( tmp );
									}
break;
    }
    cmd_yystack.s_mark -= cmd_yym;
    cmd_yystate = *cmd_yystack.s_mark;
    cmd_yystack.l_mark -= cmd_yym;
    cmd_yym = cmd_yylhs[cmd_yyn];
    if (cmd_yystate == 0 && cmd_yym == 0)
    {
#if CMD_YYDEBUG
        if (cmd_yydebug)
            TRACE("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", CMD_YYPREFIX, CMD_YYFINAL);
#endif
        cmd_yystate = CMD_YYFINAL;
        *++cmd_yystack.s_mark = CMD_YYFINAL;
        *++cmd_yystack.l_mark = cmd_yyval;
        if (cmd_yychar < 0)
        {
            if ((cmd_yychar = CMD_YYLEX) < 0) cmd_yychar = 0;
#if CMD_YYDEBUG
            if (cmd_yydebug)
            {
                cmd_yys = 0;
                if (cmd_yychar <= CMD_YYMAXTOKEN) cmd_yys = cmd_yyname[cmd_yychar];
                if (!cmd_yys) cmd_yys = "illegal-symbol";
                TRACE("%sdebug: state %d, reading %d (%s)\n",
                        CMD_YYPREFIX, CMD_YYFINAL, cmd_yychar, cmd_yys);
            }
#endif
        }
        if (cmd_yychar == 0) goto cmd_yyaccept;
        goto cmd_yyloop;
    }
    if ((cmd_yyn = cmd_yygindex[cmd_yym]) && (cmd_yyn += cmd_yystate) >= 0 &&
            cmd_yyn <= CMD_YYTABLESIZE && cmd_yycheck[cmd_yyn] == cmd_yystate)
        cmd_yystate = cmd_yytable[cmd_yyn];
    else
        cmd_yystate = cmd_yydgoto[cmd_yym];
#if CMD_YYDEBUG
    if (cmd_yydebug)
        TRACE("%sdebug: after reduction, shifting from state %d \
to state %d\n", CMD_YYPREFIX, *cmd_yystack.s_mark, cmd_yystate);
#endif
    if (cmd_yystack.s_mark >= cmd_yystack.s_last && cmd_yygrowstack(&cmd_yystack))
    {
        goto cmd_yyoverflow;
    }
    *++cmd_yystack.s_mark = (short) cmd_yystate;
    *++cmd_yystack.l_mark = cmd_yyval;
    goto cmd_yyloop;

cmd_yyoverflow:
    cmd_yyerror("yacc stack overflow");

cmd_yyabort:
    cmd_yyfreestack(&cmd_yystack);
    return (1);

cmd_yyaccept:
    cmd_yyfreestack(&cmd_yystack);
    return (0);
}
