
%{

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// BEGIN ** my additions **
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// NOTE: This source file is was generated by cygwin's byacc.exe
//   i.e. byacc -d -l -o CmdParser.cpp CmdParser.y
//
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#include "stdafx.h"
#include "cmn_resource.h"
#include "Return.h"
#include "VarList.h"
#include "Command.h"

// The lexer (of course).
extern int yylex();

// See also notes at yyForceRestart().
extern void yyForceRestart();

// The current token from yylex(). For use by yyerror().
extern char* yytext;

// A forward reference (compiler fodder)
int yyparse();

// So that yyerror() can echo the input.
const char*	m_input_string;

// m_cmd_string is the text we are parsing.
char*		m_cmd_string;

// The application's recipient command structure.
CCommand*	m_cmd;

// Transient var for compilation purposes.
CVar*		m_var;

%}

%union
{
	void*	m_void;
	int		m_int;
	double	m_real;
//	char	m_string[256];  // used char[] to avoid memory management issues!
	char	m_string[1024];  // used char[] to avoid memory management issues!
}

%token <m_string>	IDENTIFIER
%token <m_string>	STRING
%token <m_int>		INT
%token <m_real>		REAL

%type <m_string>	text

//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// END ** my additions **
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// NOTE: This comment does not appear in the generated file!
//
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

%%

// ============================================================================
//		command
//
//
command:
	routes 
	| routes parameters
	;

routes:
	| routes route
	;

parameters:
	parameter
	| parameters ',' parameter
	;

route:
	IDENTIFIER ':'					{ 
										m_cmd->add_route( $1 ); 
									}
	;

parameter:
	IDENTIFIER '=' value			{
										if (m_var)
										{
											m_var->setName( $1 );

											//
											// There must be better ways... 
											//
											/*
											if (dynamic_cast<CVarInt*>(m_var))
												m_cmd->setInt( m_var->getName(), m_var->getInt() );
											else
											if (dynamic_cast<CVarReal*>(m_var))
												m_cmd->setReal( m_var->getName(), m_var->getReal() );
											else
											if (dynamic_cast<CVarString*>(m_var))
												m_cmd->setString( m_var->getName(), m_var->getString() );
											*/
											m_cmd->setString( m_var->getName(), m_var->getString() );

											delete m_var; m_var = NULL;
										}
									}
	;

value:
	number
	| text							{ 
										if ($1)
										{
											if (m_var) delete m_var;
											m_var = new CVarString;
											m_var->setString( $1 );
										}
									}
	;

number:
	INT								{
										if (m_var) delete m_var;
										/*
										m_var = new CVarInt;
										m_var->setInt( $1 );
										*/
										CString tmp;
										tmp.Format( "%d", $1 );
										m_var = new CVarString;
										m_var->setString( tmp );
									}
	| REAL							{
										if (m_var) delete m_var;
										/*
										m_var = new CVarReal;
										m_var->setReal( $1 );
										*/
										// 2005.12.17 (PE) -- changed format from %f to %-14.7f because
										// precision was being lost, causing trim/extend to fail.
										CString tmp;
										tmp.Format( "%-14.7f", $1 );
										m_var = new CVarString;
										m_var->setString( tmp );
									}
	;

text:
	STRING
	| IDENTIFIER
	;

%%

// ============================================================================

char cmd_getc()
{
	return (*m_cmd_string == 0) ? EOF : (*(m_cmd_string++));
}


int CmdParse( const char* cmd_string, CCommand* cmd_object )
{
	int	status;

	m_input_string = cmd_string;
	m_cmd_string = (char*) cmd_string;
	m_cmd = cmd_object;
	m_var = NULL;

	status = yyparse();

	return status;
}

void CmdParseTerminate()
{
#if 0
	free( yyss );
	yyss = NULL;

	free( yyvs );
	yyvs = NULL;
#endif
}

void yyerror( const char* in_error )
{
	CReturn	status;
	CString	msg;

	msg.Format( "CmdParse() error of <%s> near <%s>", m_input_string, yytext );
	status.Internal( IDS_INTERNAL_ERROR, msg );
	yyForceRestart();
}

