#ifndef lint
static const char exp_yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#define EXP_YYBYACC 1
#define EXP_YYMAJOR 1
#define EXP_YYMINOR 9

#define EXP_YYEMPTY        (-1)
#define exp_yyclearin      (exp_yychar = EXP_YYEMPTY)
#define exp_yyerrok        (exp_yyerrflag = 0)
#define EXP_YYRECOVERING() (exp_yyerrflag != 0)

#define EXP_YYPREFIX "exp_yy"

#define EXP_YYPURE 0


/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/
/* BEGIN ** my additions ***/
/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/
/**/
/* NOTE: This source file is was generated by cygwin's byacc.exe*/
/*   i.e. byacc -d -l -o CmdParser.cpp CmdParser.y*/
/**/
/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/

#include "stdafx.h"
#include <math.h>
#include "MathConst.h"
#include "cmn_resource.h"
#include "Return.h"

/* The lexer (of course).*/
extern int exp_yylex();

/* See also notes at exp_yyForceRestart().*/
extern void exp_yyForceRestart();

/* A forward reference (compiler fodder)*/
int exp_yyparse();

/* m_expression is the text we are parsing.*/
char*	m_expression;
double	m_value;
#ifdef EXP_YYSTYPE
#undef  EXP_YYSTYPE_IS_DECLARED
#define EXP_YYSTYPE_IS_DECLARED 1
#endif
#ifndef EXP_YYSTYPE_IS_DECLARED
#define EXP_YYSTYPE_IS_DECLARED 1
typedef union
{
	int		m_int;
	double	m_real;
} EXP_YYSTYPE;
#endif /* !EXP_YYSTYPE_IS_DECLARED */

/* compatibility with bison */
#ifdef EXP_YYPARSE_PARAM
/* compatibility with FreeBSD */
# ifdef EXP_YYPARSE_PARAM_TYPE
#  define EXP_YYPARSE_DECL() exp_yyparse(EXP_YYPARSE_PARAM_TYPE EXP_YYPARSE_PARAM)
# else
#  define EXP_YYPARSE_DECL() exp_yyparse(void *EXP_YYPARSE_PARAM)
# endif
#else
# define EXP_YYPARSE_DECL() exp_yyparse(void)
#endif

/* Parameters sent to lex. */
#ifdef EXP_YYLEX_PARAM
# define EXP_YYLEX_DECL() exp_yylex(void *EXP_YYLEX_PARAM)
# define EXP_YYLEX exp_yylex(EXP_YYLEX_PARAM)
#else
# define EXP_YYLEX_DECL() exp_yylex(void)
# define EXP_YYLEX exp_yylex()
#endif

/* Parameters sent to exp_yyerror. */
#ifndef EXP_YYERROR_DECL
#define EXP_YYERROR_DECL() exp_yyerror(const char *s)
#endif
#ifndef EXP_YYERROR_CALL
#define EXP_YYERROR_CALL(msg) exp_yyerror(msg)
#endif

extern int EXP_YYPARSE_DECL();

#define DECINT 257
#define HEXINT 258
#define REAL 259
#define OP_EQ 260
#define OP_LE 261
#define OP_GE 262
#define OP_LT 263
#define OP_GT 264
#define OP_NE 265
#define OP_AND 266
#define OP_OR 267
#define OP_XOR 268
#define OP_MIN 269
#define OP_MAX 270
#define OP_LSHIFT 271
#define OP_RSHIFT 272
#define OP_SIN 273
#define OP_COS 274
#define OP_TAN 275
#define OP_ASIN 276
#define OP_ACOS 277
#define OP_ATAN 278
#define OP_RAD 279
#define OP_DEG 280
#define OP_NOT 281
#define UMINUS 282
#define EXP_YYERRCODE 256
static const short exp_yylhs[] = {                           -1,
    0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    2,    2,    3,    3,
};
static const short exp_yylen[] = {                            2,
    1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
    3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
    3,    2,    2,    2,    1,    1,    1,    1,    1,
};
static const short exp_yydefred[] = {                         0,
   38,   39,   37,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,   35,   36,   32,
    0,    0,    0,    0,    0,    0,    0,    0,   34,    0,
   33,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
   31,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    7,
    8,    9,   26,   27,   28,   23,   24,   25,   30,   29,
};
static const short exp_yydgoto[] = {                         16,
   17,   18,   19,
};
static const short exp_yysindex[] = {                       -40,
    0,    0,    0,  -40,  -38,  -33,  -31,  -28,  -23,  -21,
  -19,  -18,  -40,  -40,  -40,    0,  512,    0,    0,    0,
  -40,  -40,  -40,  -40,  -40,  -40,  -40,  -40,    0,  -12,
    0,  -40,  -40,  -40,  -40,  -40,  -40,  -40,  -40,  -40,
  -40,  -40,  -40,  -40,  -40,  -40,  -40,  -40,  -40,  -40,
  -40,  -40,  403,  416,  429,  442,  457,  470,  483,  496,
    0,  525,  525,  525,  525,  525,  525,  -27,  -27,  -27,
  -27,  -27,  537,  537,  -34,  -34,  -32,  -32,  -32,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
};
static const short exp_yyrindex[] = {                         0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,   23,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,  143,  149,  155,  161,  167,  174,   66,   77,   88,
   99,  110,  121,  132,   40,   53,    1,   14,   27,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
};
static const short exp_yygindex[] = {                         0,
  785,    0,    0,
};
#define EXP_YYTABLESIZE 837
static const short exp_yytable[] = {                         14,
    4,   21,   49,   50,    4,   50,   22,   47,   23,   49,
   50,   24,   48,    5,   47,   45,   25,   46,   26,   48,
   27,   28,    1,    0,   49,   50,    6,    0,   61,   47,
   45,    0,   46,    0,   48,    0,    0,    4,    0,    2,
    0,    4,    4,    4,    0,    4,    0,    4,    0,    0,
    5,    0,    3,    0,    5,    5,    5,    0,    5,   52,
    5,   52,    0,    6,    0,   10,   52,    6,    6,    6,
    0,    6,    0,    6,    0,    0,   11,    0,    0,    0,
    2,   52,    2,    0,    2,   15,    0,   12,    0,   51,
    0,   51,    0,    3,    0,    3,   51,    3,   13,    0,
    0,    0,    0,    0,    0,    0,   10,    0,    0,   14,
    0,   51,    0,    0,    0,    0,    0,   11,    0,    0,
   21,    0,    0,    0,    0,    0,    0,    0,   12,    0,
    0,   22,    0,    0,    0,    0,    0,    0,    0,   13,
    0,    0,   15,    0,    0,    0,    0,    0,   16,    0,
   14,    0,    0,    0,   17,    0,    0,    0,    0,    0,
   18,   21,    0,    0,    0,    0,   19,    0,    0,    0,
    0,    0,   22,   20,    0,    0,    0,    0,    0,    0,
    0,    0,    0,   15,    0,    0,    0,    0,    0,   16,
    0,    0,    0,    0,    0,   17,    0,    0,    0,    0,
    0,   18,    0,    0,    0,    0,    0,   19,    0,    0,
    0,    0,    0,    0,   20,    0,    1,    2,    3,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    5,    6,    7,    8,    9,   10,   11,   12,
   13,    0,    0,   43,   44,    0,    0,   32,   33,   34,
   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
    4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
    5,    5,    5,    5,    5,    5,    6,    6,    6,    6,
    6,    6,    6,    6,    6,    6,    6,    6,    6,    2,
    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
    2,    2,    3,    3,    3,    3,    3,    3,    3,    3,
    3,    3,    3,    3,    3,   10,   10,   10,   10,   10,
   10,   10,   10,   10,   10,   10,   11,   11,   11,   11,
   11,   11,   11,   11,   11,   11,   11,   12,   12,   12,
   12,   12,   12,   12,   12,   12,   12,   12,   13,   13,
   13,   13,   13,   13,   13,   13,   13,   13,   13,   14,
   14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
   21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
   21,   22,   22,   22,   22,   22,   22,   22,   22,   22,
   22,   22,   15,   15,   15,   15,   15,   15,   16,   16,
   16,   16,   16,   16,   17,   17,   17,   17,   17,   17,
   18,   18,   18,   18,   18,   18,   19,   19,   19,   19,
   19,   19,    0,   20,   20,   20,   20,   20,   20,   49,
   50,    0,    0,   83,   47,   45,    0,   46,    0,   48,
    0,    0,   49,   50,    0,    0,   84,   47,   45,    0,
   46,    0,   48,    0,    0,   49,   50,    0,    0,   85,
   47,   45,    0,   46,    0,   48,    0,    0,   49,   50,
    0,    0,   86,   47,   45,    0,   46,    0,   48,    0,
    0,    0,    0,   49,   50,    0,   52,   87,   47,   45,
    0,   46,    0,   48,    0,    0,   49,   50,    0,   52,
   88,   47,   45,    0,   46,    0,   48,    0,    0,   49,
   50,    0,   52,   89,   47,   45,   51,   46,    0,   48,
    0,    0,   49,   50,    0,   52,   90,   47,   45,   51,
   46,    0,   48,    0,    0,    0,    0,    0,   49,   50,
   52,    0,   51,   47,   45,    0,   46,    0,   48,    0,
    0,   49,   50,   52,    0,   51,   47,   45,    0,   46,
    0,   48,    0,   49,   50,    0,   52,    0,   47,   45,
   51,   46,    0,   48,    0,    0,    0,    0,    0,   52,
    0,    0,    0,   51,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,   52,   51,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,   52,   51,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
   52,    0,    0,    0,    0,   51,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,   51,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
   51,    0,   32,   33,   34,   35,   36,   37,   38,   39,
   40,   41,   42,   43,   44,   32,   33,   34,   35,   36,
   37,   38,   39,   40,   41,   42,   43,   44,   32,   33,
   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
   44,   32,   33,   34,   35,   36,   37,   38,   39,   40,
   41,   42,   43,   44,    0,    0,   32,   33,   34,   35,
   36,   37,   38,   39,   40,   41,   42,   43,   44,   32,
   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
   43,   44,   32,   33,   34,   35,   36,   37,   38,   39,
   40,   41,   42,   43,   44,   32,   33,   34,   35,   36,
   37,   38,   39,   40,   41,   42,   43,   44,    0,    0,
    0,   32,   33,   34,   35,   36,   37,   38,   39,   40,
   41,   42,   43,   44,    0,    0,    0,    0,   20,    0,
   38,   39,   40,   41,   42,   43,   44,   29,   30,   31,
    0,    0,    0,    0,    0,   53,   54,   55,   56,   57,
   58,   59,   60,    0,    0,    0,   62,   63,   64,   65,
   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
   76,   77,   78,   79,   80,   81,   82,
};
static const short exp_yycheck[] = {                         40,
    0,   40,   37,   38,   45,   38,   40,   42,   40,   37,
   38,   40,   47,    0,   42,   43,   40,   45,   40,   47,
   40,   40,    0,   -1,   37,   38,    0,   -1,   41,   42,
   43,   -1,   45,   -1,   47,   -1,   -1,   37,   -1,    0,
   -1,   41,   42,   43,   -1,   45,   -1,   47,   -1,   -1,
   37,   -1,    0,   -1,   41,   42,   43,   -1,   45,   94,
   47,   94,   -1,   37,   -1,    0,   94,   41,   42,   43,
   -1,   45,   -1,   47,   -1,   -1,    0,   -1,   -1,   -1,
   41,   94,   43,   -1,   45,  126,   -1,    0,   -1,  124,
   -1,  124,   -1,   41,   -1,   43,  124,   45,    0,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   41,   -1,   -1,    0,
   -1,  124,   -1,   -1,   -1,   -1,   -1,   41,   -1,   -1,
    0,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   41,   -1,
   -1,    0,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   41,
   -1,   -1,    0,   -1,   -1,   -1,   -1,   -1,    0,   -1,
   41,   -1,   -1,   -1,    0,   -1,   -1,   -1,   -1,   -1,
    0,   41,   -1,   -1,   -1,   -1,    0,   -1,   -1,   -1,
   -1,   -1,   41,    0,   -1,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,   -1,   41,   -1,   -1,   -1,   -1,   -1,   41,
   -1,   -1,   -1,   -1,   -1,   41,   -1,   -1,   -1,   -1,
   -1,   41,   -1,   -1,   -1,   -1,   -1,   41,   -1,   -1,
   -1,   -1,   -1,   -1,   41,   -1,  257,  258,  259,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,  273,  274,  275,  276,  277,  278,  279,  280,
  281,   -1,   -1,  271,  272,   -1,   -1,  260,  261,  262,
  263,  264,  265,  266,  267,  268,  269,  270,  271,  272,
  260,  261,  262,  263,  264,  265,  266,  267,  268,  269,
  270,  271,  272,  260,  261,  262,  263,  264,  265,  266,
  267,  268,  269,  270,  271,  272,  260,  261,  262,  263,
  264,  265,  266,  267,  268,  269,  270,  271,  272,  260,
  261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
  271,  272,  260,  261,  262,  263,  264,  265,  266,  267,
  268,  269,  270,  271,  272,  260,  261,  262,  263,  264,
  265,  266,  267,  268,  269,  270,  260,  261,  262,  263,
  264,  265,  266,  267,  268,  269,  270,  260,  261,  262,
  263,  264,  265,  266,  267,  268,  269,  270,  260,  261,
  262,  263,  264,  265,  266,  267,  268,  269,  270,  260,
  261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
  260,  261,  262,  263,  264,  265,  266,  267,  268,  269,
  270,  260,  261,  262,  263,  264,  265,  266,  267,  268,
  269,  270,  260,  261,  262,  263,  264,  265,  260,  261,
  262,  263,  264,  265,  260,  261,  262,  263,  264,  265,
  260,  261,  262,  263,  264,  265,  260,  261,  262,  263,
  264,  265,   -1,  260,  261,  262,  263,  264,  265,   37,
   38,   -1,   -1,   41,   42,   43,   -1,   45,   -1,   47,
   -1,   -1,   37,   38,   -1,   -1,   41,   42,   43,   -1,
   45,   -1,   47,   -1,   -1,   37,   38,   -1,   -1,   41,
   42,   43,   -1,   45,   -1,   47,   -1,   -1,   37,   38,
   -1,   -1,   41,   42,   43,   -1,   45,   -1,   47,   -1,
   -1,   -1,   -1,   37,   38,   -1,   94,   41,   42,   43,
   -1,   45,   -1,   47,   -1,   -1,   37,   38,   -1,   94,
   41,   42,   43,   -1,   45,   -1,   47,   -1,   -1,   37,
   38,   -1,   94,   41,   42,   43,  124,   45,   -1,   47,
   -1,   -1,   37,   38,   -1,   94,   41,   42,   43,  124,
   45,   -1,   47,   -1,   -1,   -1,   -1,   -1,   37,   38,
   94,   -1,  124,   42,   43,   -1,   45,   -1,   47,   -1,
   -1,   37,   38,   94,   -1,  124,   42,   43,   -1,   45,
   -1,   47,   -1,   37,   38,   -1,   94,   -1,   42,   43,
  124,   45,   -1,   47,   -1,   -1,   -1,   -1,   -1,   94,
   -1,   -1,   -1,  124,   -1,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   94,  124,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   94,  124,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
   94,   -1,   -1,   -1,   -1,  124,   -1,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  124,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
  124,   -1,  260,  261,  262,  263,  264,  265,  266,  267,
  268,  269,  270,  271,  272,  260,  261,  262,  263,  264,
  265,  266,  267,  268,  269,  270,  271,  272,  260,  261,
  262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
  272,  260,  261,  262,  263,  264,  265,  266,  267,  268,
  269,  270,  271,  272,   -1,   -1,  260,  261,  262,  263,
  264,  265,  266,  267,  268,  269,  270,  271,  272,  260,
  261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
  271,  272,  260,  261,  262,  263,  264,  265,  266,  267,
  268,  269,  270,  271,  272,  260,  261,  262,  263,  264,
  265,  266,  267,  268,  269,  270,  271,  272,   -1,   -1,
   -1,  260,  261,  262,  263,  264,  265,  266,  267,  268,
  269,  270,  271,  272,   -1,   -1,   -1,   -1,    4,   -1,
  266,  267,  268,  269,  270,  271,  272,   13,   14,   15,
   -1,   -1,   -1,   -1,   -1,   21,   22,   23,   24,   25,
   26,   27,   28,   -1,   -1,   -1,   32,   33,   34,   35,
   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
   46,   47,   48,   49,   50,   51,   52,
};
#define EXP_YYFINAL 16
#ifndef EXP_YYDEBUG
#define EXP_YYDEBUG 0
#endif
#define EXP_YYMAXTOKEN 282
#if EXP_YYDEBUG
static const char *exp_yyname[] = {

"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,"'%'","'&'",0,"'('","')'","'*'","'+'",0,"'-'",0,"'/'",0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"'^'",0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"'|'",0,"'~'",0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,"DECINT","HEXINT","REAL","OP_EQ","OP_LE","OP_GE","OP_LT","OP_GT",
"OP_NE","OP_AND","OP_OR","OP_XOR","OP_MIN","OP_MAX","OP_LSHIFT","OP_RSHIFT",
"OP_SIN","OP_COS","OP_TAN","OP_ASIN","OP_ACOS","OP_ATAN","OP_RAD","OP_DEG",
"OP_NOT","UMINUS",
};
static const char *exp_yyrule[] = {
"$accept : main",
"main : expression",
"expression : expression '+' expression",
"expression : expression '-' expression",
"expression : expression '*' expression",
"expression : expression '/' expression",
"expression : expression '%' expression",
"expression : expression '&' expression",
"expression : expression '|' expression",
"expression : expression '^' expression",
"expression : expression OP_AND expression",
"expression : expression OP_OR expression",
"expression : expression OP_XOR expression",
"expression : expression OP_MIN expression",
"expression : expression OP_MAX expression",
"expression : expression OP_EQ expression",
"expression : expression OP_LE expression",
"expression : expression OP_GE expression",
"expression : expression OP_LT expression",
"expression : expression OP_GT expression",
"expression : expression OP_NE expression",
"expression : expression OP_LSHIFT expression",
"expression : expression OP_RSHIFT expression",
"expression : OP_ASIN '(' expression ')'",
"expression : OP_ACOS '(' expression ')'",
"expression : OP_ATAN '(' expression ')'",
"expression : OP_SIN '(' expression ')'",
"expression : OP_COS '(' expression ')'",
"expression : OP_TAN '(' expression ')'",
"expression : OP_DEG '(' expression ')'",
"expression : OP_RAD '(' expression ')'",
"expression : '(' expression ')'",
"expression : '-' expression",
"expression : '~' expression",
"expression : OP_NOT expression",
"expression : number",
"number : integer",
"number : REAL",
"integer : DECINT",
"integer : HEXINT",

};
#endif

int      exp_yydebug;
int      exp_yynerrs;

int      exp_yyerrflag;
int      exp_yychar;
EXP_YYSTYPE  exp_yyval;
EXP_YYSTYPE  exp_yylval;

/* define the initial stack-sizes */
#ifdef EXP_YYSTACKSIZE
#undef EXP_YYMAXDEPTH
#define EXP_YYMAXDEPTH  EXP_YYSTACKSIZE
#else
#ifdef EXP_YYMAXDEPTH
#define EXP_YYSTACKSIZE EXP_YYMAXDEPTH
#else
#define EXP_YYSTACKSIZE 500
#define EXP_YYMAXDEPTH  500
#endif
#endif

#define EXP_YYINITSTACKSIZE 500

typedef struct {
    unsigned stacksize;
    short    *s_base;
    short    *s_mark;
    short    *s_last;
    EXP_YYSTYPE  *l_base;
    EXP_YYSTYPE  *l_mark;
} EXP_YYSTACKDATA;
/* variables for the parser stack */
static EXP_YYSTACKDATA exp_yystack;

// ============================================================================

int ExpParse( const char* expression )
{
	int	status;

	m_value = UNDEFINED;

	m_expression = (char*) expression;

	status = exp_yyparse();

	return status;
}

double ExpParseValueGet()
{
	return m_value;
}

void exp_yyerror( const char* in_error )
{
	CReturn	status;

	// TODO:  Replace with *real* error handling
	//   MessageBox( NULL, in_error, NULL, MB_OK );
	status.Internal( IDS_INTERNAL_ERROR, in_error );

	exp_yyForceRestart();
}


#if EXP_YYDEBUG
#include <stdio.h>		/* needed for TRACE */
#endif

#include <stdlib.h>	/* needed for malloc, etc */
#include <string.h>	/* needed for memset */

/* allocate initial stack or double stack size, up to EXP_YYMAXDEPTH */
static int exp_yygrowstack(EXP_YYSTACKDATA *data)
{
    int i;
    unsigned newsize;
    short *newss;
    EXP_YYSTYPE *newvs;

    if ((newsize = data->stacksize) == 0)
        newsize = EXP_YYINITSTACKSIZE;
    else if (newsize >= EXP_YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > EXP_YYMAXDEPTH)
        newsize = EXP_YYMAXDEPTH;

    i = data->s_mark - data->s_base;
    newss = (short *)realloc(data->s_base, newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    data->s_base = newss;
    data->s_mark = newss + i;

    newvs = (EXP_YYSTYPE *)realloc(data->l_base, newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    data->l_base = newvs;
    data->l_mark = newvs + i;

    data->stacksize = newsize;
    data->s_last = data->s_base + newsize - 1;
    return 0;
}

#if EXP_YYPURE || defined(EXP_YY_NO_LEAKS)
static void exp_yyfreestack(EXP_YYSTACKDATA *data)
{
    free(data->s_base);
    free(data->l_base);
    memset(data, 0, sizeof(*data));
}
#else
#define exp_yyfreestack(data) /* nothing */
#endif

#define EXP_YYABORT  goto exp_yyabort
#define EXP_YYREJECT goto exp_yyabort
#define EXP_YYACCEPT goto exp_yyaccept
#define EXP_YYERROR  goto exp_yyerrlab

int
EXP_YYPARSE_DECL()
{
    int exp_yym, exp_yyn, exp_yystate;
#if EXP_YYDEBUG
    const char *exp_yys;

    if ((exp_yys = getenv("EXP_YYDEBUG")) != 0)
    {
        exp_yyn = *exp_yys;
        if (exp_yyn >= '0' && exp_yyn <= '9')
            exp_yydebug = exp_yyn - '0';
    }
#endif

    exp_yynerrs = 0;
    exp_yyerrflag = 0;
    exp_yychar = EXP_YYEMPTY;
    exp_yystate = 0;

#if EXP_YYPURE
    memset(&exp_yystack, 0, sizeof(exp_yystack));
#endif

    if (exp_yystack.s_base == NULL && exp_yygrowstack(&exp_yystack)) goto exp_yyoverflow;
    exp_yystack.s_mark = exp_yystack.s_base;
    exp_yystack.l_mark = exp_yystack.l_base;
    exp_yystate = 0;
    *exp_yystack.s_mark = 0;

exp_yyloop:
    if ((exp_yyn = exp_yydefred[exp_yystate]) != 0) goto exp_yyreduce;
    if (exp_yychar < 0)
    {
        if ((exp_yychar = EXP_YYLEX) < 0) exp_yychar = 0;
#if EXP_YYDEBUG
        if (exp_yydebug)
        {
            exp_yys = 0;
            if (exp_yychar <= EXP_YYMAXTOKEN) exp_yys = exp_yyname[exp_yychar];
            if (!exp_yys) exp_yys = "illegal-symbol";
            TRACE("%sdebug: state %d, reading %d (%s)\n",
                    EXP_YYPREFIX, exp_yystate, exp_yychar, exp_yys);
        }
#endif
    }
    if ((exp_yyn = exp_yysindex[exp_yystate]) && (exp_yyn += exp_yychar) >= 0 &&
            exp_yyn <= EXP_YYTABLESIZE && exp_yycheck[exp_yyn] == exp_yychar)
    {
#if EXP_YYDEBUG
        if (exp_yydebug)
            TRACE("%sdebug: state %d, shifting to state %d\n",
                    EXP_YYPREFIX, exp_yystate, exp_yytable[exp_yyn]);
#endif
        if (exp_yystack.s_mark >= exp_yystack.s_last && exp_yygrowstack(&exp_yystack))
        {
            goto exp_yyoverflow;
        }
        exp_yystate = exp_yytable[exp_yyn];
        *++exp_yystack.s_mark = exp_yytable[exp_yyn];
        *++exp_yystack.l_mark = exp_yylval;
        exp_yychar = EXP_YYEMPTY;
        if (exp_yyerrflag > 0)  --exp_yyerrflag;
        goto exp_yyloop;
    }
    if ((exp_yyn = exp_yyrindex[exp_yystate]) && (exp_yyn += exp_yychar) >= 0 &&
            exp_yyn <= EXP_YYTABLESIZE && exp_yycheck[exp_yyn] == exp_yychar)
    {
        exp_yyn = exp_yytable[exp_yyn];
        goto exp_yyreduce;
    }
    if (exp_yyerrflag) goto exp_yyinrecovery;

    exp_yyerror("syntax error");

    goto exp_yyerrlab;

exp_yyerrlab:
    ++exp_yynerrs;

exp_yyinrecovery:
    if (exp_yyerrflag < 3)
    {
        exp_yyerrflag = 3;
        for (;;)
        {
            if ((exp_yyn = exp_yysindex[*exp_yystack.s_mark]) && (exp_yyn += EXP_YYERRCODE) >= 0 &&
                    exp_yyn <= EXP_YYTABLESIZE && exp_yycheck[exp_yyn] == EXP_YYERRCODE)
            {
#if EXP_YYDEBUG
                if (exp_yydebug)
                    TRACE("%sdebug: state %d, error recovery shifting\
 to state %d\n", EXP_YYPREFIX, *exp_yystack.s_mark, exp_yytable[exp_yyn]);
#endif
                if (exp_yystack.s_mark >= exp_yystack.s_last && exp_yygrowstack(&exp_yystack))
                {
                    goto exp_yyoverflow;
                }
                exp_yystate = exp_yytable[exp_yyn];
                *++exp_yystack.s_mark = exp_yytable[exp_yyn];
                *++exp_yystack.l_mark = exp_yylval;
                goto exp_yyloop;
            }
            else
            {
#if EXP_YYDEBUG
                if (exp_yydebug)
                    TRACE("%sdebug: error recovery discarding state %d\n",
                            EXP_YYPREFIX, *exp_yystack.s_mark);
#endif
                if (exp_yystack.s_mark <= exp_yystack.s_base) goto exp_yyabort;
                --exp_yystack.s_mark;
                --exp_yystack.l_mark;
            }
        }
    }
    else
    {
        if (exp_yychar == 0) goto exp_yyabort;
#if EXP_YYDEBUG
        if (exp_yydebug)
        {
            exp_yys = 0;
            if (exp_yychar <= EXP_YYMAXTOKEN) exp_yys = exp_yyname[exp_yychar];
            if (!exp_yys) exp_yys = "illegal-symbol";
            TRACE("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    EXP_YYPREFIX, exp_yystate, exp_yychar, exp_yys);
        }
#endif
        exp_yychar = EXP_YYEMPTY;
        goto exp_yyloop;
    }

exp_yyreduce:
#if EXP_YYDEBUG
    if (exp_yydebug)
        TRACE("%sdebug: state %d, reducing by rule %d (%s)\n",
                EXP_YYPREFIX, exp_yystate, exp_yyn, exp_yyrule[exp_yyn]);
#endif
    exp_yym = exp_yylen[exp_yyn];
    if (exp_yym)
        exp_yyval = exp_yystack.l_mark[1-exp_yym];
    else
        memset(&exp_yyval, 0, sizeof exp_yyval);
    switch (exp_yyn)
    {
case 1:
	{ m_value = exp_yystack.l_mark[0].m_real; }
break;
case 2:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real + exp_yystack.l_mark[0].m_real; }
break;
case 3:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real - exp_yystack.l_mark[0].m_real; }
break;
case 4:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real * exp_yystack.l_mark[0].m_real; }
break;
case 5:
	{ 
											if (exp_yystack.l_mark[0].m_real != 0.0)
												exp_yyval.m_real = exp_yystack.l_mark[-2].m_real / exp_yystack.l_mark[0].m_real;
											else
												exp_yyval.m_real = 0.0;
										}
break;
case 6:
	{ exp_yyval.m_real = (double)( (int)exp_yystack.l_mark[-2].m_real % (int)exp_yystack.l_mark[0].m_real ); }
break;
case 7:
	{ exp_yyval.m_real = (double)( (int)exp_yystack.l_mark[-2].m_real & (int)exp_yystack.l_mark[0].m_real ); }
break;
case 8:
	{ exp_yyval.m_real = (double)( (int)exp_yystack.l_mark[-2].m_real | (int)exp_yystack.l_mark[0].m_real ); }
break;
case 9:
	{ exp_yyval.m_real = (double)( (int)exp_yystack.l_mark[-2].m_real ^ (int)exp_yystack.l_mark[0].m_real ); }
break;
case 10:
	{ exp_yyval.m_real = ONE(exp_yystack.l_mark[-2].m_real) && ONE(exp_yystack.l_mark[0].m_real); }
break;
case 11:
	{ exp_yyval.m_real = ONE(exp_yystack.l_mark[-2].m_real) || ONE(exp_yystack.l_mark[0].m_real); }
break;
case 12:
	{ exp_yyval.m_real = (ONE(exp_yystack.l_mark[-2].m_real) || ONE(exp_yystack.l_mark[0].m_real)) && (ZERO(exp_yystack.l_mark[-2].m_real) || ZERO(exp_yystack.l_mark[0].m_real)); }
break;
case 13:
	{ exp_yyval.m_real = min( exp_yystack.l_mark[-2].m_real, exp_yystack.l_mark[0].m_real ); }
break;
case 14:
	{ exp_yyval.m_real = max( exp_yystack.l_mark[-2].m_real, exp_yystack.l_mark[0].m_real ); }
break;
case 15:
	{ exp_yyval.m_real = EQUAL( exp_yystack.l_mark[-2].m_real, exp_yystack.l_mark[0].m_real ); }
break;
case 16:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real <= exp_yystack.l_mark[0].m_real; }
break;
case 17:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real >= exp_yystack.l_mark[0].m_real; }
break;
case 18:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real < exp_yystack.l_mark[0].m_real; }
break;
case 19:
	{ exp_yyval.m_real = exp_yystack.l_mark[-2].m_real > exp_yystack.l_mark[0].m_real; }
break;
case 20:
	{ exp_yyval.m_real = !EQUAL(exp_yystack.l_mark[-2].m_real, exp_yystack.l_mark[0].m_real); }
break;
case 21:
	{ exp_yyval.m_real = (int)exp_yystack.l_mark[-2].m_real << (int)exp_yystack.l_mark[0].m_real; }
break;
case 22:
	{ exp_yyval.m_real = (int)exp_yystack.l_mark[-2].m_real >> (int)exp_yystack.l_mark[0].m_real; }
break;
case 23:
	{ exp_yyval.m_real = RAD2DEG * asin( exp_yystack.l_mark[-1].m_real ); }
break;
case 24:
	{ exp_yyval.m_real = RAD2DEG * acos( exp_yystack.l_mark[-1].m_real ); }
break;
case 25:
	{ exp_yyval.m_real = RAD2DEG * atan( exp_yystack.l_mark[-1].m_real ); }
break;
case 26:
	{ exp_yyval.m_real = sin( DEG2RAD * exp_yystack.l_mark[-1].m_real ); }
break;
case 27:
	{ exp_yyval.m_real = cos( DEG2RAD * exp_yystack.l_mark[-1].m_real ); }
break;
case 28:
	{ exp_yyval.m_real = tan( DEG2RAD * exp_yystack.l_mark[-1].m_real ); }
break;
case 29:
	{ exp_yyval.m_real = exp_yystack.l_mark[-1].m_real * RAD2DEG; }
break;
case 30:
	{ exp_yyval.m_real = exp_yystack.l_mark[-1].m_real * DEG2RAD; }
break;
case 31:
	{ exp_yyval.m_real = exp_yystack.l_mark[-1].m_real; }
break;
case 32:
	{ exp_yyval.m_real = -exp_yystack.l_mark[0].m_real; }
break;
case 33:
	{ exp_yyval.m_real = ~(int)exp_yystack.l_mark[0].m_real; }
break;
case 34:
	{ exp_yyval.m_real = ZERO( exp_yystack.l_mark[0].m_real ); }
break;
case 35:
	{ exp_yyval.m_real = exp_yystack.l_mark[0].m_real; }
break;
case 36:
	{ exp_yyval.m_real = (double)exp_yystack.l_mark[0].m_int; }
break;
case 37:
	{ exp_yyval.m_real = exp_yystack.l_mark[0].m_real; }
break;
case 38:
	{ exp_yyval.m_int = (int)exp_yystack.l_mark[0].m_int; }
break;
case 39:
	{ exp_yyval.m_int = (int)exp_yystack.l_mark[0].m_int; }
break;
    }
    exp_yystack.s_mark -= exp_yym;
    exp_yystate = *exp_yystack.s_mark;
    exp_yystack.l_mark -= exp_yym;
    exp_yym = exp_yylhs[exp_yyn];
    if (exp_yystate == 0 && exp_yym == 0)
    {
#if EXP_YYDEBUG
        if (exp_yydebug)
            TRACE("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", EXP_YYPREFIX, EXP_YYFINAL);
#endif
        exp_yystate = EXP_YYFINAL;
        *++exp_yystack.s_mark = EXP_YYFINAL;
        *++exp_yystack.l_mark = exp_yyval;
        if (exp_yychar < 0)
        {
            if ((exp_yychar = EXP_YYLEX) < 0) exp_yychar = 0;
#if EXP_YYDEBUG
            if (exp_yydebug)
            {
                exp_yys = 0;
                if (exp_yychar <= EXP_YYMAXTOKEN) exp_yys = exp_yyname[exp_yychar];
                if (!exp_yys) exp_yys = "illegal-symbol";
                TRACE("%sdebug: state %d, reading %d (%s)\n",
                        EXP_YYPREFIX, EXP_YYFINAL, exp_yychar, exp_yys);
            }
#endif
        }
        if (exp_yychar == 0) goto exp_yyaccept;
        goto exp_yyloop;
    }
    if ((exp_yyn = exp_yygindex[exp_yym]) && (exp_yyn += exp_yystate) >= 0 &&
            exp_yyn <= EXP_YYTABLESIZE && exp_yycheck[exp_yyn] == exp_yystate)
        exp_yystate = exp_yytable[exp_yyn];
    else
        exp_yystate = exp_yydgoto[exp_yym];
#if EXP_YYDEBUG
    if (exp_yydebug)
        TRACE("%sdebug: after reduction, shifting from state %d \
to state %d\n", EXP_YYPREFIX, *exp_yystack.s_mark, exp_yystate);
#endif
    if (exp_yystack.s_mark >= exp_yystack.s_last && exp_yygrowstack(&exp_yystack))
    {
        goto exp_yyoverflow;
    }
    *++exp_yystack.s_mark = (short) exp_yystate;
    *++exp_yystack.l_mark = exp_yyval;
    goto exp_yyloop;

exp_yyoverflow:
    exp_yyerror("yacc stack overflow");

exp_yyabort:
    exp_yyfreestack(&exp_yystack);
    return (1);

exp_yyaccept:
    exp_yyfreestack(&exp_yystack);
    return (0);
}
