/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ci_System_Msg */

#ifndef _Included_Ci_System_Msg
#define _Included_Ci_System_Msg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Ci_System_Msg
 * Method:    IsMessageActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Ci_System_Msg_IsMessageActive
  (JNIEnv *, jclass);

/*
 * Class:     Ci_System_Msg
 * Method:    MessageMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Ci_System_Msg_MessageMsg
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Ci_System_Msg
 * Method:    IsDebugActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Ci_System_Msg_IsDebugActive
  (JNIEnv *, jclass);

/*
 * Class:     Ci_System_Msg
 * Method:    DebugMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Ci_System_Msg_DebugMsg
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Ci_System_Msg
 * Method:    DiagnosticMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Ci_System_Msg_DiagnosticMsg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
