/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ci_System_OutSys */

#ifndef _Included_Ci_System_OutSys
#define _Included_Ci_System_OutSys
#ifdef __cplusplus
extern "C" {
#endif
#undef Ci_System_OutSys_NONE
#define Ci_System_OutSys_NONE 0L
#undef Ci_System_OutSys_EDITOR
#define Ci_System_OutSys_EDITOR -1L
#undef Ci_System_OutSys_FILE
#define Ci_System_OutSys_FILE 1L
/*
 * Class:     Ci_System_OutSys
 * Method:    Path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Ci_System_OutSys_Path
  (JNIEnv *, jobject);

/*
 * Class:     Ci_System_OutSys
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Ci_System_OutSys_Open
  (JNIEnv *, jobject);

/*
 * Class:     Ci_System_OutSys
 * Method:    OpenAsBinary
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Ci_System_OutSys_OpenAsBinary
  (JNIEnv *, jobject);

/*
 * Class:     Ci_System_OutSys
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Ci_System_OutSys_Close
  (JNIEnv *, jobject);

/*
 * Class:     Ci_System_OutSys
 * Method:    Type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Ci_System_OutSys_Type
  (JNIEnv *, jobject);

/*
 * Class:     Ci_System_OutSys
 * Method:    IsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Ci_System_OutSys_IsValid
  (JNIEnv *, jobject);

/*
 * Class:     Ci_System_OutSys
 * Method:    Export
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Ci_System_OutSys_Export
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
