//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AdvMach.rc
//
#define ID_DELETE                       3
#define IDD_ABOUTBOX                    100
#define IDD_RETURN_DLG                  101
#define IDR_MAINFRAME                   128
#define IDR_WHITNETYPE                  129
#define IDD_SIMULATION                  130
#define IDD_PLATEN_CONFIGURATION        131
#define IDD_OFFLOAD_CONFIGURATION       132
#define IDD_REPORT                      133
#define IDD_PROPERTIES                  134
#define IDD_UNITS_CONVERSION            136
#define IDD_TURRET_CFG                  137
#define IDB_CHECK_OFF                   138
#define IDB_CHECK_ON                    139
#define IDD_PROGRAM                     141
#define IDD_ADJUST_ORIGIN               142
#define IDD_TRAP_DOOR                   143
#define IDD_OFFSET_CURVE                144
#define IDD_OFFSET_PROFILE              145
#define IDD_DEBUG                       148
#define IDD_ADVMACH_CURVE               149
#define IDD_ADVMACH_PROFILE             150
#define IDD_CREATE_POINT                151
#define IDD_RETURN                      152
#define IDD_MODIFY_POINT                153
#define IDD_POINT                       153
#define IDD_MODIFY_LINE                 154
#define IDD_LINE                        154
#define IDD_COLOR_DLG_BAR               155
#define IDC_COLOR_DLG_BAR               156
#define IDD_HOLE                        158
#define IDD_GROUP                       159
#define IDC_CURSOR1                     160
#define IDD_PROFILE                     161
#define IDD_ARC                         162
#define IDD_DEFINE_VIEW                 163
#define IDC_NEXT                        1001
#define IDC_CUSTOM1                     1002
#define IDC_OFFLOAD_DX                  1003
#define IDC_OFFLOAD_DY                  1004
#define IDC_PLATEN_GRID                 1005
#define IDC_ADD_CUP                     1006
#define IDC_PLATEN_PICTURE              1007
#define IDC_OFFLOAD_GRID                1008
#define IDC_DEL_CUP                     1008
#define IDC_OFFLOAD_PICTURE             1009
#define IDC_ADD_CELL                    1010
#define IDC_UPDATE_OFFLOAD              1011
#define IDC_UPDATE_PLATEN               1012
#define IDC_DEL_CELL                    1012
#define IDC_PLATEN_DX                   1013
#define IDC_PLATEN_DY                   1014
#define IDC_PLATEN_CFG                  1015
#define IDC_XSHIFT                      1015
#define IDC_OFFLOAD_CFG                 1016
#define IDC_YSHIFT                      1016
#define IDC_LOAD                        1017
#define IDC_SAVE                        1018
#define IDC_RADIO                       1021
#define IDC_TURRET_PICTURE              1022
#define IDC_RADIO2                      1023
#define IDC_RADIO3                      1024
#define IDC_TURRET_GRID                 1025
#define IDC_UPDATE_TURRET               1026
#define IDC_NC_CODE                     1027
#define IDC_PREV                        1028
#define IDC_UPDATE                      1032
#define IDC_ADJUST                      1034
#define IDC_XTORCH                      1035
#define IDC_YTORCH                      1036
#define IDC_CLEAR                       1040
#define IDC_EDIT1                       1041
#define IDC_EDIT2                       1042
#define IDC_WIDTH                       1043
#define IDC_EDIT4                       1043
#define IDC_HEIGHT                      1044
#define IDC_EDIT5                       1044
#define IDC_EDIT8                       1045
#define IDC_RADIO1                      1046
#define IDC_LIST1                       1047
#define IDC_RADIO4                      1048
#define IDC_EDIT3                       1048
#define IDC_EDIT6                       1049
#define IDC_RED                         1049
#define IDC_GREEN                       1050
#define IDC_DIAM                        1050
#define IDC_BLUE                        1051
#define IDC_DEPTH                       1051
#define IDC_CYAN                        1052
#define IDC_MAGENTA                     1053
#define ID_CREATE                       1053
#define IDC_YELLOW                      1054
#define IDC_LIST                        1054
#define IDC_LIGHT_BLUE                  1055
#define IDC_GROUP_NAME                  1055
#define IDC_WHITE                       1056
#define IDC_PROFILE_NAME                1057
#define IDC_CHECK1                      1059
#define ID_UPDATE                       1060
#define IDC_XMIN                        1061
#define IDC_YMIN                        1062
#define IDC_XMAX                        1063
#define IDC_YMAX                        1064
#define IDC_ENTITY_NAME                 1065
#define IDC_NEW                         1066
#define ID_VIEW_WINDOW                  32718
#define ID_VIEW_FULL                    32719
#define ID_EDIT_SELECT                  32810
#define ID_EDIT_REVERT                  32811
#define ID_EDIT_CLEAR_SELECTED          32812
#define ID_EDIT_DELETE_SELECTED         32813
#define ID_CREATE_POINT                 32814
#define ID_CREATE_LINE                  32815
#define ID_CREATE_ARC                   32816
#define ID_CREATE_HOLE                  32817
#define ID_MODIFY_POINT                 32818
#define ID_MODIFY_LINE                  32819
#define ID_VIEW_REFRESH                 32820
#define ID_MODIFY_ARC                   32821
#define ID_MODIFY_HOLE                  32822
#define ID_MODIFY                       32823
#define ID_RED                          32831
#define ID_GREEN                        32832
#define ID_BLUE                         32833
#define ID_CYAN                         32834
#define ID_MAGENTA                      32835
#define ID_YELLOW                       32836
#define ID_CREATE_GROUP                 32837
#define ID_CREATE_PROFILE               32840
#define ID_VIEW_DEFINE                  32842

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32843
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
