/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Weng_System_ErrSys */

#ifndef _Included_Weng_System_ErrSys
#define _Included_Weng_System_ErrSys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Weng_System_ErrSys
 * Method:    IsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Weng_System_ErrSys_IsValid
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_ErrSys
 * Method:    Export
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Weng_System_ErrSys_Export
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
