/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Weng_System_OutSys */

#ifndef _Included_Weng_System_OutSys
#define _Included_Weng_System_OutSys
#ifdef __cplusplus
extern "C" {
#endif
#undef Weng_System_OutSys_NONE
#define Weng_System_OutSys_NONE 0L
#undef Weng_System_OutSys_EDITOR
#define Weng_System_OutSys_EDITOR 1L
#undef Weng_System_OutSys_FILE
#define Weng_System_OutSys_FILE 2L
/*
 * Class:     Weng_System_OutSys
 * Method:    Path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Weng_System_OutSys_Path
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Weng_System_OutSys_Open
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Weng_System_OutSys_OpenForAppend
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    OpenAsBinary
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Weng_System_OutSys_OpenAsBinary
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Weng_System_OutSys_Close
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    Type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Weng_System_OutSys_Type
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    IsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Weng_System_OutSys_IsValid
  (JNIEnv *, jobject);

/*
 * Class:     Weng_System_OutSys
 * Method:    Export
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Weng_System_OutSys_Export
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
