//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//  NOTE  NOTE  NOTE  NOTE  NOTE  NOTE  NOTE  NOTE  NOTE  NOTE
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// The code for loading the JVM was extracted from Sun's src.jar
//
//       eg. c:\jdk1.2.2\src.jar -- src/launcher/java_md.c
//
// As a reminder, the jar file is really just a renamed zip file.
// This convention was introduced by Sun to help prevent your
// average person from attempting to unzip their binaries.
// 
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#include <stdlib.h>
#include <stdio.h>

#include <sys/types.h>
#include <sys/stat.h>

#include "stdafx.h"
#include "cmn_resource.h"
// #include "Register.h"
#include "Vm.h"

#include "Path.h"
#include "Msg.h"
#include "ErrSys.h"

#include "portable.h"

HMODULE m_hLibModule;

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

static jint __stdcall JVM_Vfprintf( FILE* f, const char* format, va_list args );
static void __stdcall JVM_Exit( jint exitCode );
static void __stdcall JVM_Abort();

static jboolean GetApplicationHome(char *buf, jint bufsize);
static jobjectArray NewPlatformStringArray( JNIEnv* env );

// 'jvmDllFolder' the folder where you might expect it to be found.
static CString JVMDLLPathGet( const CString& jvmDllFolder );

static void Message( const char* format, ... );


static CString JVMENVNAME("WengVmEnv");

// Java Virtual Machine (JVM) and environment.
static JNIEnv* g_env = NULL;
static JavaVM* g_jvm = NULL;

static CString g_classPath;
static CString g_storagePath;


//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// I'm not real keen on doing this but it makes some things easier.
// For use by void JVMArgsInit( JavaVMInitArgs* args )

char g_app_path[MAXPATHLEN];
char g_class_path[MAXPATHLEN];

const int NUMOPTIONS = 5;
JavaVMOption g_options[ NUMOPTIONS ];

static void JVMArgsInit( JavaVMInitArgs* args );
//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

static CReturn WengVmEnvStart();
static CReturn StoragePathSet( const CString& storagePath );



static unsigned char debug = '0';  // linker fodder

static bool DEBUGMSGS = false;



//////////////////////////////////////////////////////////////////////
// The classpath and storagePath parameters are critical to proper
// java VM execution.
//
// classPath is passed to the java compiler as in normal execution
//     eg. 'javac -classpath <classPath> Foo.java'
//
// storagePath is also passed to the java compiler as the '-d' option,
// the destination directory for the class-file that is generated by
// the compiler.  Though less apparent, storagePath is also used by
// the java VM via the java class SimpleLoader.  The entry point to
// its use is CVm::Execute().
//
// Failures can occur for many reasons:
//
// 1. Be sure to use the correct version of javac when compiling
//    the java-source for Weng.jar. Failure to do this results in
//    the message "VM failed to find class <WengVmEnv>". Likewise,
//    the compiler version must match the JVM version.
//
//    Your system environment, system variable PATH *must* specify
//    the appropriate paths; these were broken during experimentation
//    with jdk1.6 -- a painful lesson :-(
//
//    For posterity, the PATH necessary path components at this time are:
//       C:\jdk1.3.1\bin;C:\jdk1.3.1\jre\bin;
//
//    When things were broken, the path components were:
//       C:\Program Files\Java\jdk1.6.0_22\bin;C:\Program Files\Java\jdk1.6.0_22\jre\bin\client;
//
//    I'm not sure if the CurrentVersion setting (in the registry under
//    HKEY_LOCAL_MACHINE\Software\JavaSoft for jdk & jre) matter.
//
// 2. If you get an error stating some class can not be found:
//
//  .1 Validate your classpath.
//  .2 Make sure the missing class is either in classpath or in
//     a jar (or zip) that is in the classpath.
//  .3 Make sure all classes referenced by the supposed missing
//     class are also in the classpath (per .2 above)
//  .4 Make sure system-loaded libaries (ie. dlls loaded via calls
//     to System.loadLibrary) are present.
//
// 3. If you get an error message "FATAL ERROR <some garbage>"
//    verify the JNI method used matches the method signature.
//      eg. this problem was discovered with the following case
//            g_env->GetStaticMethodIDC(...,(L...;)V)
//            g_env->CallStaticIntMethod(...)
//
// 4. For the error message "Failed to execute method <execute>"
//    This is probably caused by an exception being thrown as a
//    result of referencing null in a java file.
//
// 5. For "VM failed to execute <main>"
//    This is likely caused by using the wrong version of javac.

CReturn CVm::Init( const CString& jvmDllFolder, const CString& classPath, const CString& storagePath )
{
	// eg. "c:\Ci\AdvMach\Debug\dlls\Ci.zip;c:\jdk1.3.1\lib\tools.jar;c:\jdk1.3.1\jre\lib\rt.jar"
	g_classPath = classPath;
	g_storagePath = storagePath;

	CReturn status = JVMInit( jvmDllFolder );
	return status;
}

void CVm::Term()
{
	JVMTerm();
}

bool CVm::IsOk()
{
	return (g_jvm != NULL);
}

CReturn CVm::Compile( const CString& javaClassPath )
{
	CString errMsg;
	CReturn status;

	if (DEBUGMSGS) MsgInit();  // support for Msg.Display() in WengVmEnv.java

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// Find our virtual machine environment class.
    jclass cls = g_env->FindClass( JVMENVNAME );
    
	if (g_env->ExceptionOccurred() || cls == 0)
	{
		errMsg.Format( "VM failed to find class <%s>", JVMENVNAME );
		status.Fatal( IDS_JVM_EXCEPTION, errMsg );
		return status;
	}

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// Find the compile() method.
    jmethodID mid = g_env->GetStaticMethodID(
		cls, "compile", "(Ljava/lang/String;Ljava/lang/String;)I" );

	if (g_env->ExceptionOccurred() || mid == 0)
	{
		status.Fatal( IDS_JVM_EXCEPTION, "Failed to find method <compile>" );
		return status;
	}

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// The class path should include the
	// path to the top level java file.
	CString completeClassPath;
	CPath tmpPath( javaClassPath );
	completeClassPath.Format( "%s;%s", tmpPath.DriveDir(), g_classPath );

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// Execute the compile() method.
	jstring classPath = g_env->NewStringUTF( completeClassPath );
	jstring javaFile = g_env->NewStringUTF( javaClassPath );

	ErrSysInit();

	// NOTE: A non-zero result is not necessarily fatal!
	int result = g_env->CallStaticIntMethod( cls, mid, classPath, javaFile );

	ErrSysTerm();

	if (DEBUGMSGS) MsgTerm();  // support for Msg.Display() in WengVmEnv.java

	if ( g_env->ExceptionOccurred() )
	{
		g_env->ExceptionDescribe();
		status.Fatal( IDS_JVM_EXCEPTION, "Failed to execute method <compile>" );
	}
	else if (ErrSysCount() > 0)
	{
		status = STATUS_ERROR;  // compilation errors
	}

	return status;
}

CReturn CVm::Execute( const CString& javaClassPath, bool localStoragePath )
{
	CString errMsg;
	CReturn status;

	CPath path( javaClassPath );

	// Find our virtual machine environment class.
    jclass cls = g_env->FindClass( JVMENVNAME );

	if (g_env->ExceptionOccurred() || cls == 0)
	{
		errMsg.Format( "VM failed to find class <%s>", JVMENVNAME );
		status.Fatal( IDS_JVM_EXCEPTION, errMsg );
		return status;
	}

	status = StoragePathSet( (localStoragePath ? path.DriveDir() : g_storagePath) );
	if ( !status.IsOk() )
		return status;

	// Following java standards, the class name
	// must match the source file name.
	CString className = path.FileName();
	jstring machineName = g_env->NewStringUTF( className );


	// Find the execute() method.
	jmethodID mid = g_env->GetStaticMethodID( cls, "execute", "(Ljava/lang/String;)I" );
    
	if (g_env->ExceptionOccurred() || mid == 0)
	{
		g_env->ExceptionDescribe();
		status.Fatal( IDS_JVM_EXCEPTION, "Failed to find method <execute>" );
		return status;
	}


	// Execute the execute() method.
	int result = g_env->CallStaticIntMethod( cls, mid, machineName );

	if (g_env->ExceptionOccurred() || result != 0)
	{
		g_env->ExceptionDescribe();
		status.Fatal( IDS_JVM_EXCEPTION, "Failed to execute method <execute>" );
		return status;
	}

	return status;
}

CReturn CVm::JVMInit( const CString& jvmDllFolder )
{
	CReturn status;

	// bool debug = (CRegister::Debug( "jvminit" ) != 0);
	bool debug = false;

	CString jvmDllPath = JVMDLLPathGet( jvmDllFolder );

	if ( jvmDllPath.IsEmpty() )
	{
		MessageBox( NULL, "FATAL ERROR: Unable to find jvm.dll", "Error", MB_OK );
		status.Fatal( IDS_JVM_EXCEPTION, "Unable to find jvm.dll" );
	}
	else
	{
		if ( debug ) Message( "Calling LoadLibrary(\"%s\")", jvmDllPath );

		HINSTANCE hinst = LoadLibrary( jvmDllPath );
		if ( debug ) Message( "hinst: 0x%08x", hinst );

		if (hinst == 0)
		{
			MessageBox( NULL, "FATAL ERROR: LoadLibrary() failed.", "Error", MB_OK );
			status.Fatal( IDS_JVM_EXCEPTION, "LoadLibrary() failed." );
		}
		else
		{
			JavaVMInitArgs args;
			JVMArgsInit( &args );

			if ( debug ) Message( "Calling JNI_CreateJavaVM()" );

			jint result = JNI_CreateJavaVM( &g_jvm, (void**) &g_env, &args );
			if ( debug ) Message( "result:%d", result );

			if (result == 0)
			{
				status = WengVmEnvStart();
				if ( status.IsOk() )
					status = StoragePathSet( g_storagePath );
			}
			else
			{
				status.Fatal( IDS_JVM_EXCEPTION, "VM failed to initialize" );
				MessageBox( NULL, status.LastErrorMsg(), "foo", MB_OK );
			}
		}
	}

	return status;
}

void CVm::JVMTerm()
{
	if (g_jvm != NULL)
	{
		g_jvm->DestroyJavaVM();
		g_jvm = NULL;
	}

	if (m_hLibModule != NULL)
	{
		FreeLibrary( m_hLibModule );
	}

	MsgTerm();
}


//=-=-=-=-=-=-=-=-=-=-==-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

static jint __stdcall JVM_Vfprintf( FILE* f, const char* format, va_list args )
{
	CString errMsg;
	errMsg.Format( format, args );
	MsgDisplay( errMsg );
	return 0;
}

static void __stdcall JVM_Exit( jint exitCode )
{
	CString msg;
	msg.Format( "Exit code %d", exitCode );
	MsgDisplay( msg );
}

static void __stdcall JVM_Abort()
{
	MsgDisplay( "JVM Aborted" );
}


//=-=-=-=-=-=-=-=-=-=-==-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// The following functions are from
//    c:\jdk1.3\src.jar -- src/launcher/java_md.c
//=-=-=-=-=-=-=-=-=-=-==-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

static jboolean GetApplicationHome( char *buf, jint bufsize )
{
    char *cp;
    GetModuleFileName(0, buf, bufsize);
    *strrchr(buf, '\\') = '\0'; /* remove .exe file name */
    if ((cp = strrchr(buf, '\\')) == 0)
	{
		/* This happens if the application is in a drive root, and
		 * there is no bin directory. */
		buf[0] = '\0';
		return JNI_FALSE;
    }

    *cp = '\0';  /* remove the bin\ part */
    return JNI_TRUE;
}

static jobjectArray NewPlatformStringArray( JNIEnv* env )
{
	jclass cls = env->FindClass( "java/lang/String" );
	jobjectArray ary = env->NewObjectArray( 1, cls, 0 );

	env->SetObjectArrayElement( ary, 0, NULL );

	return ary;
}

void Message( const char* format, ... )
{
	char msg[1024];

	va_list params;
	va_start( params, format );

	vsprintf_s( msg, 1024, format, params );

	MessageBox( NULL, msg, "JVMInit", MB_OK ); 
}

CString JVMDLLPathGet( const CString& jvmDllFolder )
{
	CString jvmDllPath;

	if ( !jvmDllFolder.IsEmpty() )
	{
	    struct stat s;

		jvmDllPath.Format( "%s%s", jvmDllFolder,"\\bin\\client\\jvm.dll" );

		if (stat(jvmDllPath, &s) != 0)
			jvmDllPath = "";  // not found
	}

	return jvmDllPath;
}

void JVMArgsInit( JavaVMInitArgs* args )
{
	char home[MAXPATHLEN];
	GetApplicationHome( home, sizeof(home) );

	sprintf_s( g_app_path, MAXPATHLEN, "-Dapplication.home=%s", home );
	sprintf_s( g_class_path, MAXPATHLEN, "-Djava.class.path=%s", g_classPath );
	
	//------

	memset( &g_options, 0, sizeof(g_options) );

	g_options[0].optionString = g_app_path;
	g_options[1].optionString = g_class_path;

	g_options[2].optionString = "vfprintf";
	g_options[2].extraInfo = &JVM_Vfprintf;

	g_options[3].optionString = "abort";
	g_options[3].extraInfo = &JVM_Abort;

	g_options[4].optionString = "exit";
	g_options[4].extraInfo = &JVM_Exit;

	//------

	memset( args, 0, sizeof(*args) );

	args->version  = JNI_VERSION_1_6;
	args->nOptions = NUMOPTIONS;
	args->options  = g_options;
	args->ignoreUnrecognized = false;
}

CReturn WengVmEnvStart()
{
	CReturn status;

	jclass cls;
	jmethodID mid;

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// Find our virtual machine environment class (WengVmEnv).
	cls = g_env->FindClass( JVMENVNAME );
        
	if (g_env->ExceptionOccurred() || cls == 0)
	{
		CString errMsg;
		errMsg.Format( "VM failed to find class <%s>", JVMENVNAME );
		status.User( IDS_JVM_EXCEPTION, errMsg );
		MessageBox( NULL, status.LastErrorMsg(), "foo", MB_OK );
		return status;
	}

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// Find the main() method.
	mid = g_env->GetStaticMethodID( cls, "main", "([Ljava/lang/String;)V" );
        
	if (g_env->ExceptionOccurred() || mid == 0)
	{
		status.Fatal( IDS_JVM_EXCEPTION, "VM failed to find method <main>" );
		MessageBox( NULL, status.LastErrorMsg(), "foo", MB_OK );
		return status;
	}

	if (DEBUGMSGS) MsgInit();  // support for Msg.Display() in WengVmEnv.java

	//=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	// Execute the main() method.
	jobjectArray foo = NewPlatformStringArray( g_env );
	g_env->CallStaticVoidMethod( cls, mid, foo );
        
	if ( g_env->ExceptionOccurred() )
	{
		status.Fatal( IDS_JVM_EXCEPTION, "VM failed to execute <main>" );
		MessageBox( NULL, status.LastErrorMsg(), "foo", MB_OK );
		return status;
	}
	
	if (DEBUGMSGS) MsgTerm();  // support for Msg.Display() in WengVmEnv.java

	return status;
}

CReturn StoragePathSet( const CString& storagePath )
{
	CReturn status;

	// Find our virtual machine environment class.
    jclass cls = g_env->FindClass( JVMENVNAME );

	// Find the StoragePathSet() method.
	jmethodID mid = g_env->GetStaticMethodID( cls, "StoragePathSet", "(Ljava/lang/String;)V" );
        
	if (g_env->ExceptionOccurred() || (mid == 0))
	{
		status.Fatal( IDS_JVM_EXCEPTION, "VM failed to find method <StoragePathSet>" );
	}
	else
	{
		// Execute the StoragePathSet() method.
		jstring jPath = g_env->NewStringUTF( storagePath );
		g_env->CallStaticVoidMethod( cls, mid, jPath );
        
		if ( g_env->ExceptionOccurred() )
			status.Fatal( IDS_JVM_EXCEPTION, "VM failed to execute <StoragePathSet>" );
	}

	return status;
}
