/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ci_System_CiPortal */

#ifndef _Included_Ci_System_CiPortal
#define _Included_Ci_System_CiPortal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Ci_System_CiPortal
 * Method:    Execute
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Ci_System_CiPortal_Execute
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Ci_System_CiPortal
 * Method:    IntGet
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Ci_System_CiPortal_IntGet__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Ci_System_CiPortal
 * Method:    IntGet
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Ci_System_CiPortal_IntGet__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     Ci_System_CiPortal
 * Method:    DoubleGet
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_Ci_System_CiPortal_DoubleGet__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Ci_System_CiPortal
 * Method:    DoubleGet
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_Ci_System_CiPortal_DoubleGet__Ljava_lang_String_2D
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     Ci_System_CiPortal
 * Method:    StringGet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Ci_System_CiPortal_StringGet__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Ci_System_CiPortal
 * Method:    StringGet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Ci_System_CiPortal_StringGet__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
