
#ifndef _CI_CODEGEN_CLFILE_H
#define _CI_CODEGEN_CLFILE_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "stdafx.h"
#include <jni.h>
/* Header for class Ci_CodeGen_Clfile */

#ifndef _Included_Ci_CodeGen_Clfile
#define _Included_Ci_CodeGen_Clfile
#ifdef __cplusplus
extern "C" {
#endif
#undef Ci_CodeGen_Clfile_eRapid
#define Ci_CodeGen_Clfile_eRapid 0L
#undef Ci_CodeGen_Clfile_eLine
#define Ci_CodeGen_Clfile_eLine 1L
#undef Ci_CodeGen_Clfile_eCwArc
#define Ci_CodeGen_Clfile_eCwArc 2L
#undef Ci_CodeGen_Clfile_eCcwArc
#define Ci_CodeGen_Clfile_eCcwArc 3L
#undef Ci_CodeGen_Clfile_eFirstPoint
#define Ci_CodeGen_Clfile_eFirstPoint 20L
#undef Ci_CodeGen_Clfile_eFirstDrillHole
#define Ci_CodeGen_Clfile_eFirstDrillHole 21L
#undef Ci_CodeGen_Clfile_eFirstPeckHole
#define Ci_CodeGen_Clfile_eFirstPeckHole 22L
#undef Ci_CodeGen_Clfile_ePoint
#define Ci_CodeGen_Clfile_ePoint 23L
#undef Ci_CodeGen_Clfile_eDrillHole
#define Ci_CodeGen_Clfile_eDrillHole 24L
#undef Ci_CodeGen_Clfile_ePeckHole
#define Ci_CodeGen_Clfile_ePeckHole 25L
#undef Ci_CodeGen_Clfile_eTextCommand
#define Ci_CodeGen_Clfile_eTextCommand 44L
#undef Ci_CodeGen_Clfile_eUserCommand
#define Ci_CodeGen_Clfile_eUserCommand 45L
#undef Ci_CodeGen_Clfile_eHoldCommand
#define Ci_CodeGen_Clfile_eHoldCommand 46L
#undef Ci_CodeGen_Clfile_eRepoCommand
#define Ci_CodeGen_Clfile_eRepoCommand 47L
#undef Ci_CodeGen_Clfile_eStopCommand
#define Ci_CodeGen_Clfile_eStopCommand 48L
#undef Ci_CodeGen_Clfile_eDropCommand
#define Ci_CodeGen_Clfile_eDropCommand 49L
#undef Ci_CodeGen_Clfile_eClampInfo
#define Ci_CodeGen_Clfile_eClampInfo 50L
#undef Ci_CodeGen_Clfile_eSpeedRampInfo
#define Ci_CodeGen_Clfile_eSpeedRampInfo 51L
#undef Ci_CodeGen_Clfile_eMainBegin
#define Ci_CodeGen_Clfile_eMainBegin 60L
#undef Ci_CodeGen_Clfile_eMainEnd
#define Ci_CodeGen_Clfile_eMainEnd 61L
#undef Ci_CodeGen_Clfile_eStartProgBegin
#define Ci_CodeGen_Clfile_eStartProgBegin 62L
#undef Ci_CodeGen_Clfile_eStartProgEnd
#define Ci_CodeGen_Clfile_eStartProgEnd 63L
#undef Ci_CodeGen_Clfile_eEndProgBegin
#define Ci_CodeGen_Clfile_eEndProgBegin 64L
#undef Ci_CodeGen_Clfile_eEndProgEnd
#define Ci_CodeGen_Clfile_eEndProgEnd 65L
#undef Ci_CodeGen_Clfile_eToolChangeBegin
#define Ci_CodeGen_Clfile_eToolChangeBegin 66L
#undef Ci_CodeGen_Clfile_eToolChangeEnd
#define Ci_CodeGen_Clfile_eToolChangeEnd 67L
#undef Ci_CodeGen_Clfile_eSubDefBegin
#define Ci_CodeGen_Clfile_eSubDefBegin 80L
#undef Ci_CodeGen_Clfile_eSubDefEnd
#define Ci_CodeGen_Clfile_eSubDefEnd 81L
#undef Ci_CodeGen_Clfile_eSubCall
#define Ci_CodeGen_Clfile_eSubCall 82L
/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    Count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Ci_CodeGen_Clfile_Count
  (JNIEnv *, jobject);

/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    Int
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Ci_CodeGen_Clfile_IntGet
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    Dbl
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_Ci_CodeGen_Clfile_DoubleGet
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    Str
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Ci_CodeGen_Clfile_StringGet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    Read
 * Signature: (I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_Ci_CodeGen_Clfile_Read
  (JNIEnv *, jobject, jint, jintArray, jintArray, jdoubleArray);

/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    StatePush
 * Signature: ([I[I[D)V
 */
JNIEXPORT void JNICALL Java_Ci_CodeGen_Clfile_StatePush
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray);

/*
 * Class:     Ci_CodeGen_Clfile
 * Method:    StatePop
 * Signature: ([I[I[D)V
 */
JNIEXPORT void JNICALL Java_Ci_CodeGen_Clfile_StatePop
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif

VOID_DLL CI_ClfileInit( CClfile* clfile );
VOID_DLL CI_ClfileTerm();

#endif
